from __future__ import annotations

SENTENCES_PART1 = {
    "person": {
        "beginner": [
            ("The person walks to school.", "simple present"),
            ("She has a red bag.", "simple present - has"),
            ("He ate his lunch quickly.", "simple past"),
            ("The person is tall.", "present - to be"),
            ("She smiled at me.", "simple past"),
        ],
        "elementary": [
            ("Can you see the person near the door?", "question with can"),
            ("There is a person waiting outside.", "there is"),
            ("Could the person help us find the way?", "could - polite request"),
            ("Is the person wearing a blue shirt?", "present continuous question"),
            ("There are two people sitting on the bench.", "there are - plural"),
        ],
        "intermediate": [
            ("The person ran faster than I expected, and she reached the bus stop on time.", "compound sentence + comparative"),
            ("If the person is friendly, it is easy to ask for directions.", "first conditional"),
            ("The person looked tired, but she kept walking without stopping.", "compound sentence - contrast"),
            ("He is taller than his brother and speaks more clearly too.", "comparative adjective"),
            ("The person finished her homework, then she went outside to play.", "compound sentence - sequence"),
        ],
        "upper_intermediate": [
            ("The person who helped me yesterday turned out to be my neighbour's sister.", "relative clause - who"),
            ("A decision was made by the person in charge before anyone else arrived.", "passive voice"),
            ("The person standing near the gate has been waiting for more than an hour.", "present perfect continuous"),
            ("It was the person with the yellow umbrella who directed us to the right street.", "cleft sentence"),
            ("The person whose bag was left on the bus reported it to the driver immediately.", "relative clause - whose"),
        ],
        "advanced": [
            ("Despite feeling exhausted after a long journey, the person managed to deliver an encouraging speech to the waiting crowd.", "complex sentence - concession"),
            ("The person, widely regarded as the most knowledgeable in the field, chose to remain humble and approachable.", "non-defining relative clause"),
            ("It is often the quiet, unassuming person who contributes most significantly to the success of a group effort.", "cleft sentence + superlative"),
            ("Having grown up in a multilingual household, the person found it remarkably easy to acquire new languages.", "participle clause - having done"),
            ("The extent to which a person's attitude shapes their daily experience is frequently underestimated by researchers.", "noun clause + passive"),
        ],
    },
    "bicycle": {
        "beginner": [
            ("I ride my bicycle every day.", "simple present"),
            ("The bicycle is red and shiny.", "present - to be + adjectives"),
            ("She parked her bicycle near the tree.", "simple past"),
            ("My bicycle has two wheels.", "simple present - has"),
            ("He fell off his bicycle.", "simple past"),
        ],
        "elementary": [
            ("Can you ride a bicycle without using your hands?", "question with can"),
            ("There is a bicycle parked outside the shop.", "there is"),
            ("Could you move your bicycle so I can pass?", "could - polite request"),
            ("Is that bicycle yours or your brother's?", "yes/no question - possession"),
            ("There are many bicycles in the school parking area.", "there are - plural"),
        ],
        "intermediate": [
            ("If you ride your bicycle to school, you will save money and stay fit.", "first conditional"),
            ("The bicycle is older than mine, but it still works perfectly.", "comparative adjective"),
            ("She bought a new bicycle, and now she cycles to the market every morning.", "compound sentence"),
            ("Riding a bicycle is cheaper than taking a bus every single day.", "gerund subject + comparative"),
            ("He fixed the flat tyre, then he oiled the chain and went for a long ride.", "compound sentence - sequence"),
        ],
        "upper_intermediate": [
            ("The bicycle that my uncle gave me as a birthday gift is still in excellent condition.", "relative clause - that"),
            ("The old bicycle was repaired by the mechanic at the corner shop in less than an hour.", "passive voice"),
            ("Anyone who rides a bicycle regularly tends to develop better balance and coordination over time.", "relative clause + general truth"),
            ("The bicycle, which had been left out in the rain, was covered in rust by the following morning.", "non-defining relative clause"),
            ("She chose the bicycle whose frame was the lightest, knowing it would be easier to carry up the stairs.", "relative clause - whose"),
        ],
        "advanced": [
            ("The resurgence of bicycle commuting in urban areas reflects a broader societal shift toward sustainable and health-conscious transportation.", "complex noun phrase + present simple"),
            ("Having cycled across the entire length of the coastal road, she described the experience as both physically demanding and deeply rewarding.", "participle clause - having done"),
            ("The bicycle, once considered a humble mode of transport, has been reimagined as a symbol of environmental responsibility.", "non-defining relative clause + passive"),
            ("It is not merely the physical exercise that makes cycling valuable, but the quiet sense of freedom it consistently provides.", "cleft sentence + gerund"),
            ("The precision with which a well-maintained bicycle responds to even the slightest adjustment of the handlebars never ceases to impress experienced riders.", "noun clause + present simple"),
        ],
    },
    "car": {
        "beginner": [
            ("The car is blue.", "present - to be + adjective"),
            ("My father drives a car.", "simple present"),
            ("We went to the market by car.", "simple past"),
            ("The car stopped at the red light.", "simple past"),
            ("This car is very fast.", "present - to be + intensifier"),
        ],
        "elementary": [
            ("Can your father's car fit all five of us?", "question with can"),
            ("There is a car parked in front of our house.", "there is"),
            ("Could you please close the car window?", "could - polite request"),
            ("Is the car new or did your family buy it a long time ago?", "yes/no question + past"),
            ("There are three cars waiting at the traffic light.", "there are - plural"),
        ],
        "intermediate": [
            ("If the car runs out of fuel, we will have to push it to the nearest petrol station.", "first conditional"),
            ("This car is more comfortable than the old one we had before.", "comparative adjective"),
            ("The car broke down on the highway, so my uncle called a mechanic immediately.", "compound sentence - result"),
            ("She prefers travelling by car because it is faster and more convenient than the bus.", "comparative + reason clause"),
            ("The car was clean this morning, but now it is covered in mud after the rain.", "compound sentence - contrast"),
        ],
        "upper_intermediate": [
            ("The car that was involved in the minor accident was towed away before the school bus arrived.", "relative clause - that + passive"),
            ("A new electric car has been purchased by the school to transport students to sports events.", "passive voice"),
            ("The car whose engine made a strange noise was sent to the garage for a thorough inspection.", "relative clause - whose"),
            ("Anyone who drives a car in the city must be prepared for heavy traffic during peak hours.", "relative clause + modal"),
            ("The car, which had been parked in the sun all afternoon, was extremely hot when they returned.", "non-defining relative clause"),
        ],
        "advanced": [
            ("The widespread adoption of electric cars is gradually transforming the way urban infrastructure is planned and built.", "gerund subject + passive"),
            ("Having travelled thousands of kilometres across varied terrain, the car showed no signs of mechanical wear, a testament to careful maintenance.", "participle clause + noun phrase appositive"),
            ("The car, engineered to minimise aerodynamic drag, demonstrated a fuel efficiency that surpassed all manufacturer expectations during the trial.", "past participle clause + relative clause"),
            ("It is the seamless integration of safety technology and driver comfort that distinguishes the latest generation of family cars.", "cleft sentence + noun phrase"),
            ("Whether one views the car as a symbol of personal freedom or a contributor to environmental degradation depends largely on cultural perspective.", "whether-clause as subject + depends on"),
        ],
    },
    "motorcycle": {
        "beginner": [
            ("The motorcycle is loud.", "present - to be + adjective"),
            ("He rides a motorcycle to work.", "simple present"),
            ("She wore a helmet on the motorcycle.", "simple past"),
            ("The motorcycle went very fast.", "simple past"),
            ("Our neighbour has a big motorcycle.", "simple present - has"),
        ],
        "elementary": [
            ("Can you hear the motorcycle coming down the street?", "question with can"),
            ("There is a motorcycle parked beside the gate.", "there is"),
            ("Could the rider please slow down near the school?", "could - polite request"),
            ("Is that motorcycle faster than a bicycle?", "comparative question"),
            ("There are several motorcycles parked outside the temple.", "there are - plural"),
        ],
        "intermediate": [
            ("If you ride a motorcycle, you must always wear a helmet for safety.", "first conditional + obligation"),
            ("The motorcycle is noisier than a bicycle but quieter than a truck.", "double comparative"),
            ("He bought a second-hand motorcycle, and he repaired it himself over the weekend.", "compound sentence"),
            ("Riding a motorcycle in the rain is more dangerous than riding on a dry road.", "gerund subject + comparative"),
            ("The motorcycle skidded on the wet road, but the rider managed to keep his balance.", "compound sentence - contrast"),
        ],
        "upper_intermediate": [
            ("The motorcycle that the mechanic repaired last week broke down again on the main road.", "relative clause - that"),
            ("The motorcycle was being ridden at high speed when the tyre suddenly burst.", "past continuous passive + when-clause"),
            ("She chose the motorcycle whose fuel consumption was the lowest, as she commuted long distances daily.", "relative clause - whose + reason"),
            ("The rider who ignored the traffic signal was stopped by a police officer a short distance away.", "relative clause - who + passive"),
            ("The motorcycle, which had won several regional races, was displayed proudly at the community exhibition.", "non-defining relative clause"),
        ],
        "advanced": [
            ("The intricate engineering behind a high-performance motorcycle reflects decades of incremental innovation in materials science and aerodynamics.", "complex noun phrase + reflection of"),
            ("Having ridden through mountainous terrain for two consecutive days, the rider arrived with an unshakeable sense of personal achievement.", "participle clause - having done"),
            ("The motorcycle, stripped of unnecessary weight and fitted with a precision-tuned engine, achieved a top speed that surprised even the designers.", "past participle clauses + relative clause"),
            ("It is the combination of agility and raw mechanical power that makes the motorcycle a uniquely compelling mode of personal transport.", "cleft sentence + gerund"),
            ("The extent to which motorcycle culture has shaped local identity in this region is evident in the annual festival attended by thousands.", "noun clause + passive"),
        ],
    },
    "airplane": {
        "beginner": [
            ("The airplane is up in the sky.", "present - to be + location"),
            ("We flew in an airplane last year.", "simple past"),
            ("The airplane is very big.", "present - to be + adjective"),
            ("I saw an airplane from my window.", "simple past"),
            ("The airplane lands on a runway.", "simple present"),
        ],
        "elementary": [
            ("Can you see the airplane flying above the clouds?", "question with can"),
            ("There is an airplane waiting on the runway.", "there is"),
            ("Could we sit near the window on the airplane?", "could - polite request"),
            ("Is the airplane going to Chennai or Delhi?", "present continuous for future - question"),
            ("There are many airplanes at the international airport.", "there are - plural"),
        ],
        "intermediate": [
            ("If the airplane departs on time, we will arrive before sunset.", "first conditional"),
            ("Travelling by airplane is much faster than travelling by train.", "gerund subject + comparative"),
            ("The airplane was delayed due to heavy fog, so all passengers waited in the terminal.", "compound sentence - result"),
            ("She looked out of the airplane window and saw the city lights far below her.", "compound sentence - sequence"),
            ("An airplane flight is more exciting than a long bus journey, especially for first-time travellers.", "comparative + opinion"),
        ],
        "upper_intermediate": [
            ("The airplane that was scheduled to depart at noon was delayed by nearly three hours.", "relative clause - that"),
            ("All passengers were asked to fasten their seatbelts as the airplane began its descent.", "passive voice + as-clause"),
            ("The airplane, which carried over two hundred passengers, landed safely despite the strong crosswinds.", "non-defining relative clause"),
            ("The pilot whose calm announcement reassured everyone on board received a round of applause after landing.", "relative clause - whose"),
            ("Anyone who has watched an airplane take off at close range cannot help but feel a sense of wonder.", "relative clause + negative auxiliary"),
        ],
        "advanced": [
            ("The development of the modern commercial airplane transformed global connectivity in ways that were scarcely imaginable a century ago.", "relative clause + time adverbial"),
            ("Having flown through severe turbulence for nearly forty minutes, the passengers were visibly shaken but ultimately unharmed upon landing.", "participle clause - having done"),
            ("The airplane, designed with composite materials to reduce structural weight, set a new benchmark for fuel efficiency on long-haul routes.", "past participle clause + relative clause"),
            ("It is the extraordinary precision required to land an airplane in poor visibility that underscores the skill and composure of trained pilots.", "cleft sentence + noun clause"),
            ("The global grounding of a particular aircraft model following safety concerns illustrated how swiftly regulatory bodies can act when public welfare is at stake.", "noun clause + adverbial clause"),
        ],
    },
    "bus": {
        "beginner": [
            ("The bus is yellow.", "present - to be + adjective"),
            ("I take the bus to school.", "simple present"),
            ("The bus stopped at the corner.", "simple past"),
            ("We missed the morning bus.", "simple past"),
            ("The bus has many seats.", "simple present - has"),
        ],
        "elementary": [
            ("Can we catch the next bus to the market?", "question with can"),
            ("There is a bus stop near my house.", "there is"),
            ("Could you tell me when the next bus arrives?", "could - polite request + indirect question"),
            ("Is the school bus coming on time today?", "present continuous question"),
            ("There are people waiting at the bus stop in the rain.", "there are - plural"),
        ],
        "intermediate": [
            ("If we take the early bus, we will have more time to explore the town.", "first conditional"),
            ("The bus is slower than the train, but it is much cheaper.", "comparative + compound"),
            ("She missed the bus this morning, so she had to walk all the way to school.", "compound sentence - result"),
            ("Travelling by bus gives you a chance to look at the scenery outside the window.", "gerund subject + noun phrase"),
            ("The bus was crowded in the morning, but most passengers got off at the city centre.", "compound sentence - contrast"),
        ],
        "upper_intermediate": [
            ("The bus that runs between the school and the sports complex was taken out of service for repairs.", "relative clause - that + passive"),
            ("All new buses purchased by the city have been fitted with air conditioning and security cameras.", "passive voice + relative clause"),
            ("The bus driver whose route covered the longest distance was given a special recognition award.", "relative clause - whose"),
            ("Anyone who has travelled by bus during peak hour knows how important it is to arrive at the stop early.", "relative clause + noun clause"),
            ("The old bus, which had served the community for over fifteen years, was replaced by a modern electric vehicle.", "non-defining relative clause"),
        ],
        "advanced": [
            ("The introduction of electric buses into the city's public transport network represents a meaningful step toward reducing carbon emissions in densely populated areas.", "gerund subject + noun phrase"),
            ("Having waited at the bus stop for nearly an hour in the heat, the students were relieved when the vehicle finally turned the corner.", "participle clause - having done"),
            ("The bus system, long criticised for its unreliability, has undergone significant restructuring following a comprehensive review by transport planners.", "non-defining relative clause + passive"),
            ("It is the accessibility and affordability of bus travel that makes it the preferred mode of transport for the majority of school-going children.", "cleft sentence + relative clause"),
            ("The degree to which a reliable bus network contributes to social equity is a subject that deserves far greater attention in urban policy discussions.", "noun clause + relative clause"),
        ],
    },
    "train": {
        "beginner": [
            ("The train is long and fast.", "present - to be + adjectives"),
            ("We travelled by train last week.", "simple past"),
            ("The train stops at every station.", "simple present"),
            ("I heard the train horn at night.", "simple past"),
            ("The train has many compartments.", "simple present - has"),
        ],
        "elementary": [
            ("Can the train reach Chennai in four hours?", "question with can"),
            ("There is a train arriving on platform three.", "there is + present participle"),
            ("Could you check the train schedule for tomorrow?", "could - polite request"),
            ("Is the express train faster than the passenger train?", "comparative question"),
            ("There are passengers rushing to catch the last train.", "there are + present participle"),
        ],
        "intermediate": [
            ("If the train arrives late, we will miss our connection at the junction.", "first conditional"),
            ("Travelling by train is more scenic than flying because you can see the countryside.", "comparative + reason clause"),
            ("The train was full when we boarded, so we had to stand in the corridor.", "compound sentence - result"),
            ("She read her book quietly while the train moved through the green fields.", "while-clause - simultaneous action"),
            ("The express train is faster than the local one, but both trains go to the same destination.", "comparative + compound"),
        ],
        "upper_intermediate": [
            ("The train that derailed near the mountain tunnel has now been restored to normal service.", "relative clause - that + passive"),
            ("Passengers travelling without valid tickets are asked to pay the full fare plus a penalty charge.", "passive voice + reduced relative clause"),
            ("The train whose route passes through the valley offers some of the most breathtaking views in the region.", "relative clause - whose"),
            ("The historic steam train, which was built in the early twentieth century, still attracts large crowds at weekend exhibitions.", "non-defining relative clause"),
            ("Anyone who takes the overnight train should bring a blanket, as the air conditioning can be quite strong.", "relative clause + reason"),
        ],
        "advanced": [
            ("The expansion of high-speed rail networks across the country has fundamentally altered commuting patterns and reshaped the economic geography of several regions.", "noun phrase + present perfect + compound"),
            ("Having spent sixteen uninterrupted hours on the train, the travellers stepped onto the platform with a mixture of fatigue and exhilaration.", "participle clause - having done"),
            ("The vintage train, meticulously restored by a team of dedicated engineers, serves as a moving museum of early twentieth-century industrial design.", "past participle clause + relative clause"),
            ("It is the rhythmic motion of a long train journey, combined with the ever-changing landscape outside the window, that many travellers find unexpectedly therapeutic.", "cleft sentence + past participle phrase"),
            ("The manner in which train networks redistribute populations and stimulate economic activity in previously isolated communities continues to be a compelling argument for sustained infrastructure investment.", "noun clause + gerund"),
        ],
    },
    "truck": {
        "beginner": [
            ("The truck is very big.", "present - to be + adjective"),
            ("A truck carried the furniture.", "simple past"),
            ("The truck parked near the shop.", "simple past"),
            ("That truck makes a loud noise.", "simple present"),
            ("The truck has eight wheels.", "simple present - has"),
        ],
        "elementary": [
            ("Can that truck carry all the boxes at once?", "question with can"),
            ("There is a large truck blocking the road.", "there is + adjective"),
            ("Could the truck driver move the vehicle forward?", "could - polite request"),
            ("Is the truck carrying vegetables or building materials?", "present continuous question - alternatives"),
            ("There are two trucks unloading goods at the warehouse.", "there are + present participle"),
        ],
        "intermediate": [
            ("If the truck breaks down on the highway, the delivery will be delayed by many hours.", "first conditional"),
            ("The truck is heavier than the car, so it uses more fuel on long journeys.", "comparative + reason"),
            ("The driver stopped the truck carefully and climbed out to check the front tyre.", "compound sentence - sequence"),
            ("Driving a large truck in a narrow street is much harder than driving a small car.", "gerund subject + comparative"),
            ("The truck arrived late, but the shopkeeper was still happy to receive the goods.", "compound sentence - contrast"),
        ],
        "upper_intermediate": [
            ("The truck that was carrying fresh vegetables overturned on the wet road early this morning.", "relative clause - that"),
            ("All goods transported by truck are inspected at the checkpoint before entering the city.", "passive voice + before-clause"),
            ("The truck driver whose vehicle had the most fuel-efficient engine was praised by the company.", "relative clause - whose"),
            ("The old truck, which had crossed the country dozens of times, finally needed a complete engine overhaul.", "non-defining relative clause"),
            ("Anyone who has watched a truck navigate a narrow mountain pass will understand the extraordinary skill required.", "relative clause + noun clause"),
        ],
        "advanced": [
            ("The logistics industry's growing reliance on long-haul trucks has intensified debates about road maintenance costs and the environmental impact of diesel emissions.", "noun phrase + present perfect"),
            ("Having driven through the night to meet the warehouse deadline, the truck driver pulled into the depot as the sun rose over the hills.", "participle clause - having done"),
            ("The truck, retrofitted with a refrigeration unit to transport perishable goods, represented a significant investment for the small family business.", "past participle clause + relative clause"),
            ("It is the sheer versatility of the modern truck, capable of transporting everything from livestock to electronic components, that makes it indispensable to supply chains.", "cleft sentence + reduced relative clause"),
            ("The degree to which heavy truck traffic accelerates road deterioration in semi-urban areas is a factor often overlooked in regional infrastructure budgets.", "noun clause + passive"),
        ],
    },
    "boat": {
        "beginner": [
            ("The boat floats on the water.", "simple present"),
            ("We saw a boat near the shore.", "simple past"),
            ("The boat is small and wooden.", "present - to be + adjectives"),
            ("The fisherman sailed his boat early.", "simple past"),
            ("That boat has a blue sail.", "simple present - has"),
        ],
        "elementary": [
            ("Can this boat hold ten people safely?", "question with can + adverb"),
            ("There is a boat tied to the dock.", "there is"),
            ("Could we go for a ride in that boat?", "could - polite request"),
            ("Is the boat moving towards the island?", "present continuous question"),
            ("There are several fishing boats out on the sea today.", "there are - plural"),
        ],
        "intermediate": [
            ("If the weather stays calm, the boat will reach the island before noon.", "first conditional"),
            ("The boat moved more slowly than usual because the tide was coming in strongly.", "comparative + reason clause"),
            ("He rowed the boat gently across the lake while his sister watched the birds.", "while-clause - simultaneous action"),
            ("Sailing a boat requires balance and concentration, especially when the wind is strong.", "gerund subject + when-clause"),
            ("The boat was old, but it was still strong enough to carry the family across the river.", "compound sentence - contrast"),
        ],
        "upper_intermediate": [
            ("The boat that was used in the school expedition has been donated to the local sailing club.", "relative clause - that + passive"),
            ("A small rescue boat was launched by the coastguard within minutes of receiving the distress signal.", "passive voice + time expression"),
            ("The fisherman whose boat had the largest catch of the day shared his fish generously with the whole village.", "relative clause - whose"),
            ("The old wooden boat, which had been in the family for three generations, was carefully restored and put on display.", "non-defining relative clause + passive"),
            ("Anyone who has crossed a wide river by boat on a misty morning will recall the stillness and beauty of that experience.", "relative clause + noun clause"),
        ],
        "advanced": [
            ("The transformation of traditional fishing boats into tourist vessels reflects the complex economic pressures facing coastal communities in the modern era.", "noun phrase + relative clause"),
            ("Having navigated the estuary using only a hand-drawn map and the position of the stars, the sailors arrived at the village to an astonished reception.", "participle clause - having done"),
            ("The boat, constructed entirely from locally sourced timber and assembled without a single metal fastener, stood as a remarkable example of indigenous craftsmanship.", "past participle clause + relative clause"),
            ("It is the solitary silence of drifting in a small boat far from shore, with nothing but water and sky, that offers a rare form of clarity.", "cleft sentence + reduced relative clause"),
            ("The speed with which a well-designed boat adjusts to shifting wind conditions reveals the sophistication embedded in what might superficially appear to be a simple vessel.", "noun clause + relative clause"),
        ],
    },
    "traffic light": {
        "beginner": [
            ("The traffic light turned red.", "simple past"),
            ("Stop when the light is red.", "imperative + when-clause"),
            ("The green light means go.", "simple present"),
            ("We waited at the traffic light.", "simple past"),
            ("The traffic light has three colours.", "simple present - has"),
        ],
        "elementary": [
            ("Can you see the traffic light at the end of the road?", "question with can"),
            ("There is a traffic light at every busy junction.", "there is"),
            ("Could everyone please wait until the traffic light turns green?", "could - polite request"),
            ("Is the traffic light working properly today?", "yes/no question - adverb"),
            ("There are traffic lights on both sides of the crossing.", "there are - plural"),
        ],
        "intermediate": [
            ("If the traffic light is broken, drivers must treat the junction as a stop sign.", "first conditional + modal"),
            ("The traffic light changed to green, so all the vehicles moved forward at once.", "compound sentence - result"),
            ("Waiting for a traffic light to change is sometimes frustrating, but it keeps everyone safe.", "gerund subject + compound"),
            ("The amber light warns you to slow down because the red light will appear very soon.", "simple present + reason clause"),
            ("Traffic lights at this crossing are timed differently in the morning compared to the evening.", "passive + comparative"),
        ],
        "upper_intermediate": [
            ("The traffic light that malfunctioned during the evening rush caused a significant build-up of vehicles on four roads.", "relative clause - that"),
            ("New smart traffic lights have been installed at the busiest intersections to reduce unnecessary waiting times.", "passive voice + infinitive of purpose"),
            ("The pedestrian crossing whose traffic light had the longest green phase was located near the primary school.", "relative clause - whose"),
            ("The traffic light, which had been flashing amber for two days, was finally repaired by the municipal authorities.", "non-defining relative clause + passive"),
            ("Anyone who has witnessed the chaos caused by a failed traffic light during peak hours will appreciate the importance of regular maintenance.", "relative clause + noun clause"),
        ],
        "advanced": [
            ("The integration of adaptive traffic light systems into city grids has demonstrated measurable reductions in both average commute times and vehicle emissions.", "noun phrase + present perfect"),
            ("Having studied traffic flow patterns over several months, the engineers reconfigured the traffic light sequencing to reduce the chronic congestion at the main roundabout.", "participle clause - having done"),
            ("The traffic light, upgraded with sensors capable of detecting pedestrian presence, has significantly improved safety for visually impaired residents in the neighbourhood.", "past participle clause + present perfect"),
            ("It is the seemingly simple rhythm of a traffic light — stop, wait, go — that underpins the orderly movement of thousands of vehicles through a city each day.", "cleft sentence + dash appositive"),
            ("The extent to which poorly timed traffic lights contribute to fuel waste and driver frustration is an area where incremental algorithmic improvements can yield substantial civic benefits.", "noun clause + relative clause"),
        ],
    },
    "fire hydrant": {
        "beginner": [
            ("The fire hydrant is red.", "present - to be + adjective"),
            ("Firefighters use the fire hydrant.", "simple present"),
            ("The fire hydrant stands on the pavement.", "simple present"),
            ("We saw a fire hydrant near the school.", "simple past"),
            ("The fire hydrant gives water to the hose.", "simple present"),
        ],
        "elementary": [
            ("Can a fire hydrant supply enough water to stop a large fire?", "question with can"),
            ("There is a fire hydrant on every street in the town.", "there is"),
            ("Could you make sure nobody parks in front of the fire hydrant?", "could - polite request"),
            ("Is the fire hydrant connected to the underground water supply?", "yes/no question"),
            ("There are fire hydrants painted bright red so drivers can see them clearly.", "there are + result clause"),
        ],
        "intermediate": [
            ("If a fire breaks out, firefighters can connect their hose to the nearest fire hydrant quickly.", "first conditional"),
            ("The fire hydrant on our street is older than the ones on the next road.", "comparative adjective"),
            ("A car was blocking the fire hydrant, so the fire engine could not connect the hose in time.", "compound sentence - result"),
            ("Keeping a clear space around a fire hydrant is important because emergencies can happen without warning.", "gerund subject + reason clause"),
            ("The fire hydrant was painted and inspected last month, but the pressure test is still pending.", "compound sentence - contrast"),
        ],
        "upper_intermediate": [
            ("The fire hydrant that was damaged during the road construction was replaced within twenty-four hours.", "relative clause - that + passive"),
            ("All fire hydrants in the district are tested annually by the water authority to ensure adequate pressure.", "passive voice + infinitive of purpose"),
            ("The fire hydrant whose valve had been painted over was identified as a safety hazard during the inspection.", "relative clause - whose + passive"),
            ("The old fire hydrant, which had been installed when the road was first built, was found to be severely corroded.", "non-defining relative clause + passive"),
            ("Anyone who parks in front of a fire hydrant risks delaying an emergency response and may face a significant fine.", "relative clause + gerund"),
        ],
        "advanced": [
            ("The strategic placement of fire hydrants throughout a neighbourhood is determined by calculations involving water pressure, pipe diameter, and anticipated fire risk.", "passive voice + gerund"),
            ("Having located the nearest fire hydrant using a digital map, the crew connected the hose and had water flowing within ninety seconds of arriving on scene.", "participle clause - having done"),
            ("The fire hydrant, though often overlooked as an unremarkable piece of street furniture, represents a critical node in the urban infrastructure of public safety.", "non-defining relative clause + noun phrase"),
            ("It is the unglamorous reliability of systems like the fire hydrant, maintained silently beneath public awareness, that forms the true foundation of community resilience.", "cleft sentence + past participle phrase"),
            ("The tension between urban densification and the spatial requirements of emergency infrastructure, including the unobstructed accessibility of fire hydrants, poses ongoing challenges for city planners.", "noun phrase + gerund + relative clause"),
        ],
    },
    "stop sign": {
        "beginner": [
            ("The stop sign is red.", "present - to be + adjective"),
            ("All cars stop at the sign.", "simple present"),
            ("I saw a stop sign at the corner.", "simple past"),
            ("The stop sign is round and bright.", "present - to be + adjectives"),
            ("Drivers must stop at a stop sign.", "modal - must"),
        ],
        "elementary": [
            ("Can you see the stop sign at the end of the lane?", "question with can"),
            ("There is a stop sign at the entrance to the school.", "there is"),
            ("Could the driver not see the stop sign around the corner?", "could - negative past ability"),
            ("Is there a stop sign at every junction near the market?", "there is - question"),
            ("There are stop signs placed on all four sides of the junction.", "there are - plural"),
        ],
        "intermediate": [
            ("If a driver ignores a stop sign, they put both themselves and others in danger.", "first conditional"),
            ("The stop sign at the corner is more visible than the old one, which was hidden by a tree.", "comparative + relative clause"),
            ("A student pointed out that the stop sign had fallen over, so the teacher called the local council.", "reported speech + compound sentence"),
            ("Obeying a stop sign is one of the most basic and important rules of road safety.", "gerund subject + superlative"),
            ("The stop sign was new and bright, but many cyclists still failed to notice it in the evening.", "compound sentence - contrast"),
        ],
        "upper_intermediate": [
            ("The stop sign that was knocked down by the lorry has now been replaced with a sturdier post.", "relative clause - that + passive"),
            ("Temporary stop signs are erected by the road authority whenever traffic lights are being repaired.", "passive voice + whenever-clause"),
            ("The driver whose vehicle ran past the stop sign was pulled over by a traffic officer immediately.", "relative clause - whose + passive"),
            ("The old stop sign, which had been partially obscured by an overgrown hedge, was reported as a safety concern by residents.", "non-defining relative clause + passive"),
            ("Anyone who drives through a stop sign without stopping is putting pedestrians and other road users at serious risk.", "relative clause + gerund"),
        ],
        "advanced": [
            ("The seemingly simple act of stopping at a sign encapsulates the broader social contract that makes shared road use both possible and orderly.", "gerund subject + relative clause"),
            ("Having failed to yield at the stop sign at the intersection, the driver was issued a fine and required to attend a road safety seminar.", "participle clause - having done + passive"),
            ("The stop sign, universally recognised across language boundaries due to its distinctive octagonal shape and vivid colouring, is a model of effective visual communication design.", "non-defining relative clause + noun phrase"),
            ("It is the consistent, unthinking compliance with stop signs by the vast majority of drivers that enables the smooth functioning of traffic systems in residential areas.", "cleft sentence + noun phrase"),
            ("The question of whether stop signs are sufficient for managing traffic at increasingly busy intersections, or whether signal-controlled systems are required, is one that transport engineers revisit periodically.", "whether-clause + relative clause"),
        ],
    },
    "parking meter": {
        "beginner": [
            ("The parking meter is on the pavement.", "present - to be + location"),
            ("We paid the parking meter.", "simple past"),
            ("The parking meter ran out of time.", "simple past"),
            ("A parking meter tells you the time left.", "simple present"),
            ("The parking meter is broken today.", "present - to be + adjective"),
        ],
        "elementary": [
            ("Can you see how much time is left on the parking meter?", "question with can + embedded question"),
            ("There is a parking meter outside every shop on this road.", "there is"),
            ("Could you put some coins in the parking meter before we go in?", "could - polite request"),
            ("Is the parking meter still showing twenty minutes?", "present continuous question"),
            ("There are parking meters on both sides of the main street.", "there are - plural"),
        ],
        "intermediate": [
            ("If the parking meter expires before we return, we might get a fine.", "first conditional + might"),
            ("Paying a parking meter is easier with a phone app than with coins.", "gerund subject + comparative"),
            ("The parking meter accepted only coins, so my mother had to walk to a shop to get change.", "compound sentence - result"),
            ("The parking meter outside the hospital is often occupied all day because patients need long visits.", "simple present + reason clause"),
            ("She checked the parking meter twice, but she was still worried it would run out too soon.", "compound sentence - contrast"),
        ],
        "upper_intermediate": [
            ("The parking meter that was installed last year already needs to be replaced due to frequent malfunctions.", "relative clause - that + passive"),
            ("New digital parking meters have been introduced in the city centre to allow payment by mobile phone.", "passive voice + infinitive of purpose"),
            ("The driver whose parking meter had expired by only five minutes still received a penalty notice.", "relative clause - whose"),
            ("The old parking meter, which accepted only ten and five rupee coins, caused constant inconvenience for visitors.", "non-defining relative clause + past"),
            ("Anyone who forgets to check the parking meter regularly risks returning to find an unwanted fine on their windscreen.", "relative clause + gerund"),
        ],
        "advanced": [
            ("The gradual replacement of coin-operated parking meters with app-based systems reflects a broader municipal effort to streamline revenue collection and reduce mechanical maintenance costs.", "noun phrase + relative clause"),
            ("Having noticed that the parking meter was about to expire, she rushed out of the meeting to add more time before the enforcement officer arrived.", "participle clause - having noticed"),
            ("The parking meter, once a universal feature of high streets worldwide, is being phased out in many cities in favour of automated number-plate recognition systems.", "non-defining relative clause + passive"),
            ("It is the metered allocation of limited kerb space, enforced through parking meters, that enables towns to balance the competing demands of shoppers, residents, and delivery vehicles.", "cleft sentence + past participle phrase"),
            ("The economics of parking meter management, including the trade-off between enforcement costs and revenue generated, remain a surprisingly complex area of municipal finance.", "noun phrase + gerund + relative clause"),
        ],
    },
    "bench": {
        "beginner": [
            ("The bench is in the park.", "present - to be + location"),
            ("We sat on the bench together.", "simple past"),
            ("The bench is made of wood.", "present - to be + passive"),
            ("An old man rested on the bench.", "simple past"),
            ("The bench has space for three people.", "simple present - has"),
        ],
        "elementary": [
            ("Can we sit on that bench under the tree?", "question with can"),
            ("There is a bench near the fountain in the garden.", "there is"),
            ("Could you move along the bench so we all have space?", "could - polite request"),
            ("Is the bench still wet after the rain this morning?", "yes/no question + time expression"),
            ("There are benches along the entire length of the riverside path.", "there are - plural"),
        ],
        "intermediate": [
            ("If the bench is wet, we can spread a newspaper to sit down comfortably.", "first conditional"),
            ("The bench in the new park is more comfortable than the old stone one near the temple.", "comparative adjective"),
            ("She sat on the bench and opened her book while waiting for her friend to arrive.", "compound sentence - sequence + while-clause"),
            ("Sitting on a park bench on a quiet afternoon is one of the most relaxing things I know.", "gerund subject + superlative"),
            ("The bench was painted green last week, but some children have already scratched the surface.", "compound sentence - contrast"),
        ],
        "upper_intermediate": [
            ("The bench that was donated to the school by a former student has a small plaque engraved on its back.", "relative clause - that"),
            ("A new bench has been placed at the bus stop so that elderly passengers can wait comfortably.", "passive voice + so-that clause"),
            ("The elderly woman whose favourite bench had been removed to make way for a new path was quite upset.", "relative clause - whose"),
            ("The old bench, which had stood at the entrance of the park for decades, was finally replaced with a stronger metal one.", "non-defining relative clause"),
            ("Anyone who has sat quietly on a bench in a busy park will notice how much you can learn simply by observing.", "relative clause + how-clause"),
        ],
        "advanced": [
            ("The unassuming park bench, often overlooked as a piece of civic furniture, plays a surprisingly important role in encouraging spontaneous social interaction among strangers.", "non-defining relative clause + gerund"),
            ("Having spent the afternoon on a bench by the river, watching the boats pass and the light change, she felt a profound sense of calm return to her.", "participle clause - having done + gerund phrase"),
            ("The memorial bench, inscribed with a verse chosen by the family and positioned to face the sea, served as a quiet place of reflection for the entire community.", "past participle clause + infinitive of purpose"),
            ("It is on the ordinary park bench that some of life's most meaningful conversations take place, unscheduled and unhurried, between people who simply happen to sit together.", "cleft sentence + relative clause"),
            ("The provision of adequate public seating, including well-placed benches in parks and transport hubs, is an equity issue that disproportionately affects the elderly and those with mobility difficulties.", "noun phrase + relative clause + relative clause"),
        ],
    },
    "bird": {
        "beginner": [
            ("The bird is on the branch.", "present - to be + location"),
            ("A bird sang in the morning.", "simple past"),
            ("The bird has colourful wings.", "simple present - has"),
            ("We saw a bird near the window.", "simple past"),
            ("Birds fly south in winter.", "simple present - general truth"),
        ],
        "elementary": [
            ("Can you hear the bird singing outside?", "question with can + present participle"),
            ("There is a bird building a nest in our garden.", "there is + present participle"),
            ("Could that small bird be a sparrow or a robin?", "could - possibility"),
            ("Is that bird sitting on the same branch every morning?", "present continuous question"),
            ("There are many birds gathering on the electric wire at sunset.", "there are + present participle"),
        ],
        "intermediate": [
            ("If we sit quietly, the bird will come closer and we can take a good photograph.", "first conditional"),
            ("The bird in our garden sings more beautifully than any bird I have heard before.", "comparative adverb + present perfect"),
            ("A bird landed on the windowsill, looked inside for a moment, then flew away quickly.", "compound sentence - sequence"),
            ("Watching birds early in the morning is a wonderful way to start a peaceful day.", "gerund subject + noun phrase"),
            ("The bird looked small and fragile, but it managed to fly through the strong wind without difficulty.", "compound sentence - contrast"),
        ],
        "upper_intermediate": [
            ("The bird that built a nest in our roof has returned with its young ones every spring for four years.", "relative clause - that + present perfect"),
            ("Several rare birds have been spotted in the wetland area that was protected by the local conservation group.", "passive - present perfect + relative clause"),
            ("The migratory bird whose journey covered thousands of kilometres was tracked using a tiny solar-powered device.", "relative clause - whose + passive"),
            ("The colourful bird, which is native to the forests of the Western Ghats, is increasingly threatened by habitat loss.", "non-defining relative clause + passive"),
            ("Anyone who watches birds regularly will develop a deep appreciation for the diversity and complexity of the natural world.", "relative clause + noun phrase"),
        ],
        "advanced": [
            ("The extraordinary navigational abilities of migratory birds, which can travel thousands of kilometres with remarkable precision, continue to inspire researchers in the fields of biology and robotics.", "non-defining relative clause + present simple"),
            ("Having observed the bird's elaborate courtship display for nearly an hour, the wildlife photographer captured the precise moment of takeoff in a single stunning frame.", "participle clause - having done"),
            ("The bird, long revered in Tamil culture as a symbol of love and longing, appears repeatedly in classical Sangam poetry as a messenger between separated lovers.", "non-defining relative clause + noun phrase"),
            ("It is the astonishing variety of birdsong within even a small patch of forest that reveals the extraordinary density of life hidden within seemingly ordinary green spaces.", "cleft sentence + noun clause"),
            ("The decline in urban bird populations, attributed largely to light pollution, pesticide use, and the loss of nesting sites in modernised buildings, signals a broader deterioration in environmental health.", "noun phrase + passive + relative clause"),
        ],
    },
    "cat": {
        "beginner": [
            ("The cat is sleeping on the mat.", "present continuous"),
            ("My cat drinks milk every morning.", "simple present"),
            ("The cat jumped over the wall.", "simple past"),
            ("Our cat has soft white fur.", "simple present - has"),
            ("The cat looked at me quietly.", "simple past"),
        ],
        "elementary": [
            ("Can your cat catch a ball when you throw it?", "question with can"),
            ("There is a cat sitting on the roof next door.", "there is + present participle"),
            ("Could the cat have knocked the glass off the table?", "could + present perfect - possibility"),
            ("Is your cat friendlier than your neighbour's cat?", "comparative question"),
            ("There are three cats sleeping in a row on the warm pavement.", "there are + present participle"),
        ],
        "intermediate": [
            ("If you give the cat too much food, it will become overweight and lazy.", "first conditional"),
            ("Our cat is more playful than our dog, which surprises most people who visit us.", "comparative + non-defining relative clause"),
            ("The cat sat on the windowsill and watched the birds outside with great concentration.", "compound sentence - sequence"),
            ("Keeping a cat as a pet teaches children to be gentle, patient, and responsible.", "gerund subject + adjectives"),
            ("The cat looked hungry, so my sister gave it a small piece of fish from the kitchen.", "compound sentence - result"),
        ],
        "upper_intermediate": [
            ("The cat that my grandmother brought home as a kitten has now grown into a large and dignified animal.", "relative clause - that + present perfect"),
            ("A stray cat was found injured near the school gate and was immediately taken to the veterinary clinic.", "passive voice + compound"),
            ("The cat whose owner had recently moved away began visiting several neighbouring houses in search of affection.", "relative clause - whose + gerund"),
            ("The sleek black cat, which appeared on our doorstep during a heavy rainstorm, refused to leave and eventually became part of the family.", "non-defining relative clause"),
            ("Anyone who has spent time with a cat will know that they communicate far more through posture and eye contact than through sound.", "relative clause + noun clause"),
        ],
        "advanced": [
            ("The cat's remarkable capacity for selective attention, choosing to respond only when it suits them, has been interpreted by researchers as a sign of sophisticated social cognition.", "noun phrase + gerund + passive"),
            ("Having curled itself into an impossibly small shape on the warmest corner of the sofa, the cat appeared entirely indifferent to the commotion around it.", "participle clause - having done"),
            ("The cat, worshipped in ancient Egypt as a sacred animal and valued in medieval Europe for its rodent-controlling abilities, occupies a uniquely complex position in human cultural history.", "non-defining relative clause + passive + noun phrase"),
            ("It is the uncanny ability of a cat to appear both entirely at home and perpetually on the verge of departure that gives the animal its enduring air of mystery.", "cleft sentence + infinitive phrase"),
            ("The nuanced relationship between domestic cats and their human companions, characterised by a delicate balance of dependence and independence, continues to fascinate ethologists and ordinary pet owners alike.", "noun phrase + past participle clause + present simple"),
        ],
    },
    "dog": {
        "beginner": [
            ("The dog barked at the stranger.", "simple past"),
            ("My dog is brown and friendly.", "present - to be + adjectives"),
            ("The dog runs in the park every day.", "simple present"),
            ("She gave the dog some water.", "simple past"),
            ("The dog has a long fluffy tail.", "simple present - has"),
        ],
        "elementary": [
            ("Can your dog learn new tricks quickly?", "question with can"),
            ("There is a dog waiting at the gate for its owner.", "there is + present participle"),
            ("Could you please keep the dog away from the little children?", "could - polite request"),
            ("Is your dog more obedient than it was last year?", "comparative question + time reference"),
            ("There are stray dogs sheltering under the school building during the rain.", "there are + present participle"),
        ],
        "intermediate": [
            ("If you take your dog for a walk every day, both you and the dog will stay healthier.", "first conditional"),
            ("My dog is more energetic in the morning than in the evening, which is the opposite of me.", "comparative + non-defining relative clause"),
            ("The dog followed the child all the way home, and the child named him Lucky on the spot.", "compound sentence - sequence"),
            ("Training a dog to follow basic commands takes patience, consistency, and lots of encouragement.", "gerund subject + noun phrase"),
            ("The dog was nervous at first, but it quickly relaxed once it recognised the familiar voices.", "compound sentence - contrast + once-clause"),
        ],
        "upper_intermediate": [
            ("The dog that was rescued from the flooded street has fully recovered and found a loving new home.", "relative clause - that + present perfect"),
            ("A guide dog is trained for months before it is placed with a visually impaired person.", "passive voice + before-clause"),
            ("The dog whose collar had fallen off was identified by its microchip at the animal welfare centre.", "relative clause - whose + passive"),
            ("The old dog, which had been the family's loyal companion for twelve years, was given a quiet and dignified farewell.", "non-defining relative clause + passive"),
            ("Anyone who has raised a dog from a puppy understands the profound bond that can develop between an animal and its family.", "relative clause + noun clause"),
        ],
        "advanced": [
            ("The co-evolutionary relationship between dogs and humans, spanning at least fifteen thousand years, has produced a species uniquely attuned to reading human emotional and gestural cues.", "noun phrase + present perfect + relative clause"),
            ("Having been trained for months in scent detection, the dog located the source of the gas leak within seconds of entering the building.", "participle clause - having been done + passive"),
            ("The dog, regarded across cultures as a symbol of loyalty and unconditional companionship, holds a place in human affection that few other animals can claim.", "non-defining relative clause + relative clause"),
            ("It is the dog's extraordinary capacity to sense shifts in human mood — responding with comfort before the person has fully acknowledged their own distress — that makes it such a valued therapeutic companion.", "cleft sentence + gerund + dash clause"),
            ("The ethical questions surrounding selective breeding in dogs, particularly when it produces animals prone to chronic health conditions, have gained considerable traction in veterinary and public discourse.", "noun phrase + adverb clause + present perfect"),
        ],
    },
    "horse": {
        "beginner": [
            ("The horse is tall and strong.", "present - to be + adjectives"),
            ("The horse ran across the field.", "simple past"),
            ("We saw a horse at the fair.", "simple past"),
            ("A horse eats grass and hay.", "simple present"),
            ("The horse has a long black mane.", "simple present - has"),
        ],
        "elementary": [
            ("Can a horse gallop faster than a bicycle?", "question with can + comparative"),
            ("There is a horse standing near the old well.", "there is + present participle"),
            ("Could we go closer to look at the horse without startling it?", "could - polite request"),
            ("Is the horse used for farming or for riding in your village?", "passive + question"),
            ("There are horses grazing peacefully in the field beyond the fence.", "there are + present participle"),
        ],
        "intermediate": [
            ("If you approach a horse slowly and calmly, it is less likely to get frightened.", "first conditional + comparative"),
            ("The horse is stronger than most farm animals, which is why it has been used for heavy work for centuries.", "comparative + non-defining relative clause"),
            ("The rider gently stroked the horse's neck, then climbed into the saddle and rode toward the hills.", "compound sentence - sequence"),
            ("Learning to ride a horse requires courage, balance, and a good understanding of the animal's behaviour.", "gerund subject + noun phrase"),
            ("The horse looked nervous during the thunder, but the stable keeper spoke to it quietly until it calmed down.", "compound sentence - contrast + until-clause"),
        ],
        "upper_intermediate": [
            ("The horse that won the regional championship was bred on a small farm by a retired schoolteacher.", "relative clause - that + passive"),
            ("Horses have been used by humans for transportation, agriculture, and sport for thousands of years.", "passive - present perfect + list"),
            ("The horse whose injured leg had been carefully treated by the veterinarian was able to run freely within a month.", "relative clause - whose + passive"),
            ("The magnificent horse, which had carried its rider through some of the most challenging terrain in the country, was retired with great ceremony.", "non-defining relative clause + passive"),
            ("Anyone who has sat on the back of a horse and felt it break into a gallop will understand the exhilaration the experience produces.", "relative clause + noun clause"),
        ],
        "advanced": [
            ("The horse's role in shaping human civilisation — from ancient warfare to the agricultural revolution to the development of modern sport — is difficult to overstate.", "noun phrase + dash appositive + infinitive"),
            ("Having been ridden across some of the most inhospitable terrain on earth throughout recorded history, the horse occupies a position of unparalleled significance in the human story.", "participle clause - having been done + noun phrase"),
            ("The horse, celebrated in Tamil literature as a symbol of royal dignity and warrior's pride, appears prominently in ancient Sangam poems as a companion in battle and in glory.", "non-defining relative clause + noun phrase"),
            ("It is the combination of power, sensitivity, and responsiveness that makes the relationship between an experienced rider and a well-trained horse one of the most remarkable interspecies partnerships in existence.", "cleft sentence + relative clause"),
            ("The growing concern about the welfare of horses in competitive racing, including the use of performance-enhancing substances and the physical toll of intensive training, has prompted calls for stronger regulatory oversight.", "noun phrase + gerund + present perfect"),
        ],
    },
    "sheep": {
        "beginner": [
            ("The sheep is eating grass.", "present continuous"),
            ("We saw many sheep on the hill.", "simple past"),
            ("The sheep has thick white wool.", "simple present - has"),
            ("The farmer counts his sheep at night.", "simple present"),
            ("A sheep makes a soft baaing sound.", "simple present"),
        ],
        "elementary": [
            ("Can a sheep recognise its own reflection in water?", "question with can"),
            ("There is a sheep standing near the broken fence.", "there is + present participle"),
            ("Could we feed the sheep some leaves from our hands?", "could - polite request"),
            ("Is the sheep's wool used to make warm clothing?", "passive question"),
            ("There are sheep wandering freely on the hillside in the early morning.", "there are + present participle"),
        ],
        "intermediate": [
            ("If you do not repair the fence, the sheep will escape into the neighbouring field.", "first conditional"),
            ("Wool from sheep is warmer than cotton but less durable than synthetic fibres.", "comparative + compound comparative"),
            ("The shepherd guided the sheep down the hill, and they followed each other in a quiet, orderly line.", "compound sentence - sequence"),
            ("Shearing sheep in summer helps them stay cool and provides wool for weaving warm blankets.", "gerund subject + compound"),
            ("The sheep seemed frightened by the noise at first, but they settled down once the sound faded away.", "compound sentence - contrast + once-clause"),
        ],
        "upper_intermediate": [
            ("The sheep that strayed from the flock was found the next morning in a field three kilometres away.", "relative clause - that + passive"),
            ("Thousands of sheep are herded across vast distances every year as part of the seasonal migration of pastoralists.", "passive - present simple + noun phrase"),
            ("The shepherd whose entire flock had been infected with the disease received support from the government veterinary service.", "relative clause - whose + passive"),
            ("The sheep, which had been separated from the herd during the sudden flood, was eventually reunited with the others.", "non-defining relative clause + passive"),
            ("Anyone who has watched a well-trained sheepdog work will marvel at the precision and intelligence involved in herding a flock.", "relative clause + noun clause"),
        ],
        "advanced": [
            ("The domestication of sheep, which occurred approximately ten thousand years ago in the mountains of Western Asia, marked a pivotal moment in the development of settled human communities.", "non-defining relative clause + noun phrase"),
            ("Having adapted over millennia to survive on sparse upland vegetation, sheep are among the most resilient and economically significant livestock animals in the world.", "participle clause - having done"),
            ("The sheep, valued simultaneously for its wool, milk, and meat across diverse pastoral cultures, embodies the kind of multi-purpose utility that made it central to the agricultural economies of antiquity.", "non-defining relative clause + relative clause"),
            ("It is the seemingly docile and uncomplicated nature of the sheep that has led to its widespread use as a metaphor for unthinking conformity, a characterisation that researchers increasingly argue is unfair to a socially complex animal.", "cleft sentence + relative clause + noun clause"),
            ("The intersection of climate change, shifting land use patterns, and evolving consumer preferences is placing unprecedented pressure on sheep farmers in many parts of the world, threatening livelihoods that have persisted for generations.", "noun phrase + gerund + relative clause"),
        ],
    },
    "cow": {
        "beginner": [
            ("The cow gives us milk.", "simple present"),
            ("We saw cows near the river.", "simple past"),
            ("The cow is black and white.", "present - to be + adjectives"),
            ("A cow eats grass all day.", "simple present"),
            ("The cow has large gentle eyes.", "simple present - has"),
        ],
        "elementary": [
            ("Can a cow produce milk every single day?", "question with can + frequency"),
            ("There is a cow resting under the big banyan tree.", "there is + present participle"),
            ("Could we get fresh milk directly from the cow on this farm?", "could - polite request"),
            ("Is this cow the one that gives the most milk on the farm?", "superlative question"),
            ("There are cows walking slowly along the village road in the evening.", "there are + present participle"),
        ],
        "intermediate": [
            ("If farmers look after their cows well, the cows will produce more milk and stay healthier.", "first conditional"),
            ("Cow's milk is more nutritious than many other drinks commonly available to children.", "comparative + noun phrase"),
            ("The cow wandered onto the road, so the farmer had to gently guide it back into the field.", "compound sentence - result"),
            ("Keeping cows requires daily care, plenty of space, and a consistent supply of clean water.", "gerund subject + noun phrase"),
            ("The cow appeared calm and comfortable, but the veterinarian noticed that it had a slight fever.", "compound sentence - contrast + reported observation"),
        ],
        "upper_intermediate": [
            ("The cow that had given birth to twin calves the previous night was being closely monitored by the farmer.", "relative clause - that + past continuous passive"),
            ("Cows are considered sacred in many parts of India and are treated with great respect and care.", "passive + compound"),
            ("The farmer whose cow had won the district livestock competition was invited to share his methods at the agricultural fair.", "relative clause - whose + passive"),
            ("The old cow, which had provided the family with milk for nearly a decade, was now too frail to stand for long.", "non-defining relative clause"),
            ("Anyone who has watched a calf take its first unsteady steps will find it difficult to remain unmoved by the sight.", "relative clause + noun clause"),
        ],
        "advanced": [
            ("The cow's central role in South Asian agrarian culture extends far beyond its economic value, encompassing religious symbolism, community identity, and a deeply ingrained ethic of care toward animals.", "noun phrase + gerund + list"),
            ("Having grazed on the rich grasslands of the valley since early summer, the cows were in exceptional condition as the harvest season approached.", "participle clause - having done"),
            ("The cow, revered in Hindu tradition as a symbol of abundance, non-violence, and the earth's nurturing qualities, occupies a position in cultural life that defies straightforward economic categorisation.", "non-defining relative clause + relative clause"),
            ("It is the extraordinary efficiency with which the cow converts grass into milk — a nutrient-dense food that sustains hundreds of millions of people — that makes cattle husbandry one of humanity's most consequential agricultural achievements.", "cleft sentence + dash clause + relative clause"),
            ("The complex interplay between rising global demand for dairy products, the environmental footprint of large-scale cattle farming, and the cultural significance of the cow in India makes this an area where economic, ecological, and ethical considerations are deeply intertwined.", "noun phrase + list + relative clause"),
        ],
    },
}
