from __future__ import annotations

SENTENCES_PART3 = {
    "wine glass": {
        "beginner": [
            ("The wine glass is on the table.", "simple_present_is"),
            ("She picked up the wine glass.", "simple_past"),
            ("The wine glass is tall and thin.", "simple_present_adjectives"),
            ("He put the wine glass down.", "simple_past_phrasal_verb"),
            ("The wine glass is empty now.", "simple_present_adjective_complement"),
        ],
        "elementary": [
            ("Is there a wine glass on the dinner table?", "yes_no_question_there_is"),
            ("There is a beautiful wine glass at my place setting.", "there_is_with_adjective"),
            ("Can you see the wine glass near the plate?", "can_for_ability_question"),
            ("There are four wine glasses on the restaurant table.", "there_are_plural"),
            ("Could you please pass me the wine glass?", "could_for_polite_request"),
        ],
        "intermediate": [
            ("The wine glass is taller than the water glass, and it has a wider bowl.", "comparative_and_compound_sentence"),
            ("If you hold the wine glass by the stem, you will keep it clean.", "first_conditional"),
            ("The waiter carefully placed the wine glass on the table and then filled it with juice.", "compound_sentence_adverb"),
            ("This wine glass is more elegant than the ones we have at home.", "comparative_adjective"),
            ("She washed the wine glass gently because it was made of thin crystal.", "compound_sentence_cause"),
        ],
        "upper_intermediate": [
            ("The wine glass that was placed at the centre of the table belonged to the guest of honour.", "relative_clause_defining"),
            ("The crystal wine glass, which had been a wedding gift, was handled with great care.", "relative_clause_non_defining"),
            ("After the formal dinner was finished, all the wine glasses were collected by the restaurant staff.", "passive_voice_past"),
            ("The wine glass she had chosen for the table setting was admired by all the guests at the celebration.", "relative_clause_with_passive"),
            ("Wine glasses are typically made from fine glass or crystal so that they are both light and durable.", "passive_voice_purpose_clause"),
        ],
        "advanced": [
            ("The elegant wine glass, positioned precisely at the top right of each place setting, lent an air of sophistication to the formal dining table.", "participial_phrase_sophisticated_vocabulary"),
            ("Although the restaurant's wine glasses were crafted from delicate crystal, they were designed to be both aesthetically pleasing and surprisingly resilient.", "concessive_clause_passive_voice"),
            ("Having admired the slender stem and generously curved bowl of the wine glass, she realised that even everyday objects could be works of art.", "perfect_participle_abstract_reflection"),
            ("The sommelier explained that the shape of a wine glass is not merely decorative but is engineered to direct aromas precisely towards the nose.", "reported_speech_complex_purpose_clause"),
            ("Gleaming under the chandelier's warm light, the row of wine glasses on the banquet table created a spectacle of quiet, understated luxury.", "participial_phrase_nuanced_description"),
        ],
    },
    "cup": {
        "beginner": [
            ("I drink tea from a cup.", "simple_present_routine"),
            ("The cup is blue.", "simple_present_is_adjective"),
            ("She filled the cup with water.", "simple_past"),
            ("The cup is on the shelf.", "simple_present_location"),
            ("He dropped the cup.", "simple_past_action"),
        ],
        "elementary": [
            ("There is a cup of hot chocolate on the desk.", "there_is_prepositional_phrase"),
            ("Can I have a cup of tea, please?", "can_for_request_polite"),
            ("Is there milk in that cup?", "yes_no_question_there_is"),
            ("There are two cups on the kitchen counter.", "there_are_plural"),
            ("Could you bring me a cup of warm water?", "could_for_polite_request"),
        ],
        "intermediate": [
            ("My cup is bigger than yours, so I can drink more juice.", "comparative_compound_sentence"),
            ("If you leave the cup on the edge of the table, it might fall.", "first_conditional_warning"),
            ("She washed the cup carefully and then placed it upside down to dry.", "compound_sentence_sequential_actions"),
            ("This ceramic cup keeps drinks warmer than a plastic one.", "comparative_adjective_materials"),
            ("He wrapped both hands around the warm cup because the morning was cold.", "compound_sentence_cause_reason"),
        ],
        "upper_intermediate": [
            ("The cup that my grandmother gave me is the one I use every single morning.", "relative_clause_defining_emphasis"),
            ("The handmade clay cup, which was bought at a craft fair, has become my favourite.", "relative_clause_non_defining"),
            ("The cups were arranged neatly in the cupboard after they had been washed and dried.", "passive_voice_sequence"),
            ("The insulated cup she carries to school every day ensures that her drink stays warm for hours.", "relative_clause_result_clause"),
            ("Personalised cups are often given as gifts because they are both practical and thoughtful.", "passive_voice_reason_clause"),
        ],
        "advanced": [
            ("The simple act of wrapping one's hands around a warm cup has long been associated with comfort and a sense of calm reassurance.", "abstract_noun_phrase_nuanced_meaning"),
            ("Though the cup appeared plain and unadorned on the outside, the intricate pattern painted on its interior made it a genuinely unique object.", "concessive_clause_contrast_sophisticated"),
            ("Having been handcrafted by a local potter, the cup possessed an irregularity that no mass-produced object could ever hope to replicate.", "perfect_participle_abstract_concept"),
            ("The anthropologist argued that the humble cup, present in virtually every human culture, serves as a fascinating lens through which to examine social rituals.", "relative_clause_abstract_intellectual"),
            ("Cradling the warm cup between her palms, she let the familiar ritual of her morning tea anchor her thoughts before the demands of the day began.", "participial_phrase_nuanced_emotional_register"),
        ],
    },
    "fork": {
        "beginner": [
            ("I eat rice with a fork.", "simple_present_routine"),
            ("The fork is on the table.", "simple_present_location"),
            ("She picked up the fork.", "simple_past_action"),
            ("The fork is silver.", "simple_present_adjective"),
            ("He put the fork beside the plate.", "simple_past_prepositional_phrase"),
        ],
        "elementary": [
            ("There is a fork next to the plate.", "there_is_prepositional_phrase"),
            ("Can you pass me the fork, please?", "can_for_polite_request"),
            ("Is there a fork in the drawer?", "yes_no_question_there_is"),
            ("There are clean forks in the cutlery box.", "there_are_plural_location"),
            ("Could you put the fork on the right side of the plate?", "could_for_request_instruction"),
        ],
        "intermediate": [
            ("A fork is more useful than a spoon when eating noodles.", "comparative_adjective_context"),
            ("If you use the correct fork at a formal dinner, it shows good table manners.", "first_conditional_social"),
            ("She used the fork to pick up the vegetables and then tasted the sauce.", "compound_sentence_sequential"),
            ("This stainless-steel fork is heavier than the plastic one we use for picnics.", "comparative_materials_context"),
            ("He held the fork properly because his teacher had taught him good table manners.", "compound_sentence_reason"),
        ],
        "upper_intermediate": [
            ("The fork that was placed on the left side of the plate is used for the salad course.", "relative_clause_defining_table_setting"),
            ("The silver fork, which had been polished before the dinner party, shone brightly under the light.", "relative_clause_non_defining_passive"),
            ("At formal dinners, separate forks are provided for each course so that flavours are not mixed.", "passive_voice_purpose"),
            ("The small dessert fork she picked up was lighter and more delicate than the main course fork.", "relative_clause_comparative"),
            ("In many cultures, the fork is considered the most versatile utensil at the dining table.", "passive_voice_cultural_context"),
        ],
        "advanced": [
            ("The introduction of the fork to European dining tables in the seventeenth century was initially met with ridicule before eventually becoming indispensable.", "historical_context_passive_voice_adverb"),
            ("Although a fork may seem like the simplest of objects, the precise balance between its handle and tines is the result of careful ergonomic consideration.", "concessive_clause_sophisticated_vocabulary"),
            ("Having been set meticulously by the catering staff, each fork lay at an exact measured distance from the edge of the white linen tablecloth.", "perfect_participle_precise_description"),
            ("The chef insisted that the way a diner holds a fork reveals far more about their cultural background than most people would readily acknowledge.", "reported_speech_relative_clause_nuanced"),
            ("In her still-life painting, the solitary fork resting against the empty plate conveyed a sense of quiet anticipation that words could scarcely capture.", "participial_phrase_abstract_artistic_meaning"),
        ],
    },
    "knife": {
        "beginner": [
            ("The knife is on the table.", "simple_present_location"),
            ("She used the knife to cut the bread.", "simple_past_purpose_infinitive"),
            ("The knife is sharp.", "simple_present_adjective"),
            ("He washed the knife after dinner.", "simple_past_routine"),
            ("The kitchen knife is very useful.", "simple_present_adjective_emphasis"),
        ],
        "elementary": [
            ("There is a knife beside the plate on the table.", "there_is_prepositional_phrase"),
            ("Can you cut the apple with that knife?", "can_for_ability_question"),
            ("Is the knife clean and ready to use?", "yes_no_question_adjectives"),
            ("There are different knives for cutting bread and meat.", "there_are_plural_purpose"),
            ("Could you please hand me the small knife?", "could_for_polite_request"),
        ],
        "intermediate": [
            ("A bread knife is more suitable for cutting loaves than a regular kitchen knife.", "comparative_adjective_specific_use"),
            ("If you keep the knife clean and dry, it will stay sharp for much longer.", "first_conditional_maintenance"),
            ("She carefully cut the mango with the knife and then placed the slices in the bowl.", "compound_sentence_adverb_sequential"),
            ("The large knife is heavier than the small one, but it is better for chopping vegetables.", "comparative_compound_sentence"),
            ("He always puts the knife in the drawer after washing it because safety is important in the kitchen.", "compound_sentence_reason"),
        ],
        "upper_intermediate": [
            ("The kitchen knife that the chef uses for slicing vegetables is kept razor sharp at all times.", "relative_clause_defining_profession"),
            ("The knife, which had been sharpened just before the cooking class, cut through the vegetables with ease.", "relative_clause_non_defining_passive"),
            ("In professional kitchens, knives are sharpened regularly by the chefs to ensure both precision and safety.", "passive_voice_routine_purpose"),
            ("The bread knife she selected had a serrated edge that made slicing through the crusty loaf effortless.", "relative_clause_result"),
            ("Knives are stored carefully in wooden blocks so that their blades are protected and the kitchen remains safe.", "passive_voice_purpose_compound"),
        ],
        "advanced": [
            ("The quality of a chef's knife is often considered the single most important factor in determining the efficiency and pleasure of any culinary endeavour.", "superlative_abstract_noun_sophisticated"),
            ("Although the modern kitchen knife appears deceptively simple, its design incorporates centuries of metallurgical knowledge and ergonomic refinement.", "concessive_clause_historical_sophisticated"),
            ("Having been honed to a fine edge before the cooking demonstration began, the knife glided through the ingredients with remarkable precision and minimal effort.", "perfect_participle_precise_vocabulary"),
            ("The culinary instructor emphasised that understanding how to handle a kitchen knife safely and confidently is the foundational skill upon which all other cooking techniques are built.", "reported_speech_complex_relative_clause"),
            ("Resting on the worn wooden chopping board, the well-used kitchen knife bore the subtle marks of countless meals prepared with care, patience, and no small measure of skill.", "participial_phrase_nuanced_evocative"),
        ],
    },
    "spoon": {
        "beginner": [
            ("I stir my tea with a spoon.", "simple_present_routine"),
            ("The spoon is in the bowl.", "simple_present_location"),
            ("She used a big spoon to serve the rice.", "simple_past_purpose"),
            ("The spoon is silver and shiny.", "simple_present_adjectives"),
            ("He lost his spoon at lunch.", "simple_past_action"),
        ],
        "elementary": [
            ("There is a spoon in the soup bowl.", "there_is_location"),
            ("Can you give me a spoon for my yoghurt?", "can_for_request"),
            ("Is there a spoon on the table?", "yes_no_question_there_is"),
            ("There are wooden spoons and metal spoons in the drawer.", "there_are_plural_types"),
            ("Could you pass me the large serving spoon?", "could_for_polite_request"),
        ],
        "intermediate": [
            ("A spoon is more suitable than a fork for eating soup or porridge.", "comparative_adjective_context"),
            ("If you use the right spoon, eating thick dhal will be much easier.", "first_conditional_practical"),
            ("She stirred the porridge with the spoon and then tasted it to check the sweetness.", "compound_sentence_sequential_actions"),
            ("The dessert spoon is smaller than a tablespoon but larger than a teaspoon.", "double_comparative_size"),
            ("He always carries a spoon in his lunchbox because his favourite food is curd rice.", "compound_sentence_reason_personal"),
        ],
        "upper_intermediate": [
            ("The wooden spoon that she uses for cooking has been in the family for more than twenty years.", "relative_clause_defining_time"),
            ("The silver spoon, which was part of the old cutlery set, was polished every week without fail.", "relative_clause_non_defining_passive"),
            ("In many Tamil households, a large serving spoon is placed in every dish so that each person can serve themselves.", "passive_voice_cultural_context"),
            ("The small spoon she stirred her tea with had a delicate floral pattern engraved on its handle.", "relative_clause_descriptive_detail"),
            ("Measuring spoons are used in baking so that each ingredient is added in precisely the right quantity.", "passive_voice_purpose_precision"),
        ],
        "advanced": [
            ("The image of a child learning to hold a spoon is one of the earliest and most universal symbols of growing independence and self-sufficiency.", "abstract_noun_universal_theme"),
            ("Although the spoon is arguably the oldest eating utensil known to humanity, its fundamental form has remained virtually unchanged across millennia of culinary evolution.", "concessive_clause_historical_sophisticated"),
            ("Having been carved by hand from a single piece of neem wood, the spoon carried with it the faint, pleasant scent of the tree and the craft of its maker.", "perfect_participle_sensory_evocative"),
            ("Ethnographers have long noted that the materials from which spoons are fashioned — wood, bone, silver, or plastic — offer a surprisingly revealing window into a society's resources and values.", "appositive_phrase_academic_nuanced"),
            ("As she watched her grandmother ladle sambar into each bowl with the same unhurried, generous motion she had always used, she understood that a spoon could carry far more than just food.", "complex_sentence_abstract_emotional_insight"),
        ],
    },
    "bowl": {
        "beginner": [
            ("The bowl is full of soup.", "simple_present_adjective_complement"),
            ("She ate rice from the bowl.", "simple_past_action"),
            ("The bowl is round and deep.", "simple_present_adjectives"),
            ("He washed the bowl after eating.", "simple_past_routine"),
            ("The bowl is on the kitchen table.", "simple_present_location"),
        ],
        "elementary": [
            ("There is a bowl of fresh fruit on the counter.", "there_is_noun_phrase"),
            ("Can you fill the bowl with warm water?", "can_for_request_instruction"),
            ("Is there enough rice in the bowl?", "yes_no_question_quantity"),
            ("There are two bowls of salad on the dining table.", "there_are_plural_location"),
            ("Could you bring me a bigger bowl for the dough?", "could_for_polite_request_comparative"),
        ],
        "intermediate": [
            ("This ceramic bowl is deeper than the plastic one, so it is better for soups.", "comparative_compound_sentence"),
            ("If you cover the bowl with a lid, the food inside will stay warm longer.", "first_conditional_practical"),
            ("She poured the batter into the bowl and then mixed it until it was smooth.", "compound_sentence_sequential"),
            ("The mixing bowl is much larger than the serving bowl because it needs to hold all the ingredients.", "comparative_reason_clause"),
            ("He placed the bowl of dhal on the table carefully because it was very hot.", "compound_sentence_reason_adverb"),
        ],
        "upper_intermediate": [
            ("The clay bowl that her mother uses for making idli batter has a wide mouth and a smooth surface.", "relative_clause_defining_descriptive"),
            ("The large salad bowl, which was placed at the centre of the table, was admired by all the guests.", "relative_clause_non_defining_passive"),
            ("In many South Indian homes, rice and dhal are served together in a single bowl so that they can be mixed easily.", "passive_voice_purpose_cultural"),
            ("The ceramic bowl she had painted during her art class was selected for display at the school exhibition.", "relative_clause_passive_achievement"),
            ("Bowls of various sizes are kept in every kitchen so that cooking and serving can be done efficiently.", "passive_voice_purpose_general"),
        ],
        "advanced": [
            ("The simple, unglazed clay bowl found at the archaeological site suggested that the civilisation had developed sophisticated culinary practices far earlier than previously believed.", "complex_sentence_inference_academic"),
            ("Although a bowl may appear to be the most utilitarian of objects, the craftsmanship of a hand-thrown ceramic bowl can elevate it to the status of fine art.", "concessive_clause_contrast_sophisticated"),
            ("Having been passed down through three generations of the family, the heavy brass bowl now occupied a place of quiet reverence on the kitchen shelf.", "perfect_participle_heritage_evocative"),
            ("The food stylist argued that the choice of bowl — its colour, texture, and depth — was just as important as the dish itself in creating an appetising visual presentation.", "reported_speech_appositive_nuanced"),
            ("As she slowly emptied the bowl of its last spoonfuls of warm payasam, she was struck by the peculiar sadness that accompanies the ending of something genuinely delicious.", "complex_sentence_abstract_emotional_precise"),
        ],
    },
    "banana": {
        "beginner": [
            ("I eat a banana every day.", "simple_present_routine_frequency"),
            ("The banana is yellow.", "simple_present_adjective"),
            ("She peeled the banana quickly.", "simple_past_adverb"),
            ("The banana is ripe and sweet.", "simple_present_adjectives"),
            ("He put the banana in his bag.", "simple_past_location"),
        ],
        "elementary": [
            ("There is a banana in my lunchbox today.", "there_is_location_time"),
            ("Can you give me that banana from the fruit bowl?", "can_for_request"),
            ("Is there a ripe banana in the kitchen?", "yes_no_question_adjective"),
            ("There are six bananas in the bunch on the table.", "there_are_plural_number"),
            ("Could you peel the banana for the little child?", "could_for_polite_request_purpose"),
        ],
        "intermediate": [
            ("A banana is more filling than an apple, so I eat one before my sports class.", "comparative_reason_compound"),
            ("If you keep the banana in the fridge, the skin will turn black but the fruit stays fresh.", "first_conditional_contrast"),
            ("She sliced the banana into the bowl and then added some honey on top.", "compound_sentence_sequential_detail"),
            ("The overripe banana is sweeter than a firm one, which makes it perfect for baking.", "comparative_relative_clause_purpose"),
            ("He eats a banana every morning because it gives him energy for the long school day.", "compound_sentence_reason"),
        ],
        "upper_intermediate": [
            ("The banana that was left on the counter overnight had turned perfectly ripe by the morning.", "relative_clause_defining_time_result"),
            ("The bunch of bananas, which had been bought from the market just that morning, was already half finished by afternoon.", "relative_clause_non_defining_passive_time"),
            ("In many parts of India, banana leaves are used as plates on which food is served during festivals.", "passive_voice_cultural_purpose"),
            ("The soft banana she mashed into the dough made the bread sweeter and more moist than usual.", "relative_clause_result_comparative"),
            ("Bananas are harvested while they are still green so that they ripen gradually during transport and reach shops at the perfect stage.", "passive_voice_process_purpose"),
        ],
        "advanced": [
            ("The Cavendish banana, which dominates global markets today, became the world's preferred variety only after the Gros Michel was devastated by a fungal disease in the mid-twentieth century.", "relative_clause_non_defining_historical_sophisticated"),
            ("Although the banana is often perceived as a humble, everyday fruit, its journey from a tropical plantation to a school lunchbox involves an intricate global supply chain.", "concessive_clause_contrast_global_context"),
            ("Having ripened to a deep, freckled yellow overnight, the banana released a heady, sweet fragrance that filled the kitchen with the unmistakable promise of a good breakfast.", "perfect_participle_sensory_evocative"),
            ("Nutritionists consistently point out that the banana's combination of natural sugars, fibre, and potassium makes it one of the most efficiently energy-yielding snacks available to athletes.", "reported_speech_superlative_sophisticated"),
            ("She regarded the blackened, over-soft banana on the counter not as waste but as an opportunity — the ideal foundation for the warm, fragrant loaf she had been meaning to bake all week.", "complex_sentence_reframing_nuanced_vocabulary"),
        ],
    },
    "apple": {
        "beginner": [
            ("I eat an apple after school.", "simple_present_routine_time"),
            ("The apple is red and round.", "simple_present_adjectives"),
            ("She bit into the apple.", "simple_past_action"),
            ("The apple tastes sweet.", "simple_present_sensory_verb"),
            ("He put the apple on the table.", "simple_past_location"),
        ],
        "elementary": [
            ("There is a shiny red apple in my bag.", "there_is_adjectives"),
            ("Can I have an apple from the fruit bowl?", "can_for_permission_request"),
            ("Is there an apple left in the basket?", "yes_no_question_quantity"),
            ("There are green apples and red apples in the market.", "there_are_plural_variety"),
            ("Could you cut the apple into slices for me?", "could_for_polite_request"),
        ],
        "intermediate": [
            ("A green apple is more sour than a red one, but I prefer the tangy taste.", "comparative_contrast_preference"),
            ("If you eat an apple every day, your teeth and gums will stay healthier.", "first_conditional_health"),
            ("She washed the apple carefully and then cut it into neat slices for the children.", "compound_sentence_adverb_sequential"),
            ("The apple in her bag was crisper and juicier than the ones sold at the school canteen.", "double_comparative_descriptive"),
            ("He chose the biggest apple in the basket because he was very hungry after the game.", "compound_sentence_reason_superlative"),
        ],
        "upper_intermediate": [
            ("The apple that fell from the tree in the garden was quickly picked up and eaten by the children.", "relative_clause_defining_passive"),
            ("The small apple, which had been grown in the school's own garden, tasted far sweeter than any store-bought variety.", "relative_clause_non_defining_comparative_passive"),
            ("In many cultures, an apple is given to teachers as a symbol of appreciation, a tradition that has persisted for generations.", "passive_voice_appositive_relative_clause"),
            ("The crisp, fragrant apple she selected at the market was the last of the season's harvest.", "relative_clause_defining_time_context"),
            ("Apples are stored in cool conditions after they are harvested so that they remain fresh for several months.", "passive_voice_process_purpose"),
        ],
        "advanced": [
            ("The apple occupies a uniquely symbolic position in human culture, appearing in myths, proverbs, and scientific legend with a frequency that far exceeds its botanical significance.", "complex_sentence_cultural_analysis_sophisticated"),
            ("Although hundreds of apple varieties exist worldwide, only a small handful are commercially cultivated, a narrowing of diversity that agricultural scientists view with growing concern.", "concessive_clause_passive_voice_academic"),
            ("Having been polished to a deep, burnished red by the vendor's cloth, the apple gleamed under the market lights like something out of a fairy tale.", "perfect_participle_allusion_evocative"),
            ("The seemingly simple act of biting into a cold, crisp apple — with its explosive rush of juice and sharp, clean flavour — is one of those small, underappreciated pleasures that punctuate an ordinary day.", "complex_sentence_sensory_philosophical"),
            ("She had read that the particular shade of red on a ripe apple is produced by pigments called anthocyanins, a discovery that made her regard the familiar fruit with a new and unexpected sense of wonder.", "reported_speech_appositive_abstract_reflection"),
        ],
    },
    "sandwich": {
        "beginner": [
            ("I eat a sandwich at lunch.", "simple_present_routine_time"),
            ("The sandwich has cheese and tomato.", "simple_present_has"),
            ("She made a sandwich for breakfast.", "simple_past_purpose"),
            ("The sandwich is delicious.", "simple_present_adjective"),
            ("He packed a sandwich in his lunchbox.", "simple_past_action"),
        ],
        "elementary": [
            ("There is a sandwich wrapped in paper in my bag.", "there_is_participial_phrase"),
            ("Can I have a vegetable sandwich, please?", "can_for_polite_request"),
            ("Is there a sandwich left in the lunch box?", "yes_no_question_quantity"),
            ("There are three sandwiches on the plate for the picnic.", "there_are_plural_context"),
            ("Could you make me a sandwich with cucumber and mint chutney?", "could_for_polite_request_detail"),
        ],
        "intermediate": [
            ("A sandwich is quicker to prepare than a hot meal, but it is just as filling.", "comparative_compound_sentence_contrast"),
            ("If you toast the bread before making the sandwich, it will stay crispy for longer.", "first_conditional_tip"),
            ("She spread the chutney on the bread, added the vegetables, and then pressed the sandwich firmly.", "compound_sentence_sequential_three_actions"),
            ("The grilled sandwich from the school canteen is tastier than the one I bring from home.", "comparative_personal_context"),
            ("He made a big sandwich because he had football practice after school and needed extra energy.", "compound_sentence_reason_context"),
        ],
        "upper_intermediate": [
            ("The sandwich that she had carefully prepared the night before was completely squashed by the time lunchtime arrived.", "relative_clause_defining_time_result"),
            ("The club sandwich, which contained three layers of bread and a variety of fillings, was too large for her to finish.", "relative_clause_non_defining_result"),
            ("In many school canteens across the world, sandwiches are sold as a convenient and nutritious lunchtime option.", "passive_voice_general_context"),
            ("The toasted sandwich he unwrapped from his lunchbox filled the entire classroom with a warm, spiced aroma.", "relative_clause_descriptive_sensory"),
            ("Sandwiches can be made more nutritious by using wholegrain bread and adding fresh vegetables instead of processed fillings.", "passive_voice_advice_comparative"),
        ],
        "advanced": [
            ("The sandwich, deceptively simple in its construction yet endlessly variable in its combinations, has become one of the most democratic and universally beloved forms of portable food.", "appositive_phrase_sophisticated_analysis"),
            ("Although the Earl of Sandwich is credited with popularising the concept in eighteenth-century England, variations of bread wrapped around fillings had existed across many cultures for centuries before.", "concessive_clause_historical_passive"),
            ("Having been assembled with an almost architectural precision — a thin layer of butter, crisp lettuce, sliced tomato, and well-seasoned filling — the sandwich was a small but genuine work of culinary craft.", "perfect_participle_appositive_precise_vocabulary"),
            ("She reflected that the packed sandwich, which her mother rose early each morning to prepare, was not merely lunch but a quiet, daily expression of love that she had only recently begun to appreciate.", "relative_clause_abstract_emotional_insight"),
            ("Food historians argue that the sandwich's genius lies not in any single ingredient but in the structural principle of enclosure, which transforms separate components into a unified, portable, and satisfying whole.", "reported_speech_complex_abstract_analysis"),
        ],
    },
    "orange": {
        "beginner": [
            ("I peel an orange every morning.", "simple_present_routine_time"),
            ("The orange is sweet and juicy.", "simple_present_adjectives"),
            ("She squeezed the orange for juice.", "simple_past_purpose"),
            ("The orange is round and bright.", "simple_present_adjectives"),
            ("He ate an orange after his meal.", "simple_past_time"),
        ],
        "elementary": [
            ("There is a fresh orange in the fruit basket.", "there_is_adjective"),
            ("Can you peel this orange for me, please?", "can_for_polite_request"),
            ("Is there orange juice in the fridge?", "yes_no_question_location"),
            ("There are four oranges left in the bag from the market.", "there_are_plural_location"),
            ("Could you cut the orange into quarters for the children?", "could_for_polite_request_purpose"),
        ],
        "intermediate": [
            ("An orange is juicier than a lemon, but a lemon is much more sour.", "double_comparative_contrast"),
            ("If you roll the orange on the table before peeling it, more juice will come out.", "first_conditional_tip"),
            ("She peeled the orange carefully, separated the segments, and placed them neatly in a bowl.", "compound_sentence_three_sequential_actions"),
            ("The juice of this orange is sweeter than the bottled juice we buy from the shop.", "comparative_personal_preference"),
            ("He eats an orange every day during winter because it is rich in vitamin C.", "compound_sentence_reason_health"),
        ],
        "upper_intermediate": [
            ("The orange that he plucked from the tree in his grandmother's garden was the sweetest he had ever tasted.", "relative_clause_defining_superlative"),
            ("The large navel orange, which had been imported from abroad, was available only at the supermarket.", "relative_clause_non_defining_passive"),
            ("In many Tamil households, oranges are offered to guests as a gesture of hospitality and welcome.", "passive_voice_cultural_context"),
            ("The freshly squeezed orange juice she prepared every morning was far more flavourful than any packaged variety.", "relative_clause_comparative_adverb"),
            ("Oranges are often harvested before they are fully ripe so that they can withstand the long journey to distant markets.", "passive_voice_process_purpose"),
        ],
        "advanced": [
            ("The act of peeling an orange — spiralling the rind away in one continuous, fragrant strip — is a small but satisfying exercise in patience and dexterity.", "abstract_noun_sensory_philosophical"),
            ("Although the orange is now cultivated across the globe, its origins lie in Southeast Asia, where it was first domesticated thousands of years ago in a form quite unlike the fruit we recognise today.", "concessive_clause_historical_contrast"),
            ("Having been left in the sun for the afternoon, the orange had warmed through so that when she finally peeled it, the juice ran down her hands in a small, sweet flood.", "perfect_participle_sensory_evocative"),
            ("The vibrant orange, its essential oil-laden peel releasing an invigorating scent the moment it was broken, struck her as one of nature's most generously designed packages.", "appositive_participial_phrase_sophisticated"),
            ("Nutritionists have long celebrated the orange not only for its vitamin C content but for the complex constellation of phytochemicals in its flesh and pith that work synergistically to support immune function.", "reported_speech_complex_academic_vocabulary"),
        ],
    },
    "broccoli": {
        "beginner": [
            ("I eat broccoli with rice.", "simple_present_routine_food"),
            ("The broccoli is green.", "simple_present_adjective_colour"),
            ("She cooked the broccoli in a pan.", "simple_past_method"),
            ("Broccoli is good for you.", "simple_present_health"),
            ("He did not like broccoli as a child.", "simple_past_negative"),
        ],
        "elementary": [
            ("There is some broccoli in the vegetable soup.", "there_is_uncountable_context"),
            ("Can you add broccoli to the stir-fry, please?", "can_for_polite_request"),
            ("Is there any broccoli left in the fridge?", "yes_no_question_any_quantity"),
            ("There are two heads of broccoli on the kitchen counter.", "there_are_countable_noun"),
            ("Could you steam the broccoli for five minutes?", "could_for_instruction_time"),
        ],
        "intermediate": [
            ("Steamed broccoli is healthier than fried broccoli because it keeps more nutrients.", "comparative_reason_health"),
            ("If you overcook the broccoli, it will turn yellow and lose its crunch.", "first_conditional_cooking_warning"),
            ("She blanched the broccoli quickly, drained it, and then tossed it with olive oil and garlic.", "compound_sentence_three_sequential_culinary"),
            ("The broccoli in this dish is crispier and more flavourful than the one we had at the canteen.", "double_comparative_contrast_personal"),
            ("He started eating broccoli regularly because his doctor said it would improve his health.", "compound_sentence_reason_reported"),
        ],
        "upper_intermediate": [
            ("The head of broccoli that she bought from the market was so fresh that it lasted for a whole week in the fridge.", "relative_clause_defining_result"),
            ("The roasted broccoli, which had been seasoned with spices before being placed in the oven, was surprisingly delicious.", "relative_clause_non_defining_passive"),
            ("In many school lunch programmes, broccoli is included in meals because it is rich in vitamins and minerals.", "passive_voice_reason_health"),
            ("The bright green florets she added to the soup gave the dish a vivid colour and a satisfying crunch.", "relative_clause_result_sensory"),
            ("Broccoli is best stored unwashed in the refrigerator so that it retains its freshness and nutritional value for as long as possible.", "passive_voice_advice_purpose"),
        ],
        "advanced": [
            ("Broccoli's reputation as a superfood, once dismissed as nutritional marketing, has been substantiated by a growing body of research highlighting its exceptionally dense concentration of antioxidants.", "appositive_phrase_concessive_academic"),
            ("Although many children instinctively recoil from broccoli's slightly bitter taste, this bitterness is produced by glucosinolates — the very compounds that make the vegetable so beneficial to human health.", "concessive_clause_appositive_sophisticated"),
            ("Having been lightly steamed to preserve both its vivid emerald colour and its considerable nutritional integrity, the broccoli served at the hospital canteen was a model of simple, healthful cooking.", "perfect_participle_parallel_structure"),
            ("The agricultural scientist explained that the wide variation in broccoli's flavour intensity between individuals is partly attributable to genetic differences in taste receptor sensitivity, particularly for bitter compounds.", "reported_speech_complex_scientific_vocabulary"),
            ("She had never given much thought to broccoli until she read that the small, tightly packed florets of a single head could contain more vitamin C than a large orange, a fact that permanently altered her view of this quietly extraordinary vegetable.", "complex_sentence_discovery_reflection_sophisticated"),
        ],
    },
    "carrot": {
        "beginner": [
            ("I like eating carrots.", "simple_present_like_gerund"),
            ("The carrot is orange and long.", "simple_present_adjectives"),
            ("She cut the carrot into small pieces.", "simple_past_detail"),
            ("Carrots are good for your eyes.", "simple_present_health"),
            ("He pulled a carrot from the ground.", "simple_past_vivid_action"),
        ],
        "elementary": [
            ("There is a carrot in the vegetable soup.", "there_is_context"),
            ("Can you grate the carrot for the salad?", "can_for_request_cooking"),
            ("Is there a carrot in the fridge we can use?", "yes_no_question_location"),
            ("There are five carrots in the bag from the market.", "there_are_plural_number"),
            ("Could you peel the carrot before chopping it?", "could_for_instruction_sequence"),
        ],
        "intermediate": [
            ("A raw carrot is crunchier than a boiled one, but both are healthy to eat.", "comparative_compound_sentence_contrast"),
            ("If you eat carrots regularly, they will help keep your eyesight strong.", "first_conditional_health"),
            ("She peeled the carrot, grated it finely, and then mixed it into the dough for the halwa.", "compound_sentence_three_sequential_culinary"),
            ("The carrots in this stew are softer and more flavourful than the ones in the packet soup.", "double_comparative_personal_preference"),
            ("He added carrots to the lunch box because they are easy to eat and do not need cooking.", "compound_sentence_reason_practical"),
        ],
        "upper_intermediate": [
            ("The large, sweet carrot that she found at the bottom of the vegetable bag was perfect for making halwa.", "relative_clause_defining_purpose"),
            ("The grated carrot, which had been mixed with lemon juice and a pinch of salt, made a simple but refreshing side salad.", "relative_clause_non_defining_passive"),
            ("In many traditional Indian recipes, carrots are grated and cooked slowly in milk and sugar to make a rich, fragrant dessert.", "passive_voice_process_cultural"),
            ("The bright orange carrots she placed alongside the potatoes and beans added both colour and sweetness to the stew.", "relative_clause_result_sensory"),
            ("Carrots are grown throughout India and are harvested during the cooler months so that they develop their characteristic sweetness.", "passive_voice_process_seasonal"),
        ],
        "advanced": [
            ("The humble carrot, cultivated for thousands of years in forms ranging from purple to white before selective breeding produced the familiar orange variety, carries within it a surprisingly rich agricultural history.", "appositive_phrase_historical_participial"),
            ("Although the association between carrots and improved eyesight has been somewhat overstated in popular culture, the beta-carotene they contain does play a genuinely important role in maintaining ocular health.", "concessive_clause_nuanced_scientific"),
            ("Having been slow-cooked for nearly two hours in a mixture of milk, cardamom, and sugar, the carrots had dissolved into a yielding, intensely flavoured mass that formed the foundation of a magnificent gajar halwa.", "perfect_participle_culinary_evocative"),
            ("The gardener pointed out that the sweetness of a freshly pulled carrot, still cool from the soil and carrying the faint, green scent of its leafy top, is a pleasure that no commercially stored carrot can ever quite replicate.", "reported_speech_complex_sensory_contrast"),
            ("She found something quietly remarkable in the carrot's transformation — from a tough, unpromising root pulled from cold earth to, under the patient application of heat and sweetness, a dish of extraordinary comfort and depth.", "complex_sentence_metaphorical_culinary_reflection"),
        ],
    },
    "hot dog": {
        "beginner": [
            ("I eat a hot dog at the school fair.", "simple_present_routine_context"),
            ("The hot dog is in a soft bun.", "simple_present_location"),
            ("She put ketchup on the hot dog.", "simple_past_action"),
            ("The hot dog smells delicious.", "simple_present_sensory"),
            ("He bought a hot dog at the food stall.", "simple_past_context"),
        ],
        "elementary": [
            ("There is a hot dog with mustard at the snack counter.", "there_is_prepositional_phrase"),
            ("Can I have a hot dog with extra ketchup, please?", "can_for_polite_request_detail"),
            ("Is there a hot dog stall near the entrance of the fair?", "yes_no_question_location"),
            ("There are several hot dog stalls at the school food festival.", "there_are_plural_context"),
            ("Could you pass me the ketchup for my hot dog?", "could_for_polite_request"),
        ],
        "intermediate": [
            ("A grilled hot dog tastes better than a boiled one because grilling adds a smoky flavour.", "comparative_reason_cooking_method"),
            ("If you add onions and mustard to the hot dog, it will taste even more delicious.", "first_conditional_enhancement"),
            ("She ordered a hot dog, added toppings from the condiment station, and then found a seat in the shade.", "compound_sentence_three_sequential_context"),
            ("The hot dog from the food truck was much juicier and more flavourful than the packaged ones.", "double_comparative_personal_preference"),
            ("He ate a hot dog at the school fun day because it was the most popular snack at the event.", "compound_sentence_reason_superlative"),
        ],
        "upper_intermediate": [
            ("The hot dog that she bought at the fair was served in a freshly toasted bun with three different sauces.", "relative_clause_defining_descriptive_detail"),
            ("The sizzling hot dog, which had been grilling on the open griddle for several minutes, was handed to her wrapped in paper.", "relative_clause_non_defining_passive"),
            ("At school food festivals, hot dogs are usually prepared fresh on the spot so that students can enjoy them while they are still hot.", "passive_voice_context_purpose"),
            ("The large hot dog he unwrapped at the picnic was topped with caramelised onions and a generous squeeze of mustard.", "relative_clause_descriptive_sensory"),
            ("Hot dogs are typically served in a split bread roll and garnished with condiments so that they are easy to eat without cutlery.", "passive_voice_process_purpose"),
        ],
        "advanced": [
            ("The hot dog, a staple of fairs, sporting events, and roadside stalls across many parts of the world, occupies a curious position as one of the most cheerfully unpretentious foods in the global culinary landscape.", "appositive_phrase_cultural_analysis"),
            ("Although the hot dog's origins are disputed between Frankfurt and Vienna — both cities claim to have invented the sausage — its transformation into a popular street food is incontrovertibly an American story.", "concessive_clause_historical_geographical"),
            ("Having been pressed onto the griddle and turned with practised ease by the vendor, the hot dog arrived in its bun with a satisfying char that spoke of experience and many thousands of sausages previously grilled.", "perfect_participle_evocative_sensory"),
            ("Food anthropologists note that the hot dog's enduring appeal lies partly in its portability and partly in the almost ritualistic pleasure of customising one's own toppings from a shared condiment station.", "reported_speech_complex_analysis_sophisticated"),
            ("She bit into the hot dog and was struck, not for the first time, by how thoroughly a simple combination of spiced meat, soft bread, and sharp condiment could satisfy a hunger that more elaborate food sometimes failed to touch.", "complex_sentence_philosophical_sensory_reflection"),
        ],
    },
    "pizza": {
        "beginner": [
            ("I love eating pizza.", "simple_present_love_gerund"),
            ("The pizza has cheese on top.", "simple_present_has"),
            ("She shared the pizza with her friends.", "simple_past_social"),
            ("The pizza is hot and tasty.", "simple_present_adjectives"),
            ("He ordered a pizza for dinner.", "simple_past_action"),
        ],
        "elementary": [
            ("There is a pizza with vegetables in the oven.", "there_is_prepositional_phrase"),
            ("Can we order a pizza for the class party?", "can_for_permission_suggestion"),
            ("Is there any pizza left in the box?", "yes_no_question_any_quantity"),
            ("There are eight slices in this pizza, so we can each have two.", "there_are_plural_maths_context"),
            ("Could you save a slice of pizza for me?", "could_for_polite_request"),
        ],
        "intermediate": [
            ("A thin-crust pizza is crispier than a thick-crust one, but I prefer the thick crust.", "comparative_personal_preference"),
            ("If you add extra cheese and vegetables, the pizza will be both tastier and more filling.", "first_conditional_double_result"),
            ("She rolled out the dough, spread the tomato sauce, and then added the toppings before baking.", "compound_sentence_four_sequential_culinary"),
            ("The pizza at the new restaurant is much better than the one we had at the school canteen.", "comparative_specific_contexts"),
            ("He chose a vegetable pizza because he does not eat meat and wanted a filling dinner.", "compound_sentence_double_reason"),
        ],
        "upper_intermediate": [
            ("The pizza that the students baked in the home science class was better than anyone had expected.", "relative_clause_defining_result"),
            ("The large margherita pizza, which was shared among the six of them, disappeared within ten minutes.", "relative_clause_non_defining_result_time"),
            ("In many schools, pizza is sold at the canteen on Fridays as a popular end-of-week treat.", "passive_voice_context_routine"),
            ("The vegetarian pizza she designed for the school food project featured locally grown vegetables and a homemade sauce.", "relative_clause_descriptive_achievement"),
            ("Pizzas can be personalised with a wide variety of toppings so that each person can enjoy exactly the combination they prefer.", "passive_voice_purpose_personalisation"),
        ],
        "advanced": [
            ("The pizza, in its authentic Neapolitan form, is a study in restraint — a thin, slightly charred disc of dough bearing the minimum of toppings necessary to create maximum flavour.", "appositive_phrase_sophisticated_culinary_analysis"),
            ("Although pizza is now one of the most widely consumed foods on the planet, its global proliferation has produced countless regional variations that would be entirely unrecognisable to its Italian originators.", "concessive_clause_passive_voice_global_context"),
            ("Having been fired in a wood-burning oven at an intensely high temperature for no more than ninety seconds, the pizza arrived at the table with a perfectly blistered crust and a molten, aromatic centre.", "perfect_participle_culinary_precise_sensory"),
            ("Food writers often argue that the enduring appeal of pizza lies in the genius of its architecture — the structural integrity of the crust, the moisture balance of the sauce, and the precise melt of the cheese working in perfect concert.", "reported_speech_appositive_complex_culinary_analysis"),
            ("As she lifted the first slice and watched the cheese stretch in a long, reluctant strand, she understood intuitively why this simple combination of dough, tomato, and cheese had managed to conquer the world's appetite.", "complex_sentence_sensory_philosophical_insight"),
        ],
    },
    "donut": {
        "beginner": [
            ("I ate a donut at the bakery.", "simple_past_location"),
            ("The donut has pink icing on top.", "simple_present_has_colour"),
            ("She chose a chocolate donut.", "simple_past_choice"),
            ("The donut is sweet and fluffy.", "simple_present_adjectives"),
            ("He shared his donut with his sister.", "simple_past_social"),
        ],
        "elementary": [
            ("There is a glazed donut on the plate.", "there_is_adjective_location"),
            ("Can I have a donut with sprinkles, please?", "can_for_polite_request_detail"),
            ("Is there a donut left in the box?", "yes_no_question_quantity"),
            ("There are a dozen donuts in the bag from the bakery.", "there_are_plural_number_context"),
            ("Could you save a donut for my brother?", "could_for_polite_request"),
        ],
        "intermediate": [
            ("A freshly made donut is much softer than a donut that has been sitting in the box all day.", "comparative_time_context"),
            ("If you warm the donut in the oven for a few minutes, it will taste almost as good as freshly baked.", "first_conditional_tip_comparison"),
            ("She picked up a donut, examined the icing carefully, and then took a big, happy bite.", "compound_sentence_three_sequential_vivid"),
            ("The jam-filled donut was messier to eat but far more satisfying than the plain glazed one.", "comparative_contrast_personal"),
            ("He bought two donuts because the school bake sale was raising money for the new library.", "compound_sentence_reason_context"),
        ],
        "upper_intermediate": [
            ("The donut that was decorated with tiny stars and a swirl of blue icing was chosen by every child who passed the stall.", "relative_clause_defining_result"),
            ("The ring-shaped donut, which had been rolled in cinnamon sugar while it was still warm, filled the kitchen with a wonderful spiced scent.", "relative_clause_non_defining_passive_sensory"),
            ("At the school fundraiser, donuts were baked by the students themselves and sold to raise money for the sports equipment fund.", "passive_voice_context_purpose"),
            ("The enormous, elaborately decorated donut she photographed for her food blog became unexpectedly popular on social media.", "relative_clause_result_modern_context"),
            ("Donuts are often coated in icing or dusted with sugar just before they are sold so that they look and taste as fresh as possible.", "passive_voice_process_time_purpose"),
        ],
        "advanced": [
            ("The donut occupies a peculiar place in popular culture — simultaneously a symbol of indulgence, a staple of police station breakrooms in American television, and, increasingly, the centrepiece of artisanal bakery menus.", "appositive_phrase_list_cultural_analysis"),
            ("Although the donut's deep-fried origins might suggest it is purely a vehicle for excess, the skill involved in achieving a perfectly light, even crumb with a delicately crisp exterior is not inconsiderable.", "concessive_clause_nuanced_culinary"),
            ("Having been left to prove overnight in a cool room, the donut dough had developed a complex, slightly fermented flavour that made the finished product far more interesting than anything achievable with a rapid rise.", "perfect_participle_technical_culinary_sophisticated"),
            ("The pastry chef explained that the ideal donut exists at a precise intersection of contrasts — a crust that offers the barest resistance before yielding to an interior of extraordinary softness and warmth.", "reported_speech_abstract_sensory_precise"),
            ("She stood at the bakery counter for far longer than was strictly necessary, deliberating over which donut to choose, and in that small, unhurried moment of sweet indecision found something that resembled genuine happiness.", "complex_sentence_philosophical_reflection_nuanced"),
        ],
    },
    "cake": {
        "beginner": [
            ("We eat cake on birthdays.", "simple_present_routine_occasion"),
            ("The cake is chocolate and sweet.", "simple_present_adjectives"),
            ("She baked a cake yesterday.", "simple_past_time"),
            ("The cake has cream on top.", "simple_present_has"),
            ("He cut the cake into slices.", "simple_past_action"),
        ],
        "elementary": [
            ("There is a birthday cake on the table.", "there_is_context"),
            ("Can I have a slice of the chocolate cake?", "can_for_permission_request"),
            ("Is there any cake left after the party?", "yes_no_question_any_time"),
            ("There are candles on the cake for each year of her age.", "there_are_plural_purpose"),
            ("Could you save me a piece of cake before it is all gone?", "could_for_polite_request_urgency"),
        ],
        "intermediate": [
            ("A homemade cake is tastier than a shop-bought one because it is made with fresh ingredients.", "comparative_reason_clause"),
            ("If you do not let the cake cool completely, the icing will melt when you spread it.", "first_conditional_baking_warning"),
            ("She mixed the batter, poured it into the tin, and then placed it in the oven to bake for forty minutes.", "compound_sentence_four_sequential_baking"),
            ("The mango cake that appeared at the school party was more popular than the vanilla one.", "comparative_specific_context"),
            ("He asked his mother to bake a cake because his entire class was coming over to celebrate his birthday.", "compound_sentence_reason_social"),
        ],
        "upper_intermediate": [
            ("The three-tiered cake that was displayed at the school's annual food festival was admired by students and teachers alike.", "relative_clause_defining_passive_context"),
            ("The sponge cake, which had been baked early that morning and allowed to cool slowly, was light and perfectly even.", "relative_clause_non_defining_passive_sequential"),
            ("In many Tamil families, a special sweet cake is prepared during festivals and shared with neighbours as a gesture of celebration.", "passive_voice_cultural_context"),
            ("The richly decorated cake she designed for the competition incorporated local flavours like cardamom and coconut.", "relative_clause_descriptive_cultural_detail"),
            ("Cakes are typically decorated after they have cooled so that the icing does not run and the decorations stay in place.", "passive_voice_process_sequence_purpose"),
        ],
        "advanced": [
            ("The cake, in virtually every culture that has mastered the art of baking, serves simultaneously as a vehicle for sweetness and as a social object — a tangible marker of celebration, affection, and shared occasion.", "appositive_phrase_parallel_structure_sophisticated"),
            ("Although the elaborately tiered celebration cake is a relatively recent invention, the human impulse to sweeten food for festive occasions stretches back to antiquity, predating refined sugar by many centuries.", "concessive_clause_historical_contrast_sophisticated"),
            ("Having been iced with painstaking care over the course of an entire afternoon, the cake stood on the counter as a testament to the baker's patience and her deep, practical love for the people who would eat it.", "perfect_participle_abstract_emotional_reflection"),
            ("The food writer observed that a truly excellent cake achieves a balance so precise — between sweetness and depth, between structural integrity and tender crumb — that the skill involved becomes entirely invisible, which is, of course, the highest form of craft.", "reported_speech_complex_abstract_sophisticated_analysis"),
            ("As the candles were lit and the familiar melody rose from the assembled voices of her family, she looked at the cake — imperfectly iced, slightly lopsided, made with obvious love — and felt something close to perfect contentment.", "complex_sentence_sensory_emotional_nuanced"),
        ],
    },
    "chair": {
        "beginner": [
            ("I sit on a chair at school.", "simple_present_routine_location"),
            ("The chair is made of wood.", "simple_present_material"),
            ("She moved the chair to the table.", "simple_past_direction"),
            ("The chair is blue and comfortable.", "simple_present_adjectives"),
            ("He sat on the chair and waited.", "simple_past_compound"),
        ],
        "elementary": [
            ("There is a chair next to the window.", "there_is_prepositional_phrase"),
            ("Can you bring the chair from the other room?", "can_for_request"),
            ("Is there an empty chair at the back of the classroom?", "yes_no_question_adjective_location"),
            ("There are thirty chairs in the school hall for the assembly.", "there_are_plural_number_context"),
            ("Could you pull the chair a little closer to the table?", "could_for_polite_request_direction"),
        ],
        "intermediate": [
            ("This wooden chair is more comfortable than the plastic ones we used last year.", "comparative_personal_time_context"),
            ("If you sit in the same chair for too long, your back will start to ache.", "first_conditional_health_warning"),
            ("She pulled the chair out, sat down, and opened her notebook ready for the lesson.", "compound_sentence_three_sequential_classroom"),
            ("The padded chair in the library is far more comfortable than any of the chairs in the classroom.", "comparative_specific_locations"),
            ("He saved a chair for his friend because she had gone to collect her lunch tray.", "compound_sentence_reason_context"),
        ],
        "upper_intermediate": [
            ("The old wooden chair that had stood in the corner of the classroom for as long as anyone could remember was finally replaced.", "relative_clause_defining_time_result"),
            ("The comfortable reading chair, which was positioned near the window in the school library, was always the first to be taken.", "relative_clause_non_defining_passive_result"),
            ("In many traditional Tamil homes, chairs are arranged in a circle in the main hall so that conversation can flow freely among family members.", "passive_voice_cultural_context_purpose"),
            ("The small, rickety chair she had always avoided suddenly seemed, after a week of standing, wonderfully inviting.", "relative_clause_time_contrast_result"),
            ("Chairs are designed to support the natural curve of the spine so that prolonged sitting causes as little physical strain as possible.", "passive_voice_purpose_health"),
        ],
        "advanced": [
            ("The chair, that most ordinary and ubiquitous of domestic objects, has nonetheless attracted the sustained attention of some of the twentieth century's greatest designers, who saw in its simple geometry an endlessly renewable design challenge.", "appositive_phrase_relative_clause_sophisticated"),
            ("Although we rarely give conscious thought to the chair we sit in for hours each day, its height, the rake of its back, and the firmness of its seat profoundly influence our posture, our comfort, and even our mood.", "concessive_clause_complex_analysis_sophisticated"),
            ("Having been designed by a renowned architect as a statement piece for the school's new library, the chair managed to be both visually arresting and, contrary to expectation, genuinely comfortable.", "perfect_participle_concessive_nuanced"),
            ("The ergonomist explained that the ideal chair does not encourage its occupant to remain still but rather to shift position frequently, thereby maintaining circulation and reducing the muscular fatigue associated with prolonged sedentary work.", "reported_speech_complex_academic_purpose"),
            ("She noticed that after an entire day in the new school hall chairs, she was not nearly as stiff as usual, and it occurred to her, not for the first time, that the objects we take most for granted are often the ones that matter most to our daily wellbeing.", "complex_sentence_reflection_abstract_insight"),
        ],
    },
    "couch": {
        "beginner": [
            ("I sit on the couch after school.", "simple_present_routine_time"),
            ("The couch is soft and big.", "simple_present_adjectives"),
            ("She fell asleep on the couch.", "simple_past_action"),
            ("The couch is in the living room.", "simple_present_location"),
            ("He reads on the couch every evening.", "simple_present_routine_frequency"),
        ],
        "elementary": [
            ("There is a couch by the window in the living room.", "there_is_prepositional_phrase"),
            ("Can you move the couch to make room for the guests?", "can_for_request_purpose"),
            ("Is there space on the couch for one more person?", "yes_no_question_quantity"),
            ("There are three cushions on the couch in our sitting room.", "there_are_plural_location"),
            ("Could you sit on the couch and wait for a few minutes?", "could_for_polite_request"),
        ],
        "intermediate": [
            ("Our new couch is softer and more comfortable than the old wooden bench we had before.", "double_comparative_personal_contrast"),
            ("If everyone sits on the couch together, we can all watch the film at the same time.", "first_conditional_practical_social"),
            ("She moved the cushions to one side, stretched out on the couch, and immediately felt herself relax.", "compound_sentence_three_sequential_sensory"),
            ("The couch near the balcony door gets more sunlight than the one against the far wall.", "comparative_location_specific"),
            ("He always sits on the same corner of the couch because it has the best view of the television.", "compound_sentence_reason_personal"),
        ],
        "upper_intermediate": [
            ("The large corner couch that they had ordered for the new flat arrived three weeks later than expected.", "relative_clause_defining_time_result"),
            ("The old family couch, which had been in the sitting room for more than fifteen years, was finally donated to a charity.", "relative_clause_non_defining_passive_time"),
            ("In many Indian homes, the living room couch is used not only for sitting but as an informal gathering space where the family comes together in the evenings.", "passive_voice_purpose_cultural_extended"),
            ("The comfortable couch she had placed next to the bookshelf quickly became her favourite place to read on weekend mornings.", "relative_clause_result_personal"),
            ("Couches are often positioned facing the main wall of a living room so that the television, or the centre of conversation, remains the natural focal point.", "passive_voice_purpose_design"),
        ],
        "advanced": [
            ("The couch, perhaps more than any other single piece of household furniture, encapsulates the modern aspiration towards domestic comfort — a designated space for rest, warmth, and the deliberate abandonment of productivity.", "appositive_phrase_abstract_sophisticated"),
            ("Although the couch is easily dismissed as a symbol of passivity, the evening hours spent on it — reading, talking, watching, simply being — constitute some of the most genuinely restorative time in a busy person's day.", "concessive_clause_abstract_philosophical"),
            ("Having been reupholstered in a warm, textured fabric the previous spring, the old couch had been entirely transformed in character, its new surface inviting a kind of deliberate, unhurried lounging that the stiff original material had never encouraged.", "perfect_participle_extended_descriptive_sensory"),
            ("Interior designers frequently note that the placement and scale of a couch are the single most influential decisions in a living room, capable of either opening the space generously or enclosing it with oppressive heaviness.", "reported_speech_superlative_sophisticated_analysis"),
            ("There is something quietly profound about the way a well-used family couch accumulates, in its cushions and its worn armrests, the invisible residue of countless evenings — arguments resolved, stories told, and silences shared — that no new piece of furniture can replicate.", "complex_sentence_abstract_emotional_reflective_sophisticated"),
        ],
    },
    "potted plant": {
        "beginner": [
            ("There is a potted plant on the window sill.", "there_is_location"),
            ("The potted plant has green leaves.", "simple_present_has"),
            ("She waters the potted plant every morning.", "simple_present_routine_time"),
            ("The potted plant is growing well.", "present_continuous_positive"),
            ("He bought a potted plant for the classroom.", "simple_past_purpose"),
        ],
        "elementary": [
            ("There is a small potted plant on the teacher's desk.", "there_is_adjective_location"),
            ("Can you water the potted plant while I am away?", "can_for_request_time_clause"),
            ("Is there a potted plant in the corner of the room?", "yes_no_question_location"),
            ("There are potted plants on every window sill in the school corridor.", "there_are_plural_location"),
            ("Could you move the potted plant closer to the sunlight?", "could_for_polite_request_purpose"),
        ],
        "intermediate": [
            ("This potted plant grows faster than the one we have in the shaded corner.", "comparative_condition_context"),
            ("If you water the potted plant too much, the roots will rot and the plant will die.", "first_conditional_warning"),
            ("She repotted the plant, placed it on the sunny windowsill, and watched it recover within a week.", "compound_sentence_three_sequential_result"),
            ("The potted plant in the library is healthier and more vibrant than the one in the hallway.", "double_comparative_specific_locations"),
            ("He takes care of the classroom potted plant because he wants to learn how to grow things.", "compound_sentence_reason_motivation"),
        ],
        "upper_intermediate": [
            ("The potted plant that was placed in the science lab as a photosynthesis demonstration grew visibly taller each week.", "relative_clause_defining_purpose_result"),
            ("The large potted plant, which had been given to the school by a parent volunteer, now stood proudly in the reception area.", "relative_clause_non_defining_passive_adverb"),
            ("In many classrooms, potted plants are kept near windows so that students can observe plant growth as part of their science curriculum.", "passive_voice_purpose_educational"),
            ("The small potted plant she had nurtured from a single cutting had grown into a lush, leafy specimen that filled the corner of her bedroom.", "relative_clause_process_result_descriptive"),
            ("Potted plants are increasingly used in school buildings to improve indoor air quality and create a calmer, more welcoming learning environment.", "passive_voice_purpose_dual_benefit"),
        ],
        "advanced": [
            ("The potted plant, positioned with deliberate care near the south-facing window of the study room, served as a quiet reminder that even within an artificial, constructed environment, something green and living could thrive.", "participial_phrase_abstract_philosophical"),
            ("Although the scientific evidence for dramatic air-purifying benefits of indoor plants has been somewhat overstated in popular media, their psychological effect on occupants of enclosed spaces appears to be both genuine and significant.", "concessive_clause_nuanced_scientific_academic"),
            ("Having been transferred from a tiny seedling pot into a generous ceramic planter filled with rich compost, the plant had repaid the attention with a burst of new growth that seemed almost gratuitously exuberant.", "perfect_participle_extended_sensory_vocabulary"),
            ("Environmental psychologists have found that the presence of even a single potted plant in a workspace measurably reduces reported stress levels and increases subjective feelings of both calm and creative productivity.", "reported_speech_complex_academic_vocabulary"),
            ("She tended the potted plants along the classroom window sill with an attention that her classmates found amusing but that she understood, instinctively, as a kind of practice in noticing — the patient, daily act of paying attention to something small, slow, and alive.", "complex_sentence_philosophical_abstract_personal_insight"),
        ],
    },
    "bed": {
        "beginner": [
            ("I sleep in my bed every night.", "simple_present_routine_time"),
            ("The bed is soft and warm.", "simple_present_adjectives"),
            ("She made her bed in the morning.", "simple_past_routine"),
            ("The bed has a blue blanket on it.", "simple_present_has"),
            ("He jumped on the bed happily.", "simple_past_adverb"),
        ],
        "elementary": [
            ("There is a bed with a mosquito net in the room.", "there_is_prepositional_phrase"),
            ("Can you make the bed before you leave for school?", "can_for_request_time_clause"),
            ("Is there enough space for a second bed in the room?", "yes_no_question_quantity_purpose"),
            ("There are two beds in the room that my brother and I share.", "there_are_plural_relative_clause"),
            ("Could you put the clean sheets on the bed, please?", "could_for_polite_request"),
        ],
        "intermediate": [
            ("My new bed is much more comfortable than the old cot I slept on before.", "comparative_personal_time_contrast"),
            ("If you go to bed at the same time every night, you will sleep more deeply and wake up feeling refreshed.", "first_conditional_health_double_result"),
            ("She fluffed the pillows, straightened the blanket, and then stood back to survey the neatly made bed.", "compound_sentence_three_sequential_domestic"),
            ("The bed near the window gets more breeze at night, which makes it easier to sleep during summer.", "comparative_reason_relative_clause_seasonal"),
            ("He could not sleep because the bed in the guest room was far too hard for his liking.", "compound_sentence_reason_comparative"),
        ],
        "upper_intermediate": [
            ("The bed that her grandmother had slept in for forty years was eventually moved to the storage room to make space.", "relative_clause_defining_time_purpose"),
            ("The wide, low wooden bed, which had been built by a local carpenter, fitted the room perfectly and gave it a warm, traditional character.", "relative_clause_non_defining_passive_result"),
            ("In many traditional Tamil homes, family members sleep on mats spread on the floor rather than on raised beds, a practice that is both economical and practical in a warm climate.", "passive_voice_cultural_appositive_reason"),
            ("The single bed she had slept in throughout her childhood was replaced with a larger one when she started secondary school.", "relative_clause_time_passive_result"),
            ("Beds are designed to distribute the body's weight evenly so that muscles can fully relax during sleep and the body can repair itself through the night.", "passive_voice_purpose_health_extended"),
        ],
        "advanced": [
            ("The bed, which we spend roughly a third of our entire lives occupying, remains one of the most psychologically significant spaces in human existence — a private territory associated simultaneously with vulnerability, restoration, and the intimate architecture of our dreams.", "relative_clause_appositive_sophisticated_abstract"),
            ("Although the simple act of lying down seems effortless, the science of sleep has revealed that the quality of one's bed — its firmness, the breathability of its materials, and its thermal properties — exerts a measurable influence on the depth and restorative value of sleep.", "concessive_clause_passive_voice_scientific"),
            ("Having been awake since before dawn for four consecutive mornings, she finally fell into her bed not with the usual tentative lowering of a tired person but with the absolute, committed surrender of someone completely undone by exhaustion.", "perfect_participle_extended_contrasting_evocative"),
            ("Sleep researchers emphasise that the ritual of preparing for bed — cooling the room, dimming the lights, setting aside the day's concerns — is as important as the mattress itself in creating the physiological conditions necessary for deep, uninterrupted sleep.", "reported_speech_appositive_complex_academic"),
            ("She lay in bed in the early morning, that peculiar threshold hour when the night has not quite released its hold but the day has already begun to press its claims, and found herself grateful, with a fullness that surprised her, for the simple fact of warmth, stillness, and rest.", "complex_sentence_philosophical_time_abstract_emotional"),
        ],
    },
}
