from __future__ import annotations

SENTENCES_PART4 = {
    "dining table": {
        "beginner": [
            ("We eat at the table.", "simple present"),
            ("The table is big.", "simple present - adjective"),
            ("She set the table.", "simple past"),
            ("Put the food here.", "imperative"),
            ("We sat at the table.", "simple past"),
        ],
        "elementary": [
            ("Can you clear the dining table after dinner?", "modal - can"),
            ("There is a flower vase on the table.", "there is"),
            ("Is the table big enough for six people?", "yes/no question"),
            ("We could all fit around the large table.", "modal - could"),
            ("There are eight chairs around the dining table.", "there are"),
        ],
        "intermediate": [
            ("The dining table is bigger than the kitchen counter, so we always eat there.", "comparative + reason clause"),
            ("She wiped the table clean and then placed the plates carefully.", "compound sentence"),
            ("If the table is dirty, we should clean it before setting the food.", "first conditional"),
            ("The round dining table is more convenient than a rectangular one for our family.", "comparative adjective"),
            ("We eat breakfast at the table, but dinner is sometimes served in the living room.", "compound sentence - contrast"),
        ],
        "upper_intermediate": [
            ("The dining table, which was made from solid teak wood, had been in the family for generations.", "non-restrictive relative clause"),
            ("Meals are always served on the dining table, where the whole family gathers every evening.", "relative clause of place"),
            ("The old table was replaced by a modern one that could seat up to ten people comfortably.", "passive voice + relative clause"),
            ("Having a large dining table means that guests can always be welcomed for a shared meal.", "gerund subject + passive"),
            ("The dining table was polished every weekend so that it would remain in good condition.", "passive voice + purpose clause"),
        ],
        "advanced": [
            ("The dining table serves not merely as a surface for meals but as the symbolic heart of family communion and daily ritual.", "sophisticated metaphor + noun phrase complexity"),
            ("A well-maintained dining table around which the family gathers each evening fosters a sense of belonging that is difficult to replicate elsewhere.", "embedded relative clause + abstract noun"),
            ("Sociologists argue that the gradual disappearance of shared dining-table meals correlates with a weakening of intergenerational communication within households.", "academic register + complex noun phrase"),
            ("The craftsman who built the dining table insisted on using sustainably sourced timber, reflecting his deep commitment to environmental responsibility.", "relative clause + abstract noun phrase"),
            ("Though modest in appearance, the scratched and worn dining table bore witness to countless family celebrations, arguments, and reconciliations over the decades.", "concessive clause + extended noun phrase"),
        ],
    },
    "toilet": {
        "beginner": [
            ("Flush the toilet after use.", "imperative"),
            ("Keep the toilet clean.", "imperative - adjective"),
            ("The toilet is in the bathroom.", "simple present"),
            ("Wash your hands after using the toilet.", "imperative"),
            ("A clean toilet is important.", "simple present - adjective"),
        ],
        "elementary": [
            ("Can you please clean the toilet today?", "modal - polite request"),
            ("There is a toilet brush near the bowl.", "there is"),
            ("Is the toilet clean and ready to use?", "yes/no question"),
            ("We should always flush the toilet after use.", "modal - should"),
            ("There are proper hygiene rules for using the toilet.", "there are"),
        ],
        "intermediate": [
            ("If you clean the toilet regularly, it will stay hygienic and odour-free.", "first conditional"),
            ("The toilet is more important than any other bathroom fixture for maintaining good hygiene.", "comparative"),
            ("She scrubbed the toilet bowl and then disinfected the seat carefully.", "compound sentence"),
            ("Proper toilet hygiene is essential, and it should be taught to children from a young age.", "compound sentence - addition"),
            ("The toilet should be cleaned at least twice a week to prevent the spread of germs.", "modal passive + frequency"),
        ],
        "upper_intermediate": [
            ("The toilet, which is used by everyone in the household, must be cleaned and disinfected on a regular basis.", "non-restrictive relative clause + modal"),
            ("Good sanitation habits, including proper toilet use and handwashing, are essential for preventing the spread of disease.", "participle phrase + passive"),
            ("The new toilet that was installed last month uses significantly less water per flush than the old one.", "restrictive relative clause + comparative"),
            ("Children should be taught from an early age that maintaining toilet hygiene is a basic responsibility.", "modal + noun clause"),
            ("The toilet seat must always be lowered and the flush used after every visit as a matter of courtesy.", "passive voice + noun phrase"),
        ],
        "advanced": [
            ("Access to a clean, functioning toilet is widely recognised as a fundamental component of human dignity and public health infrastructure.", "passive voice + abstract noun phrase"),
            ("The seemingly mundane act of flushing the toilet and washing one's hands afterwards constitutes one of the most effective defences against waterborne illness.", "gerund subject + superlative"),
            ("Sanitation engineers argue that the design of modern toilet systems must balance water efficiency with hygienic effectiveness to meet sustainability goals.", "modal + infinitive + abstract noun"),
            ("Although often overlooked in discussions of household cleanliness, the toilet is arguably the fixture that most directly affects the health of the entire family.", "concessive clause + adverb of degree"),
            ("The introduction of low-flush toilet technology has significantly reduced domestic water consumption without compromising the standards of personal hygiene expected in modern homes.", "noun phrase + complex verb phrase"),
        ],
    },
    "tv": {
        "beginner": [
            ("I watch TV at night.", "simple present"),
            ("The TV is on.", "simple present"),
            ("She turned off the TV.", "simple past"),
            ("The TV is very big.", "simple present - adjective"),
            ("We watch the news on TV.", "simple present"),
        ],
        "elementary": [
            ("Can we watch a movie on TV tonight?", "modal - can, request"),
            ("There is a good programme on TV right now.", "there is"),
            ("Could you turn down the volume on the TV?", "modal - polite request"),
            ("Is there anything interesting on TV this evening?", "there is - question"),
            ("There are many channels available on our television.", "there are"),
        ],
        "intermediate": [
            ("If you sit too close to the TV, it could hurt your eyes over time.", "first conditional + modal"),
            ("The television in the living room is larger than the one in the bedroom.", "comparative"),
            ("She finished her homework first, and then she watched her favourite TV show.", "compound sentence - sequence"),
            ("Watching too much TV can affect your sleep, so it is better to switch it off before bedtime.", "causal compound sentence"),
            ("The TV show was exciting, but we had to stop watching because it was getting very late.", "compound sentence - contrast + reason"),
        ],
        "upper_intermediate": [
            ("The television programme that she had been looking forward to all week was finally broadcast last night.", "restrictive relative clause + past perfect"),
            ("Television, which was once considered a luxury item, is now found in nearly every household around the world.", "non-restrictive relative clause + contrast"),
            ("The documentary that was aired on TV last night examined the effects of social media on young people.", "restrictive relative clause + passive"),
            ("Children who watch educational programmes on television tend to develop stronger vocabulary and general knowledge skills.", "restrictive relative clause + tendency"),
            ("The smart television was connected to the internet so that the family could access streaming services directly.", "passive voice + purpose clause"),
        ],
        "advanced": [
            ("Critics contend that the proliferation of streaming services has fundamentally altered the way audiences engage with television content, eroding the shared cultural experience of live broadcast.", "complex noun phrase + gerund + abstract noun"),
            ("The transition from analogue to digital television broadcasting, though largely invisible to the average viewer, represented a significant technological milestone in mass communication.", "concessive clause + abstract noun phrase"),
            ("Television remains one of the most powerful instruments of cultural influence, shaping public opinion, reinforcing social norms, and occasionally challenging prevailing assumptions.", "parallel structure + abstract nouns"),
            ("Documentary filmmakers who produce content for television must navigate the tension between narrative accessibility and the intellectual rigour demanded by their subject matter.", "relative clause + abstract noun + gerund"),
            ("The evening news bulletin, which many families still watch together, serves as one of the few remaining rituals that unify household members around a shared information source.", "non-restrictive relative clause + relative clause"),
        ],
    },
    "laptop": {
        "beginner": [
            ("I use a laptop at school.", "simple present"),
            ("The laptop is on the desk.", "simple present"),
            ("She opened her laptop.", "simple past"),
            ("My laptop is white.", "simple present - adjective"),
            ("He types on the laptop.", "simple present"),
        ],
        "elementary": [
            ("Can I borrow your laptop for a moment?", "modal - can, request"),
            ("There is a laptop charger on the table.", "there is"),
            ("Could you help me connect the laptop to the internet?", "modal - polite request"),
            ("Is the laptop fully charged and ready to use?", "yes/no question"),
            ("There are many useful apps on my laptop.", "there are"),
        ],
        "intermediate": [
            ("If the laptop runs out of battery, you should plug it in immediately.", "first conditional + modal"),
            ("My new laptop is faster than the old desktop computer we had before.", "comparative"),
            ("She saved her assignment on the laptop and then sent it by email to her teacher.", "compound sentence - sequence"),
            ("The laptop is very convenient for studying, but you need to avoid distractions while using it.", "compound sentence - contrast"),
            ("If you drop the laptop, the screen might crack, so always carry it in a protective bag.", "first conditional + advice"),
        ],
        "upper_intermediate": [
            ("The laptop that she received as a birthday gift had enough memory to run all her design software smoothly.", "restrictive relative clause + result"),
            ("Laptops, which were once considered expensive professional tools, are now widely used by students at every level of education.", "non-restrictive relative clause + contrast"),
            ("The document that had been accidentally deleted was recovered using the laptop's backup software.", "restrictive relative clause + passive"),
            ("Students who regularly use laptops for note-taking often find it easier to organise and search through their study materials.", "restrictive relative clause + comparative"),
            ("The laptop was set up with parental controls so that younger children could only access age-appropriate content.", "passive voice + purpose clause"),
        ],
        "advanced": [
            ("The ubiquity of the laptop in contemporary educational settings has prompted researchers to investigate whether digital note-taking enhances or impedes deep comprehension of complex material.", "noun phrase + whether-clause + parallel structure"),
            ("A well-configured laptop equipped with productivity software can serve as an indispensable tool for students navigating the demands of modern academic life.", "participial phrase + abstract noun + gerund"),
            ("The rapid obsolescence of laptop hardware presents a significant environmental challenge, as discarded devices contribute substantially to the growing volume of electronic waste worldwide.", "noun phrase + causal clause + adverb"),
            ("Cybersecurity experts recommend that laptop users employ strong passwords and enable two-factor authentication to safeguard sensitive personal and academic data from unauthorised access.", "reporting verb + that-clause + purpose infinitive"),
            ("The portability and processing power of modern laptops have effectively dissolved the boundary between classroom and home as distinct spaces of learning.", "compound subject + abstract noun phrase"),
        ],
    },
    "mouse": {
        "beginner": [
            ("I use a mouse to click.", "simple present - purpose"),
            ("The mouse is on the desk.", "simple present"),
            ("She moved the mouse slowly.", "simple past"),
            ("The mouse has two buttons.", "simple present"),
            ("He clicked the mouse once.", "simple past"),
        ],
        "elementary": [
            ("Can you pass me the computer mouse?", "modal - can, request"),
            ("There is a wireless mouse next to the keyboard.", "there is"),
            ("Could you show me how to use the scroll wheel?", "modal - polite request"),
            ("Is this mouse compatible with my laptop?", "yes/no question"),
            ("There are different types of computer mice available.", "there are"),
        ],
        "intermediate": [
            ("If the mouse stops working, you should check whether the batteries need replacing.", "first conditional + whether-clause"),
            ("A wireless mouse is more convenient than a wired one because there are no cables to tangle.", "comparative + reason clause"),
            ("She plugged in the mouse and then adjusted the pointer speed in the settings.", "compound sentence - sequence"),
            ("The mouse cursor moved slowly at first, but it became faster after she cleaned the sensor.", "compound sentence - contrast + result"),
            ("If you use a mouse for long periods, you might experience wrist strain unless you take regular breaks.", "first conditional + unless-clause"),
        ],
        "upper_intermediate": [
            ("The ergonomic mouse that she ordered online was designed to reduce wrist strain during extended computer use.", "restrictive relative clause + passive"),
            ("Computer mice, which have evolved considerably since the early days of personal computing, now come in a variety of shapes and sizes.", "non-restrictive relative clause + contrast"),
            ("The mouse pointer can be customised in the system settings so that it is easier to see on the screen.", "passive voice + purpose clause"),
            ("Students who spend many hours using a computer mouse should learn about proper desk posture to avoid repetitive strain injuries.", "restrictive relative clause + modal"),
            ("The old wired mouse was replaced by a Bluetooth model that could be used up to ten metres from the computer.", "passive voice + restrictive relative clause"),
        ],
        "advanced": [
            ("The development of the optical mouse, which eliminated the need for a mechanical rolling ball, represented a pivotal moment in the evolution of human-computer interaction.", "non-restrictive relative clause + abstract noun phrase"),
            ("Ergonomists argue that the conventional flat mouse design is poorly suited to the natural resting position of the human hand and wrist, contributing to a rise in repetitive strain injuries.", "reporting verb + that-clause + gerund"),
            ("The precision afforded by a high-resolution mouse is particularly valued by graphic designers and digital artists who require pixel-level accuracy in their work.", "noun phrase + passive + restrictive relative clause"),
            ("As touchscreens and trackpads become increasingly prevalent, some technology analysts question whether the standalone computer mouse will retain its position as the primary pointing device.", "adverbial clause + whether-clause + future reference"),
            ("The seemingly simple act of clicking a mouse button triggers a complex sequence of hardware interrupts and software responses that most users never consciously consider.", "gerund subject + complex noun phrase + relative clause"),
        ],
    },
    "keyboard": {
        "beginner": [
            ("I type on the keyboard.", "simple present"),
            ("The keyboard is black.", "simple present - adjective"),
            ("She pressed the wrong key.", "simple past"),
            ("The keyboard has many keys.", "simple present"),
            ("He cleaned the keyboard today.", "simple past"),
        ],
        "elementary": [
            ("Can you type your name on the keyboard?", "modal - can, request"),
            ("There is a keyboard shortcut for copying text.", "there is"),
            ("Could you show me where the Enter key is?", "modal - polite request"),
            ("Is this keyboard wireless or does it need a cable?", "yes/no question - choice"),
            ("There are special function keys along the top of the keyboard.", "there are"),
        ],
        "intermediate": [
            ("If you learn to touch-type on the keyboard, you will be able to write much faster.", "first conditional + modal"),
            ("A mechanical keyboard is louder than a membrane keyboard, but many people prefer the tactile feedback.", "comparative + contrast"),
            ("She practised typing on the keyboard every day, and her speed improved greatly within a month.", "compound sentence - result"),
            ("The keyboard shortcut is faster than using the menu, so professionals often learn them carefully.", "comparative + reason"),
            ("If a key gets stuck, you should gently remove it and clean the area underneath.", "first conditional + modal"),
        ],
        "upper_intermediate": [
            ("The keyboard shortcut that she memorised helped her edit documents far more efficiently than before.", "restrictive relative clause + comparative"),
            ("Keyboards, which were originally designed for typewriters, have been adapted over decades to suit the needs of modern computing.", "non-restrictive relative clause + passive"),
            ("The wireless keyboard that was purchased for the classroom can connect to multiple devices simultaneously.", "restrictive relative clause + passive + adverb"),
            ("Students who practise keyboard skills from an early age tend to develop significantly faster typing speeds by secondary school.", "restrictive relative clause + tendency"),
            ("The keyboard layout used in most countries was designed in the nineteenth century and has remained largely unchanged ever since.", "passive voice + adverb"),
        ],
        "advanced": [
            ("The persistence of the QWERTY keyboard layout, despite decades of research suggesting that alternative arrangements could improve typing efficiency, illustrates how deeply entrenched design conventions can resist change.", "noun phrase + concessive clause + abstract noun"),
            ("Typists who invest time in mastering the full keyboard, including rarely used symbols and shortcut combinations, gain a measurable productivity advantage in document-heavy professional environments.", "restrictive relative clause + gerund + noun phrase"),
            ("The shift from physical keyboards to on-screen touch keyboards in mobile devices has reignited debate among ergonomists about the long-term effects on writing speed, accuracy, and musculoskeletal health.", "noun phrase + passive + prepositional phrase"),
            ("A well-designed keyboard, responsive to the natural rhythm and pressure of human fingers, can transform the act of writing from a laborious mechanical process into a fluid and almost unconscious extension of thought.", "participial phrase + abstract noun"),
            ("Linguists studying keyboard-mediated communication have noted that the physical constraints of typing have subtly shaped the syntactic and lexical choices that writers make in informal digital discourse.", "participial phrase + that-clause + abstract noun"),
        ],
    },
    "cell phone": {
        "beginner": [
            ("I have a cell phone.", "simple present"),
            ("Her cell phone is pink.", "simple present - adjective"),
            ("He called me on my phone.", "simple past"),
            ("The phone is charging now.", "present continuous"),
            ("She dropped her cell phone.", "simple past"),
        ],
        "elementary": [
            ("Can you call me on my cell phone later?", "modal - can, request"),
            ("There is a new message on your cell phone.", "there is"),
            ("Could you lower the volume on your phone in class?", "modal - polite request"),
            ("Is your cell phone battery fully charged?", "yes/no question"),
            ("There are many helpful apps on a cell phone.", "there are"),
        ],
        "intermediate": [
            ("If you use your cell phone too much at night, it will disturb your sleep.", "first conditional"),
            ("Her new cell phone has a better camera than her old one.", "comparative"),
            ("He put his cell phone on silent and then focused entirely on his studies.", "compound sentence - sequence"),
            ("Cell phones are very useful for communication, but they can be a distraction in class.", "compound sentence - contrast"),
            ("If you forget your cell phone at home, you might feel anxious until you get it back.", "first conditional + modal"),
        ],
        "upper_intermediate": [
            ("The cell phone that she had been using for three years finally stopped working after she dropped it in water.", "restrictive relative clause + past perfect"),
            ("Cell phones, which were once simple calling devices, now function as portable computers with access to the entire internet.", "non-restrictive relative clause + contrast"),
            ("The mobile phone was confiscated by the teacher because it had been used during an examination.", "passive voice + reason clause + past perfect"),
            ("Students who use their cell phones responsibly in school can benefit from having an instant research tool at their fingertips.", "restrictive relative clause + modal"),
            ("Screen time on cell phones is now being monitored by many parents using built-in parental control applications.", "passive voice - present continuous"),
        ],
        "advanced": [
            ("The smartphone, which has rendered the standalone camera, alarm clock, dictionary, and map largely redundant, represents one of the most consequential technological convergences of the early twenty-first century.", "non-restrictive relative clause + noun phrase + abstract noun"),
            ("Psychologists have raised concerns that the constant availability of cell phones is undermining adolescents' capacity for sustained attention and deep, uninterrupted thought.", "reporting verb + that-clause + gerund + abstract noun"),
            ("The dependence of modern social life on cell phone connectivity raises important questions about digital equity, given that reliable access remains unevenly distributed across economic groups.", "noun phrase + abstract noun + concessive clause"),
            ("Cell phone etiquette, a concept that barely existed two decades ago, has now become a subject of serious discussion in workplaces, schools, and even family homes.", "appositive phrase + contrast + abstract noun"),
            ("The electromagnetic radiation emitted by cell phones, though widely studied, has not been conclusively linked to adverse health outcomes in the quantities typically encountered during normal use.", "participial phrase + concessive clause + passive"),
        ],
    },
    "microwave": {
        "beginner": [
            ("I heat food in the microwave.", "simple present"),
            ("The microwave is in the kitchen.", "simple present"),
            ("She warmed the soup in it.", "simple past"),
            ("The microwave beeped loudly.", "simple past"),
            ("He set the timer on the microwave.", "simple past"),
        ],
        "elementary": [
            ("Can you heat up the rice in the microwave?", "modal - can, request"),
            ("There is leftover food in the microwave.", "there is"),
            ("Could you show me how to use the microwave timer?", "modal - polite request"),
            ("Is the microwave safe for heating liquids?", "yes/no question"),
            ("There are several heating settings on this microwave.", "there are"),
        ],
        "intermediate": [
            ("If you put metal inside a microwave, it will create dangerous sparks.", "first conditional - warning"),
            ("Reheating food in a microwave is much quicker than using a traditional oven.", "comparative"),
            ("She covered the bowl with a lid and then placed it carefully inside the microwave.", "compound sentence - sequence"),
            ("The microwave is very convenient for busy mornings, but it cannot brown or crisp food the way an oven can.", "compound sentence - contrast"),
            ("If you do not stir the food halfway through heating, some parts might remain cold in the centre.", "first conditional + modal"),
        ],
        "upper_intermediate": [
            ("The microwave that was installed in the school canteen broke down after being used continuously for several hours.", "restrictive relative clause + passive + adverb"),
            ("Microwaves, which work by exciting water molecules in food, can heat a meal in a fraction of the time needed by a conventional oven.", "non-restrictive relative clause + comparative"),
            ("Certain types of plastic containers should never be placed inside a microwave because they can release harmful chemicals when heated.", "modal passive + causal clause"),
            ("Food that has been reheated in a microwave should be stirred and checked before eating to ensure it is heated evenly throughout.", "restrictive relative clause + passive + purpose infinitive"),
            ("The microwave was introduced to domestic kitchens in the 1970s and has since become one of the most commonly used appliances in the world.", "passive voice + time clause"),
        ],
        "advanced": [
            ("The microwave oven, initially developed as a byproduct of radar technology, exemplifies how military research investments can yield transformative civilian applications with profound implications for everyday life.", "participial phrase + abstract noun + noun phrase"),
            ("Nutritionists debate whether microwave heating preserves more vitamins and minerals in vegetables than conventional boiling does, with emerging evidence suggesting it may in fact be the superior method.", "whether-clause + comparative + noun phrase"),
            ("The convenience offered by the microwave has been credited with contributing to the decline of from-scratch cooking and the concurrent rise of processed, ready-to-heat food culture in industrialised societies.", "passive voice + gerund + noun phrase"),
            ("Contrary to widespread popular belief, microwave ovens do not make food radioactive; they merely agitate water molecules using non-ionising radiation that dissipates entirely once the appliance is switched off.", "concessive phrase + contrast + participle"),
            ("The microwave's penetration into virtually every domestic kitchen over the past fifty years reflects a broader cultural shift toward time efficiency as the paramount value in household food preparation.", "noun phrase + abstract noun + prepositional phrase"),
        ],
    },
    "oven": {
        "beginner": [
            ("She baked bread in the oven.", "simple past"),
            ("The oven is very hot.", "simple present - adjective"),
            ("He turned on the oven.", "simple past"),
            ("We cook pizza in the oven.", "simple present"),
            ("The oven beeped when done.", "simple past"),
        ],
        "elementary": [
            ("Can you preheat the oven to 180 degrees?", "modal - can, request"),
            ("There is a tray of biscuits in the oven.", "there is"),
            ("Could you check if the oven is still on?", "modal - polite request"),
            ("Is the oven hot enough for baking the cake?", "yes/no question"),
            ("There are two shelves inside this oven.", "there are"),
        ],
        "intermediate": [
            ("If you do not preheat the oven, the cake will not rise properly.", "first conditional"),
            ("Baking in a fan-assisted oven is more efficient than using a conventional one because heat is distributed evenly.", "comparative + reason clause"),
            ("She greased the baking tin and then placed it inside the preheated oven.", "compound sentence - sequence"),
            ("The oven is essential for making bread, but you need to monitor the temperature carefully.", "compound sentence - condition"),
            ("If you open the oven door too often, the temperature will drop and your cake might not cook evenly.", "first conditional + modal"),
        ],
        "upper_intermediate": [
            ("The dish that had been slow-cooked in the oven for three hours was tender and rich with flavour.", "restrictive relative clause + past perfect"),
            ("Ovens, which range from basic gas models to sophisticated convection systems, are indispensable appliances in both home and professional kitchens.", "non-restrictive relative clause + contrast"),
            ("The oven temperature should be checked with a thermometer periodically, as built-in gauges are often slightly inaccurate.", "modal passive + causal clause"),
            ("Children who are learning to bake should always be supervised by an adult when using the oven.", "restrictive relative clause + modal passive"),
            ("The meal was placed in the oven at a low temperature so that it would cook slowly without drying out.", "passive voice + purpose clause"),
        ],
        "advanced": [
            ("The wood-fired oven, which has been used in various forms for millennia, has experienced a remarkable resurgence in artisanal bakeries seeking to recreate the complex crust and flavour profiles impossible to achieve through modern methods.", "non-restrictive relative clause + passive + gerund"),
            ("Culinary scientists have demonstrated that the distribution of heat within a conventional oven is far less uniform than most home cooks assume, necessitating strategic rack positioning and rotation of dishes.", "reporting verb + that-clause + gerund + noun phrase"),
            ("The introduction of self-cleaning oven technology, which uses extremely high temperatures to incinerate food residue, eliminated one of the most laborious tasks in kitchen maintenance.", "non-restrictive relative clause + passive"),
            ("Professional bakers argue that mastery of oven temperament — understanding its hot spots, quirks, and response to humidity — is as important as any recipe in determining the quality of the final product.", "reporting verb + gerund + abstract noun + comparative"),
            ("The oven's transformation from an open hearth requiring constant tending to a sealed, thermostatically controlled appliance represents one of the most significant improvements in domestic cooking technology across the modern era.", "noun phrase + participial phrase + abstract noun"),
        ],
    },
    "toaster": {
        "beginner": [
            ("I make toast every morning.", "simple present - frequency"),
            ("The toaster is on the counter.", "simple present"),
            ("She put bread in the toaster.", "simple past"),
            ("The toast popped up quickly.", "simple past"),
            ("He likes crispy toast.", "simple present - preference"),
        ],
        "elementary": [
            ("Can you make some toast for breakfast?", "modal - can, request"),
            ("There is a toaster on the kitchen counter.", "there is"),
            ("Could you set the toaster to a medium setting?", "modal - polite request"),
            ("Is the toaster plugged in and ready to use?", "yes/no question"),
            ("There are crumbs collected in the toaster tray.", "there are"),
        ],
        "intermediate": [
            ("If you leave the bread in the toaster too long, it will burn and smell unpleasant.", "first conditional - warning"),
            ("A two-slice toaster is smaller than a four-slice model, but it takes up less space on the counter.", "comparative + contrast"),
            ("He cleaned out the crumb tray and then toasted two slices of wholemeal bread.", "compound sentence - sequence"),
            ("The toaster is the quickest way to prepare breakfast, but you should never leave it unattended.", "compound sentence - advice"),
            ("If the toaster lever gets stuck, you should unplug it before attempting to fix it safely.", "first conditional + modal"),
        ],
        "upper_intermediate": [
            ("The toaster that her mother had bought decades ago still worked perfectly, a testament to older appliances being built to last.", "restrictive relative clause + abstract noun"),
            ("Toasters, which use electrical resistance to generate heat, can reach very high temperatures and should always be kept away from water.", "non-restrictive relative clause + modal passive"),
            ("The bread that was left in the toaster for too long set off the kitchen smoke alarm.", "restrictive relative clause + past perfect"),
            ("People who eat breakfast regularly often rely on a toaster as their primary morning cooking appliance for its speed and simplicity.", "restrictive relative clause + abstract noun"),
            ("The crumb tray must be emptied regularly so that accumulated debris does not become a fire hazard.", "modal passive + purpose clause"),
        ],
        "advanced": [
            ("The humble toaster, often overlooked in discussions of kitchen technology, has undergone surprisingly sophisticated engineering refinements since its first commercial introduction in the early twentieth century.", "appositive phrase + passive + time clause"),
            ("Product designers working on modern toasters must balance aesthetic minimalism with functional requirements such as even browning, variable heat settings, and safe automatic shut-off mechanisms.", "participial phrase + abstract noun + noun phrase"),
            ("The widespread adoption of the electric toaster in mid-twentieth-century households symbolised the broader democratisation of convenient kitchen appliances previously accessible only to the affluent.", "noun phrase + passive + adverb"),
            ("Nutritional debates around toasting bread — specifically, whether the process significantly alters glycaemic response — illustrate how even the most routine culinary acts attract scientific scrutiny.", "appositive phrase + whether-clause + abstract noun"),
            ("The toaster's deceptive simplicity belies the precise engineering required to deliver consistent, controllable heat to a thin slice of bread in a matter of seconds without posing a fire risk.", "noun phrase + abstract noun + purpose infinitive"),
        ],
    },
    "sink": {
        "beginner": [
            ("I wash my hands in the sink.", "simple present"),
            ("The sink is full of dishes.", "simple present"),
            ("She rinsed the cup in the sink.", "simple past"),
            ("Turn off the tap after use.", "imperative"),
            ("The sink is in the kitchen.", "simple present"),
        ],
        "elementary": [
            ("Can you wash the vegetables in the sink?", "modal - can, request"),
            ("There is a pile of dirty dishes in the sink.", "there is"),
            ("Could you unblock the sink drain before tonight?", "modal - polite request"),
            ("Is the sink drain blocked again this week?", "yes/no question"),
            ("There are two taps on this kitchen sink.", "there are"),
        ],
        "intermediate": [
            ("If you let water run unnecessarily in the sink, you will waste a great deal every month.", "first conditional - environment"),
            ("The kitchen sink is deeper than the bathroom basin, making it easier to wash large pots.", "comparative + result"),
            ("She soaked the dishes in the sink and then scrubbed each one with a sponge.", "compound sentence - sequence"),
            ("Always rinse vegetables thoroughly in the sink before cooking, because residual soil can carry bacteria.", "imperative + reason clause"),
            ("If the sink tap drips at night, the constant sound will make it difficult to sleep.", "first conditional"),
        ],
        "upper_intermediate": [
            ("The kitchen sink, which had been leaking for several weeks, was finally repaired by a plumber who found a crack in the pipe.", "non-restrictive relative clause + passive + restrictive relative clause"),
            ("Water that is wasted by leaving the sink tap running unnecessarily contributes to the strain on urban water supply systems.", "restrictive relative clause + noun phrase"),
            ("The new sink that was fitted in the laboratory has a built-in filtration system to ensure the water is safe for experiments.", "restrictive relative clause + passive + purpose infinitive"),
            ("Dishes should always be rinsed in the sink before being placed in the dishwasher to prevent food from blocking the filter.", "modal passive + gerund + purpose infinitive"),
            ("The habit of washing hands thoroughly in the sink with soap remains one of the simplest and most effective methods of preventing the spread of infection.", "noun phrase + superlative + gerund"),
        ],
        "advanced": [
            ("The kitchen sink occupies a curiously central position in domestic life, functioning simultaneously as a site of food preparation, hygiene, and the less glamorous but essential labour of cleaning up after meals.", "adverb + noun phrase + parallel structure"),
            ("Plumbers advise that grease should never be poured down a kitchen sink, as it solidifies in the pipes over time and eventually causes blockages that are both costly and time-consuming to clear.", "reporting verb + that-clause + causal clause + relative clause"),
            ("The ergonomic height of a sink, a detail rarely considered by homeowners until it causes chronic back discomfort, has become a subject of increasing interest in kitchen design research.", "appositive clause + passive + abstract noun"),
            ("The per-capita volume of water wasted through dripping taps and running sinks in developed nations represents a staggering inefficiency that sustainable plumbing technology is only beginning to address.", "noun phrase + abstract noun + relative clause"),
            ("In many cultures, the act of gathering around a sink to wash dishes communally after a meal has served as a setting for informal conversation, dispute resolution, and the quiet transmission of domestic knowledge between generations.", "gerund subject + abstract noun + parallel structure"),
        ],
    },
    "refrigerator": {
        "beginner": [
            ("We keep food in the refrigerator.", "simple present"),
            ("The refrigerator is very cold.", "simple present - adjective"),
            ("She opened the refrigerator door.", "simple past"),
            ("Put the milk in the fridge.", "imperative"),
            ("The fridge is full of food.", "simple present"),
        ],
        "elementary": [
            ("Can you check if there is juice in the refrigerator?", "modal + there is"),
            ("There is a bowl of leftover rice in the fridge.", "there is"),
            ("Could you close the refrigerator door properly please?", "modal - polite request"),
            ("Is the refrigerator cold enough to keep the vegetables fresh?", "yes/no question"),
            ("There are different compartments for storing food in the fridge.", "there are"),
        ],
        "intermediate": [
            ("If you leave the refrigerator door open for too long, the temperature inside will rise and food will spoil faster.", "first conditional"),
            ("The new refrigerator is more energy-efficient than the old one, so our electricity bill should decrease.", "comparative + result"),
            ("She organised all the food in the refrigerator and then checked which items were close to their expiry dates.", "compound sentence - sequence"),
            ("Raw meat should always be stored on the bottom shelf of the refrigerator so that it cannot drip onto other food.", "modal passive + purpose clause"),
            ("If the refrigerator makes a strange humming noise, you should call a technician to inspect it.", "first conditional + modal"),
        ],
        "upper_intermediate": [
            ("The refrigerator that the family had been using for fifteen years finally stopped cooling efficiently and needed to be replaced.", "restrictive relative clause + past perfect + passive"),
            ("Modern refrigerators, which often include smart temperature monitoring systems, have become considerably more sophisticated than the simple cooling boxes of earlier decades.", "non-restrictive relative clause + comparative"),
            ("Perishable food that has been stored improperly in the refrigerator can become a source of foodborne illness if consumed after its safe period.", "restrictive relative clause + passive + conditional"),
            ("The refrigerator was reorganised so that older items were placed at the front, making it easier to use them before they expired.", "passive voice + purpose clause + gerund"),
            ("Children who are taught early about proper food storage in the refrigerator tend to develop healthier kitchen habits as they grow older.", "restrictive relative clause + tendency"),
        ],
        "advanced": [
            ("The domestic refrigerator, which fundamentally altered the rhythm of food shopping and meal planning in the twentieth century, remains one of the most energy-consuming appliances in the average household.", "non-restrictive relative clause + superlative"),
            ("Food safety authorities recommend that refrigerator temperatures be maintained consistently below four degrees Celsius to inhibit the growth of pathogens that cause foodborne illness.", "reporting verb + that-clause + purpose infinitive + relative clause"),
            ("The environmental cost of manufacturing and running a refrigerator over its operational lifespan has prompted appliance engineers to pursue more energy-efficient compressor and insulation technologies.", "noun phrase + passive + purpose infinitive"),
            ("The social historian's observation that the refrigerator democratised access to fresh food by reducing dependence on daily market visits captures only part of its broader transformation of domestic routine.", "noun clause + gerund + abstract noun"),
            ("As global supply chains become increasingly fragile, food security analysts have renewed their interest in cold chain infrastructure — from industrial cold storage down to the household refrigerator — as a critical buffer against disruption.", "adverbial clause + passive + prepositional phrase"),
        ],
    },
    "book": {
        "beginner": [
            ("I read a book today.", "simple past"),
            ("The book is on the shelf.", "simple present"),
            ("She likes reading books.", "simple present - preference + gerund"),
            ("He found a good book.", "simple past"),
            ("This book is very interesting.", "simple present - adjective"),
        ],
        "elementary": [
            ("Can you recommend a good book for me to read?", "modal - can, request"),
            ("There is a bookmark on page fifty.", "there is"),
            ("Could you lend me that science fiction book?", "modal - polite request"),
            ("Is this book available in the school library?", "yes/no question"),
            ("There are hundreds of books on those shelves.", "there are"),
        ],
        "intermediate": [
            ("If you read books regularly, you will develop a much stronger vocabulary over time.", "first conditional"),
            ("This novel is more gripping than the last book I read because the characters feel very real.", "comparative + reason clause"),
            ("She finished the chapter and then placed a bookmark carefully between the pages.", "compound sentence - sequence"),
            ("Reading books improves concentration, and it also helps you understand other people's perspectives.", "compound sentence - addition"),
            ("If the library does not have the book you want, you can ask the librarian to order it.", "first conditional + modal"),
        ],
        "upper_intermediate": [
            ("The novel that she had borrowed from the library was so engaging that she stayed up until midnight to finish it.", "restrictive relative clause + past perfect + result"),
            ("Books, which have served as the primary vehicle for preserving human knowledge across centuries, are now facing competition from digital media.", "non-restrictive relative clause + passive"),
            ("The book that was recommended by her English teacher turned out to be one of the most thought-provoking she had ever read.", "restrictive relative clause + passive + superlative"),
            ("Students who read widely outside their school curriculum tend to perform significantly better in comprehension and essay-writing assessments.", "restrictive relative clause + tendency"),
            ("The old book was handled carefully so that its fragile pages would not be damaged or torn.", "passive voice + purpose clause"),
        ],
        "advanced": [
            ("The printed book, despite repeated predictions of its obsolescence in the digital age, has demonstrated remarkable resilience, with physical book sales continuing to hold steady against the expansion of e-readers and audiobooks.", "concessive clause + abstract noun + participial phrase"),
            ("Cognitive scientists have found that reading a physical book promotes deeper comprehension and better retention of narrative details than reading the same text on a screen, a difference attributed to tactile and spatial memory cues.", "reporting verb + that-clause + comparative + passive"),
            ("The cultural authority of the book as an object — quite apart from its contents — continues to shape how knowledge is validated, how authors are perceived, and how intellectual achievement is measured in academic and professional circles.", "noun phrase + parallel structure + abstract noun"),
            ("A single book, placed in the hands of a curious child at the right moment, has the capacity to redirect an entire life trajectory in ways that no algorithm-driven content recommendation system can reliably replicate.", "participial phrase + noun phrase + relative clause"),
            ("The history of banned books reveals how consistently those in power have recognised the transformative potential of the written word to challenge orthodoxy, inspire dissent, and mobilise collective imagination toward alternative futures.", "noun clause + abstract noun + parallel infinitives"),
        ],
    },
    "clock": {
        "beginner": [
            ("The clock is on the wall.", "simple present"),
            ("It is three o'clock now.", "simple present - time"),
            ("She looked at the clock.", "simple past"),
            ("The clock makes a ticking sound.", "simple present"),
            ("He set the alarm clock.", "simple past"),
        ],
        "elementary": [
            ("Can you tell me what time the clock shows?", "modal - can, request"),
            ("There is a large clock above the classroom door.", "there is"),
            ("Could you wind up the old clock on the shelf?", "modal - polite request"),
            ("Is the clock showing the correct time today?", "yes/no question"),
            ("There are both analogue and digital clocks in our house.", "there are"),
        ],
        "intermediate": [
            ("If the clock is slow, you might arrive late to your appointments without realising it.", "first conditional + gerund"),
            ("The analogue clock is harder to read at a glance than a digital one for some people.", "comparative"),
            ("She noticed the clock was wrong and then adjusted it to the correct time immediately.", "compound sentence - sequence"),
            ("The classroom clock stopped during the exam, so no one was sure how much time remained.", "compound sentence - result"),
            ("If you do not check the clock regularly, you may lose track of time during long study sessions.", "first conditional + modal"),
        ],
        "upper_intermediate": [
            ("The antique clock that hung in the hallway had not been wound for years and had stopped at half past two.", "restrictive relative clause + past perfect"),
            ("Clocks, which have been used to measure time for thousands of years, have evolved from sundials and water clocks to atomic precision instruments.", "non-restrictive relative clause + passive"),
            ("The clock that was donated to the school was engraved with the names of all students who had graduated that year.", "restrictive relative clause + passive"),
            ("People who struggle to manage their time effectively are often advised to place a visible clock on their desk as a simple reminder.", "restrictive relative clause + passive"),
            ("The clock on the wall was adjusted every spring and autumn to account for the changes in daylight saving time.", "passive voice + purpose infinitive"),
        ],
        "advanced": [
            ("The invention of the mechanical clock in medieval Europe did not merely provide a means of measuring time; it fundamentally restructured human society around the concept of scheduled, segmented activity.", "negative inversion + abstract noun + noun phrase"),
            ("Philosophers of time have long debated whether the clock measures an objective, pre-existing reality or whether it actively constructs our experience of duration by imposing artificial divisions upon what might otherwise be perceived as continuous flow.", "reporting verb + whether-clause + parallel structure"),
            ("The atomic clock, accurate to within one second over millions of years, underpins the global positioning systems, financial transaction networks, and telecommunications infrastructure upon which modern civilisation depends.", "appositive phrase + relative clause + noun phrase"),
            ("The metaphor of the clock as a symbol of mortality — each tick marking the irreversible passage of time — has pervaded Western literature, art, and philosophy from at least the Renaissance onwards.", "appositive phrase + relative clause + passive"),
            ("Our contemporary obsession with productivity and time management might be understood as a cultural pathology born of the industrial revolution's insistence that every hour be accounted for and every moment optimised for output.", "noun phrase + passive + that-clause"),
        ],
    },
    "vase": {
        "beginner": [
            ("There is a vase on the table.", "there is"),
            ("The vase is tall and blue.", "simple present - adjectives"),
            ("She put flowers in the vase.", "simple past"),
            ("The vase broke on the floor.", "simple past"),
            ("He filled the vase with water.", "simple past"),
        ],
        "elementary": [
            ("Can you put fresh flowers in the vase?", "modal - can, request"),
            ("There is a beautiful vase near the window.", "there is"),
            ("Could you move the vase away from the edge?", "modal - polite request"),
            ("Is the vase made of glass or ceramic?", "yes/no question - material"),
            ("There are several vases displayed on the shelf.", "there are"),
        ],
        "intermediate": [
            ("If you put flowers in a clean vase with fresh water, they will last much longer.", "first conditional"),
            ("The tall ceramic vase is more elegant than the small plastic one on the windowsill.", "comparative"),
            ("She trimmed the flower stems and then arranged them carefully inside the crystal vase.", "compound sentence - sequence"),
            ("The vase is a beautiful decoration, but it needs to be kept away from the edge of the shelf.", "compound sentence - advice"),
            ("If the vase is knocked over, it will shatter because it is made of thin glass.", "first conditional + reason clause"),
        ],
        "upper_intermediate": [
            ("The porcelain vase that her grandmother had brought from China was carefully wrapped and stored in a padded box.", "restrictive relative clause + passive"),
            ("Vases, which have served both functional and decorative purposes since ancient civilisations, continue to be treasured as art objects in modern homes.", "non-restrictive relative clause + passive"),
            ("The vase that was displayed in the museum had been excavated from a Bronze Age settlement and was estimated to be over three thousand years old.", "restrictive relative clause + passive + past perfect"),
            ("Flowers that are placed in a vase with a small amount of sugar dissolved in the water tend to remain fresh for several days longer.", "restrictive relative clause + passive"),
            ("The antique vase was inspected by an expert who confirmed that it was a genuine example of Ming dynasty porcelain.", "passive voice + restrictive relative clause"),
        ],
        "advanced": [
            ("The ancient Greek vase, painted with scenes of athletic competition and mythological narrative, serves today as an irreplaceable primary source for historians seeking to reconstruct the visual culture of the classical world.", "participial phrase + abstract noun + relative clause"),
            ("The paradox of the decorative vase lies in its dual identity as both a functional vessel designed to contain water and a purely aesthetic object whose value is tied to its visual form rather than its utility.", "noun phrase + parallel structure + relative clause"),
            ("Ceramic vases produced in Tang dynasty China were carried along the Silk Road and found their way into courts and collections across Central Asia, Persia, and the Byzantine Empire, testifying to the remarkable reach of early global trade.", "passive voice + complex prepositional phrase + gerund"),
            ("The still-life painter's recurring choice of the vase as a subject reflects not merely its visual attractiveness but its capacity to serve as a meditation on transience, beauty, and the relationship between the natural and the crafted object.", "noun clause + parallel structure + abstract noun"),
            ("Archaeologists prize intact ancient vases not only for the decorative programmes painted on their surfaces but for the organic residues trapped within them, which can reveal detailed information about the liquids they once held.", "adverb + parallel structure + relative clause"),
        ],
    },
    "scissors": {
        "beginner": [
            ("She cut the paper with scissors.", "simple past"),
            ("The scissors are on the desk.", "simple present"),
            ("He used scissors in art class.", "simple past"),
            ("These scissors are very sharp.", "simple present - adjective"),
            ("Put the scissors away safely.", "imperative"),
        ],
        "elementary": [
            ("Can you pass me the scissors from the drawer?", "modal - can, request"),
            ("There is a pair of scissors on the craft table.", "there is"),
            ("Could you use the scissors carefully when cutting fabric?", "modal - polite request"),
            ("Are these scissors sharp enough to cut through thick card?", "yes/no question"),
            ("There are craft scissors and kitchen scissors in the top drawer.", "there are"),
        ],
        "intermediate": [
            ("If you use scissors incorrectly, you might cut yourself, so always be careful near the blades.", "first conditional + modal + advice"),
            ("These fabric scissors are much sharper than the ordinary ones we use for paper crafts.", "comparative"),
            ("She measured the ribbon first and then cut it to the right length with her scissors.", "compound sentence - sequence"),
            ("Scissors are essential for many craft projects, but they should always be stored with the blades closed.", "compound sentence - safety"),
            ("If children use scissors unsupervised, there is a risk of injury, so adults should always be nearby.", "first conditional + noun phrase + reason"),
        ],
        "upper_intermediate": [
            ("The scissors that were used in the surgery were sterilised before each procedure to prevent the risk of infection.", "restrictive relative clause + passive + purpose infinitive"),
            ("Scissors, which consist of two crossed pivoting blades, are one of the oldest and most widely used cutting tools in human history.", "non-restrictive relative clause + superlative"),
            ("Left-handed scissors, which are designed so that the top blade is on the left, can make cutting significantly easier for left-handed users.", "non-restrictive relative clause + comparative"),
            ("Children who are learning to use scissors for the first time should be given safety scissors with rounded tips.", "restrictive relative clause + modal passive"),
            ("The scissors were misplaced after the art lesson, and the whole class spent several minutes searching for them.", "passive voice + compound sentence"),
        ],
        "advanced": [
            ("The scissors, deceptively simple in design, represent a sophisticated mechanical solution to the challenge of controlled cutting, exploiting the principle of the lever to concentrate force precisely along the line of the blades.", "appositive phrase + noun phrase + gerund"),
            ("Surgical scissors, engineered to exacting tolerances from surgical-grade stainless steel, are among the most precisely manufactured instruments in modern medicine, where a poorly aligned blade can have serious consequences.", "participial phrase + superlative + relative clause"),
            ("The idiom 'rock, paper, scissors' has transcended its origins as a children's decision-making game to become a subject of mathematical analysis in game theory, illustrating the elegant properties of non-transitive relationships.", "noun clause + passive + abstract noun"),
            ("The development of micro-scissors capable of operating at the cellular level has opened new frontiers in minimally invasive surgery, enabling procedures that would have been technically impossible a generation ago.", "noun phrase + relative clause + gerund"),
            ("Textile historians note that the introduction of high-quality steel scissors into domestic sewing practice during the industrial revolution significantly accelerated the pace of home dressmaking and altered the economics of clothing production.", "reporting verb + that-clause + noun phrase + abstract noun"),
        ],
    },
    "teddy bear": {
        "beginner": [
            ("She hugs her teddy bear every night.", "simple present - frequency"),
            ("The teddy bear is soft and brown.", "simple present - adjectives"),
            ("He lost his teddy bear at school.", "simple past"),
            ("My teddy bear has big eyes.", "simple present"),
            ("She named her teddy bear Max.", "simple past"),
        ],
        "elementary": [
            ("Can you find my teddy bear under the bed?", "modal - can, request"),
            ("There is a small teddy bear on her pillow.", "there is"),
            ("Could you wash the teddy bear because it is dirty?", "modal - polite request + reason"),
            ("Is your teddy bear made of cotton or synthetic fabric?", "yes/no question - material"),
            ("There are several teddy bears displayed on the shelf in her room.", "there are"),
        ],
        "intermediate": [
            ("If you wash a teddy bear too many times, its fur might become rough and lose its softness.", "first conditional"),
            ("Her old teddy bear is much more worn than the new one, but she still loves it the most.", "comparative + contrast"),
            ("She packed her favourite teddy bear in her bag and then felt a little less nervous about the trip.", "compound sentence - emotion"),
            ("A teddy bear can be a great comfort to young children, especially when they feel scared or sad.", "modal + condition"),
            ("If a child loses a beloved teddy bear, it can feel like losing a close friend, which is perfectly normal.", "first conditional + simile"),
        ],
        "upper_intermediate": [
            ("The teddy bear that she had been given as a baby was still sitting on her bookshelf, worn but much-loved.", "restrictive relative clause + past perfect + contrast"),
            ("Teddy bears, which were first produced in the early 1900s and named after President Theodore Roosevelt, remain among the most popular childhood toys worldwide.", "non-restrictive relative clause + passive"),
            ("The handmade teddy bear that her grandmother had sewn from old fabric became one of her most treasured possessions.", "restrictive relative clause + past perfect"),
            ("Children who form strong attachments to comfort objects such as teddy bears often use them as a way to manage anxiety in unfamiliar situations.", "restrictive relative clause + purpose infinitive"),
            ("The worn teddy bear was repaired by a specialist so that it could be preserved as a meaningful family keepsake.", "passive voice + purpose clause"),
        ],
        "advanced": [
            ("The teddy bear occupies a unique position in the landscape of childhood objects, functioning as a transitional attachment figure that bridges the internal emotional world of the child with the external, unpredictable environment.", "noun phrase + abstract noun + relative clause"),
            ("Child psychologists have observed that the intensity of a child's attachment to a teddy bear or similar comfort object bears little relationship to the object's material value but a great deal to the emotional associations it has accumulated.", "reporting verb + that-clause + contrast + abstract noun"),
            ("The global market for collectible and designer teddy bears, catering to adult enthusiasts rather than children, illustrates how objects rooted in childhood can be recontextualised as luxury commodities and cultural artefacts.", "noun phrase + participial phrase + abstract noun"),
            ("The simple, undemanding presence of a teddy bear, incapable of judgement or abandonment, may explain its enduring appeal not only to young children navigating a confusing world but also to adults seeking an uncomplicated symbol of comfort.", "noun phrase + participial phrase + parallel structure"),
            ("Textile conservators who restore antique teddy bears describe their work as a form of emotional archaeology, reconstructing not merely the physical object but the layers of personal history and affection embedded within its seams.", "restrictive relative clause + abstract noun + gerund"),
        ],
    },
    "hair drier": {
        "beginner": [
            ("She dries her hair every morning.", "simple present - frequency"),
            ("The hair drier is in the bathroom.", "simple present"),
            ("He used the hair drier after swimming.", "simple past"),
            ("The hair drier is very loud.", "simple present - adjective"),
            ("She plugged in the hair drier.", "simple past"),
        ],
        "elementary": [
            ("Can I use your hair drier after my shower?", "modal - can, request"),
            ("There is a hair drier in the top bathroom cabinet.", "there is"),
            ("Could you lend me your hair drier for a few minutes?", "modal - polite request"),
            ("Is this hair drier suitable for thick and curly hair?", "yes/no question"),
            ("There are different heat and speed settings on this hair drier.", "there are"),
        ],
        "intermediate": [
            ("If you use a hair drier on the highest heat setting every day, your hair might become dry and damaged.", "first conditional - warning"),
            ("A professional hair drier is more powerful than a budget model, and it dries hair much more quickly.", "comparative + addition"),
            ("She wrapped the cord neatly around the drier and then stored it in the bathroom cabinet.", "compound sentence - sequence"),
            ("Using a hair drier is convenient in cold weather, but you should always keep it away from water.", "compound sentence - safety"),
            ("If you hold the hair drier too close to your hair, the heat will cause damage over time.", "first conditional"),
        ],
        "upper_intermediate": [
            ("The hair drier that she ordered online came with a diffuser attachment designed specifically for curly hair.", "restrictive relative clause + passive"),
            ("Hair driers, which work by passing air over a heated element, can cause considerable damage to hair if used without a heat-protecting product.", "non-restrictive relative clause + conditional"),
            ("The old hair drier that had been used daily for ten years finally overheated and automatically shut itself off as a safety measure.", "restrictive relative clause + past perfect + passive"),
            ("Hairdressers who work with hair driers throughout the day are advised to take regular breaks to avoid repetitive strain in the wrist and shoulder.", "restrictive relative clause + passive"),
            ("The hair drier must never be used near water or in a wet environment because of the serious risk of electric shock.", "modal passive + reason clause"),
        ],
        "advanced": [
            ("The evolution of the hair drier from a heavy, hazardous salon appliance to a compact, ionic device with multiple precision settings reflects the broader trend of miniaturisation and consumer-focused engineering in domestic technology.", "noun phrase + abstract noun + gerund"),
            ("Trichologists advise that excessive heat from hair driers degrades the keratin structure of the hair shaft over time, progressively reducing its tensile strength, elasticity, and natural lustre.", "reporting verb + that-clause + noun phrase + parallel structure"),
            ("The ergonomic design challenges inherent in a hair drier — balancing weight distribution, cord management, airflow efficiency, and thermal safety within a handheld form factor — represent a deceptively complex engineering problem.", "appositive phrase + parallel structure + abstract noun"),
            ("Cultural attitudes toward hair drying vary significantly across climates and traditions; in some societies, air drying is preferred as the natural method, while in others the hair drier is considered an indispensable morning ritual.", "parallel structure + contrast + noun phrase"),
            ("The proliferation of social media hair tutorials has created unprecedented consumer demand for salon-grade hair driers, fundamentally disrupting the traditional boundary between professional and domestic hair-care equipment.", "noun phrase + passive + gerund"),
        ],
    },
    "toothbrush": {
        "beginner": [
            ("I brush my teeth every morning.", "simple present - frequency"),
            ("My toothbrush is blue.", "simple present - adjective"),
            ("She bought a new toothbrush.", "simple past"),
            ("He brushed his teeth at night.", "simple past"),
            ("Keep your toothbrush clean.", "imperative"),
        ],
        "elementary": [
            ("Can you show me how to brush teeth correctly?", "modal - can, request"),
            ("There is a toothbrush in the bathroom cup.", "there is"),
            ("Could you replace your toothbrush with a new one?", "modal - polite request"),
            ("Is an electric toothbrush better than a manual one?", "yes/no question - comparison"),
            ("There are different sizes of toothbrush available for adults and children.", "there are"),
        ],
        "intermediate": [
            ("If you do not brush your teeth twice a day, you are more likely to develop cavities and gum disease.", "first conditional"),
            ("An electric toothbrush is more effective than a manual one at removing plaque from the gum line.", "comparative"),
            ("She applied toothpaste to her toothbrush and then brushed her teeth for a full two minutes.", "compound sentence - sequence"),
            ("Dentists recommend brushing your teeth after every meal, but at least twice daily is the minimum.", "reporting verb + gerund + contrast"),
            ("If you store your toothbrush near the toilet, bacteria can settle on the bristles and contaminate it.", "first conditional - hygiene"),
        ],
        "upper_intermediate": [
            ("The toothbrush that the dentist gave her after the check-up had extra-soft bristles designed for sensitive gums.", "restrictive relative clause + passive"),
            ("Toothbrushes, which should be replaced every three months or after an illness, are one of the most personal hygiene items a person owns.", "non-restrictive relative clause + superlative"),
            ("The child's toothbrush that was purchased at the pharmacy had a timer built into the handle to encourage brushing for two full minutes.", "restrictive relative clause + passive + purpose infinitive"),
            ("Children who are taught proper toothbrushing technique from an early age tend to maintain better dental health throughout their lives.", "restrictive relative clause + tendency"),
            ("The toothbrush must be rinsed thoroughly after each use and stored upright in a clean, open-air holder so that it dries quickly.", "modal passive + purpose clause"),
        ],
        "advanced": [
            ("The toothbrush, an object so mundane that its design is rarely given a second thought, has undergone surprisingly radical innovation in recent years, with sonic and oscillating technologies delivering measurably superior plaque removal compared with manual brushing.", "appositive clause + abstract noun + gerund + comparative"),
            ("Dental hygienists emphasise that the technique used when brushing is at least as important as the quality of the toothbrush itself, since incorrect angling and pressure distribution can actually damage enamel and recede gum tissue over time.", "reporting verb + that-clause + comparative + causal clause"),
            ("The adoption of biodegradable bamboo toothbrushes as an alternative to conventional plastic ones reflects a growing consumer awareness of the environmental implications of single-use personal hygiene products.", "noun phrase + relative clause + gerund"),
            ("Archaeologists have discovered primitive tooth-cleaning implements made from frayed twigs dating back thousands of years, suggesting that the fundamental human impulse to clean the teeth is not a modern preoccupation but an ancient one.", "past perfect + participial phrase + that-clause"),
            ("The humble toothbrush, when examined as a cultural artefact, reveals the intersection of medical knowledge, industrial manufacturing, consumer marketing, and personal ritual in the everyday maintenance of the body.", "appositive clause + abstract noun + parallel structure"),
        ],
    },
}
