from __future__ import annotations

SENTENCES_PART2 = {
    "elephant": {
        "beginner": [
            ("The elephant is very big.", "simple_present_adjective"),
            ("Elephants eat leaves and grass.", "simple_present_plural"),
            ("The elephant has a long trunk.", "simple_present_possession"),
            ("I saw an elephant at the zoo.", "simple_past"),
            ("The elephant walked slowly.", "simple_past_adverb"),
        ],
        "elementary": [
            ("Can elephants swim in deep water?", "modal_can_question"),
            ("There is a large elephant near the river.", "there_is_structure"),
            ("Could you hear the elephant trumpet loudly?", "modal_could_question"),
            ("There are three elephants in this photo.", "there_are_plural"),
            ("Can an elephant remember its old home?", "modal_can_question"),
        ],
        "intermediate": [
            ("Elephants are smarter than most animals, and they can solve simple puzzles.", "comparative_compound"),
            ("If we protect forests, elephants will have enough food to survive.", "first_conditional"),
            ("The elephant lifted the heavy log and carried it across the field.", "compound_sentence_past"),
            ("Elephants live in large family groups, and the oldest female leads them.", "compound_sentence_present"),
            ("If an elephant is injured, other elephants in the herd will help it.", "first_conditional"),
        ],
        "upper_intermediate": [
            ("The elephant that was rescued from the forest has now recovered fully.", "relative_clause_past"),
            ("Hundreds of elephants are killed every year because of illegal hunting.", "passive_voice_present"),
            ("The young elephant, which had lost its mother, was cared for by the herd.", "non_defining_relative_clause"),
            ("It is believed that elephants grieve for their dead by staying near the body.", "passive_impersonal_belief"),
            ("The ivory trade, which was banned internationally, still threatens elephant populations.", "non_defining_relative_clause_passive"),
        ],
        "advanced": [
            ("Elephants demonstrate remarkable cognitive abilities, including self-recognition in mirrors, which places them among a select group of species with theory of mind.", "sophisticated_subordination"),
            ("The conservation of elephant habitats requires not only government policy but also the active participation of local communities who coexist with these magnificent animals.", "complex_noun_phrase_coordination"),
            ("Having been displaced from their ancestral migration routes by expanding agriculture, many elephant herds now face severe food scarcity during the dry season.", "perfect_participle_clause"),
            ("The matriarch's accumulated knowledge of water sources, which can span decades of memory, is indispensable to the survival of the entire herd during droughts.", "relative_clause_complex_noun_phrase"),
            ("Researchers argue that the emotional bonds elephants form within family units are sophisticated enough to warrant a serious reconsideration of how we define animal consciousness.", "argue_that_subordination"),
        ],
    },
    "bear": {
        "beginner": [
            ("The bear is brown and furry.", "simple_present_adjective"),
            ("Bears eat fish and honey.", "simple_present_plural"),
            ("The bear climbed the tall tree.", "simple_past"),
            ("A bear sleeps in winter.", "simple_present_habit"),
            ("The bear had sharp claws.", "simple_past_possession"),
        ],
        "elementary": [
            ("Can bears climb trees very fast?", "modal_can_question"),
            ("There is a bear sleeping in that cave.", "there_is_structure"),
            ("Could you see the bear near the river?", "modal_could_question"),
            ("There are many bears in the cold forest.", "there_are_plural"),
            ("Can a bear run faster than a human?", "modal_can_comparative_question"),
        ],
        "intermediate": [
            ("Bears hibernate during winter, and they do not eat for several months.", "compound_sentence_present"),
            ("If you see a bear in the wild, you should stay very calm and move away slowly.", "first_conditional_advice"),
            ("The mother bear protected her cubs and chased the wolf away.", "compound_sentence_past"),
            ("Bears are larger than wolves, but wolves hunt in groups to defend themselves.", "comparative_compound_contrast"),
            ("If bears cannot find enough food before winter, they may not survive hibernation.", "first_conditional"),
        ],
        "upper_intermediate": [
            ("The bear that was seen near the village has been safely relocated to the national park.", "relative_clause_passive"),
            ("Brown bears are found across a wide range of habitats, from dense forests to open tundra.", "passive_voice_present_range"),
            ("The bear cub, which had wandered away from its mother, was found by forest rangers the next morning.", "non_defining_relative_clause_past"),
            ("It is estimated that polar bear populations will decline significantly as Arctic ice continues to melt.", "passive_impersonal_future"),
            ("Bears, which are omnivores, adjust their diet according to what food is available in each season.", "non_defining_relative_clause_present"),
        ],
        "advanced": [
            ("The bear's seemingly lethargic winter dormancy is, in fact, a metabolically active state during which its body temperature drops only marginally, distinguishing it from true hibernation.", "sophisticated_contrast_subordination"),
            ("Conservation corridors connecting fragmented forest patches are essential for maintaining genetic diversity among bear populations that would otherwise become isolated.", "complex_passive_relative"),
            ("Having spent months accumulating fat reserves in autumn, the bear emerges in spring noticeably thinner but remarkably healthy given its prolonged fast.", "perfect_participle_contrast"),
            ("The conflict between expanding human settlements and bear habitats presents wildlife managers with a dilemma that no simple policy can fully resolve.", "complex_noun_phrase_relative"),
            ("Grizzly bears, once extirpated from much of their historical range, are slowly reclaiming territory in regions where rewilding programmes have been actively implemented.", "passive_complex_relative_clause"),
        ],
    },
    "zebra": {
        "beginner": [
            ("The zebra has black and white stripes.", "simple_present_possession"),
            ("Zebras live in Africa.", "simple_present_location"),
            ("The zebra ran very fast.", "simple_past_adverb"),
            ("A zebra looks like a horse.", "simple_present_comparison"),
            ("Zebras eat grass every day.", "simple_present_habit"),
        ],
        "elementary": [
            ("Can you tell which zebra has the most stripes?", "modal_can_question"),
            ("There is a zebra drinking water at the river.", "there_is_present_continuous"),
            ("There are many zebras walking across the plains.", "there_are_present_continuous"),
            ("Could the lions catch the fast zebra?", "modal_could_question"),
            ("Can two zebras have exactly the same stripe pattern?", "modal_can_question"),
        ],
        "intermediate": [
            ("Zebras live in large herds, and they protect each other from lions.", "compound_sentence_present"),
            ("If a zebra gets separated from its herd, it becomes vulnerable to predators.", "first_conditional"),
            ("The zebra galloped across the open plain and leaped over the shallow stream.", "compound_sentence_past"),
            ("Zebras are faster than wildebeest, but lions are still able to catch young ones.", "comparative_compound_contrast"),
            ("If you look closely at two zebras, you will notice their stripe patterns are different.", "first_conditional_observation"),
        ],
        "upper_intermediate": [
            ("The zebra that was separated from the herd was eventually guided back by rangers on horseback.", "relative_clause_passive_past"),
            ("It is thought that a zebra's stripes evolved as a defence against biting insects rather than as camouflage.", "passive_impersonal_belief"),
            ("The young zebra, which had been born just hours earlier, was already able to stand and run.", "non_defining_relative_clause_past"),
            ("Zebra migration routes, which can stretch over hundreds of kilometres, are increasingly blocked by fences and roads.", "non_defining_relative_clause_passive"),
            ("Thousands of zebras are observed crossing the Mara River annually during the Great Migration.", "passive_voice_present"),
        ],
        "advanced": [
            ("The hypothesis that zebra stripes serve primarily to deter blood-sucking flies has gained considerable empirical support from controlled field experiments conducted in Africa.", "sophisticated_noun_clause_relative"),
            ("As savanna grasslands shrink due to agricultural expansion, zebra populations that once roamed freely across vast distances are now confined to fragmented reserves.", "complex_subordination_relative"),
            ("The social cohesion of a zebra herd, maintained through mutual grooming and alarm calls, represents a sophisticated collective defence strategy against apex predators.", "complex_noun_phrase"),
            ("Having evolved in an environment dominated by fast-moving predators, zebras possess a cardiovascular system capable of sustaining bursts of speed that most predators cannot match over long distances.", "perfect_participle_clause_complex"),
            ("Conservationists argue that preserving migratory corridors is more effective than establishing isolated reserves, because zebra populations require seasonal movement to access adequate water and grazing land.", "argue_that_comparative_subordination"),
        ],
    },
    "giraffe": {
        "beginner": [
            ("The giraffe has a very long neck.", "simple_present_possession"),
            ("Giraffes eat leaves from tall trees.", "simple_present_plural"),
            ("The giraffe is the tallest animal.", "simple_present_superlative"),
            ("I saw a giraffe at the zoo.", "simple_past"),
            ("The giraffe walked slowly to the tree.", "simple_past"),
        ],
        "elementary": [
            ("Can a giraffe reach the top branches of a tree?", "modal_can_question"),
            ("There is a tall giraffe eating leaves near us.", "there_is_present_continuous"),
            ("There are four giraffes standing by the watering hole.", "there_are_plural"),
            ("Could you see the giraffe over the tall wall?", "modal_could_question"),
            ("Can giraffes defend themselves against lions?", "modal_can_question"),
        ],
        "intermediate": [
            ("Giraffes have very long necks, and they can reach leaves that other animals cannot.", "compound_sentence_present_can"),
            ("If a giraffe bends down to drink water, it becomes an easy target for crocodiles.", "first_conditional"),
            ("The giraffe stretched its neck high and pulled the fresh leaves from the branch.", "compound_sentence_past"),
            ("Giraffes are taller than elephants, but elephants are heavier and stronger.", "comparative_compound_contrast"),
            ("If you watch a giraffe drink, you will see how awkwardly it has to spread its legs.", "first_conditional_observation"),
        ],
        "upper_intermediate": [
            ("The giraffe that was born at the wildlife sanctuary quickly became a favourite attraction for visitors.", "relative_clause_past"),
            ("Giraffes are found exclusively in sub-Saharan Africa, where they roam open woodlands and savannas.", "passive_voice_relative_clause"),
            ("The adult giraffe, which can weigh up to 1,200 kilograms, uses its powerful kick to defend against lions.", "non_defining_relative_clause_present"),
            ("It has been discovered that giraffes produce low-frequency sounds that are inaudible to the human ear.", "passive_impersonal_discovery"),
            ("Giraffe populations, which have declined by nearly 40 percent over the last three decades, are now listed as vulnerable.", "non_defining_relative_clause_passive"),
        ],
        "advanced": [
            ("The elongated cervical vertebrae of the giraffe, each of which can measure up to 28 centimetres, represent an extraordinary example of evolutionary adaptation driven by competitive foraging pressure.", "complex_non_defining_relative_clause"),
            ("Despite their imposing stature, giraffes are surprisingly vulnerable during the act of drinking, a moment during which their cardiovascular system must manage extreme changes in blood pressure.", "sophisticated_contrast_apposition"),
            ("Scientists have recently reclassified giraffes into four distinct species based on genetic analysis, a finding that has significant implications for how conservation resources are allocated.", "relative_clause_complex_consequence"),
            ("Having evolved the tallest body plan of any living terrestrial animal, the giraffe faces unique physiological challenges, particularly in maintaining adequate blood pressure to perfuse the brain.", "perfect_participle_complex"),
            ("The silent communication networks that giraffes maintain through infrasound, largely undetected until recent decades, suggest that animal social lives are far more complex than earlier naturalists had imagined.", "relative_clause_passive_complex_subordination"),
        ],
    },
    "backpack": {
        "beginner": [
            ("I carry my books in my backpack.", "simple_present_habit"),
            ("My backpack is blue and heavy.", "simple_present_adjective"),
            ("She put her lunch in the backpack.", "simple_past"),
            ("The backpack has many pockets.", "simple_present_possession"),
            ("I bought a new backpack yesterday.", "simple_past"),
        ],
        "elementary": [
            ("Can you fit your water bottle in the backpack?", "modal_can_question"),
            ("There is a red backpack under the desk.", "there_is_location"),
            ("There are three backpacks left in the shop.", "there_are_quantity"),
            ("Could you carry the heavy backpack for me?", "modal_could_request"),
            ("Can a backpack protect a laptop from rain?", "modal_can_question"),
        ],
        "intermediate": [
            ("My backpack is heavier than my sister's because I carry extra textbooks.", "comparative_because"),
            ("If you organise your backpack the night before, you will never forget anything at school.", "first_conditional_advice"),
            ("She zipped up her backpack and ran to catch the school bus.", "compound_sentence_past"),
            ("A good backpack should be comfortable to wear, and it must also be strong enough to last several years.", "compound_sentence_modal"),
            ("If you buy a waterproof backpack, your books will stay dry even in heavy rain.", "first_conditional"),
        ],
        "upper_intermediate": [
            ("The backpack that he left on the train was returned to him the following morning by the station staff.", "relative_clause_passive_past"),
            ("Ergonomically designed backpacks are now recommended by doctors to prevent back pain in school children.", "passive_voice_present_purpose"),
            ("Her old backpack, which she had used for five years, finally tore at the strap during the hiking trip.", "non_defining_relative_clause_past"),
            ("It is advised that students should not carry backpacks weighing more than ten percent of their body weight.", "passive_impersonal_advice"),
            ("The backpack was carefully packed with everything needed for the three-day school camp, including a sleeping bag and a raincoat.", "passive_voice_past_detail"),
        ],
        "advanced": [
            ("The transition from the rigid school satchel to the modern ergonomic backpack reflects broader shifts in educational philosophy regarding the physical wellbeing of students.", "sophisticated_noun_phrase_subordination"),
            ("A well-chosen backpack, one that distributes weight evenly across both shoulders and sits close to the back, can significantly reduce the cumulative musculoskeletal strain that students accumulate over years of daily use.", "apposition_relative_clause_complex"),
            ("Beyond its utilitarian function, the backpack has become a vehicle for self-expression among adolescents, its exterior adorned with badges, keyrings, and patches that signal identity and group membership.", "sophisticated_apposition_relative"),
            ("The proliferation of lightweight, high-capacity backpacks engineered from technical fabrics has transformed long-distance trekking, enabling hikers to carry multi-day supplies without the debilitating fatigue associated with older frame packs.", "complex_participial_relative_clause"),
            ("Designers working at the intersection of fashion and functionality have elevated the backpack from a purely practical object to a status symbol, with certain limited-edition versions commanding prices that rival luxury handbags.", "complex_prepositional_phrase_relative"),
        ],
    },
    "umbrella": {
        "beginner": [
            ("I use an umbrella when it rains.", "simple_present_when_clause"),
            ("The umbrella is red and round.", "simple_present_adjective"),
            ("She opened her umbrella quickly.", "simple_past_adverb"),
            ("My umbrella broke in the strong wind.", "simple_past"),
            ("He forgot his umbrella at school.", "simple_past"),
        ],
        "elementary": [
            ("Can a small umbrella keep you dry in heavy rain?", "modal_can_question"),
            ("There is a yellow umbrella by the front door.", "there_is_location"),
            ("There are many colourful umbrellas at the market.", "there_are_adjective"),
            ("Could you share your umbrella with me?", "modal_could_request"),
            ("Can you fold this umbrella and put it in your bag?", "modal_can_question"),
        ],
        "intermediate": [
            ("Umbrellas are more useful than raincoats when you also need to carry a bag.", "comparative_when_clause"),
            ("If you do not carry an umbrella during monsoon season, you will get completely soaked.", "first_conditional"),
            ("The wind turned her umbrella inside out, and she had to buy a new one.", "compound_sentence_past"),
            ("A good umbrella should be both waterproof and windproof, and it should also be light enough to carry every day.", "compound_sentence_modal"),
            ("If the rain continues, we will need to wait under the umbrella until the auto arrives.", "first_conditional"),
        ],
        "upper_intermediate": [
            ("The umbrella that she left on the bus was handed in to the lost-and-found office at the station.", "relative_clause_passive_past"),
            ("Compact folding umbrellas are now preferred by most commuters because they fit easily into a school bag or handbag.", "passive_voice_present_because"),
            ("Her grandmother's large umbrella, which had been in the family for decades, was still completely waterproof.", "non_defining_relative_clause_past"),
            ("It is widely believed that carrying an umbrella on a sunny day will reduce your chances of being caught in a sudden shower.", "passive_impersonal_belief"),
            ("Dozens of umbrellas are left behind on public transport every year, making them one of the most commonly lost personal items.", "passive_voice_present_result"),
        ],
        "advanced": [
            ("The umbrella's deceptively simple mechanism — a canopy of waterproof fabric stretched over a collapsible ribbed frame — has remained largely unchanged for over two centuries despite countless attempts to redesign it.", "sophisticated_apposition_contrast"),
            ("In densely populated monsoon cities like Chennai, the umbrella functions not merely as protection against rain but as a social object whose colour, size, and condition subtly communicate aspects of the owner's identity.", "complex_not_merely_but_relative"),
            ("The cultural symbolism of the umbrella as a marker of status and authority, evident in ancient royal courts from Egypt to China, persisted well into the colonial era before being entirely supplanted by its practical connotations.", "sophisticated_participial_subordination"),
            ("Engineers developing next-generation canopy materials are experimenting with hydrophobic nanotextiles that shed water so efficiently that a single shake renders the surface dry, eliminating the dripping associated with conventional fabrics.", "complex_participial_relative_clause"),
            ("The paradox of umbrella ownership — that people purchase them in large numbers yet consistently fail to have one available when rain arrives — has been studied by behavioural economists as an example of optimism bias in everyday decision-making.", "sophisticated_apposition_relative_passive"),
        ],
    },
    "handbag": {
        "beginner": [
            ("She carries a small handbag to school.", "simple_present_habit"),
            ("The handbag is made of black leather.", "simple_present_material"),
            ("My mother bought a new handbag today.", "simple_past"),
            ("The handbag has a golden zip.", "simple_present_possession"),
            ("She put her phone in her handbag.", "simple_past"),
        ],
        "elementary": [
            ("Can you find my keys inside this handbag?", "modal_can_question"),
            ("There is a small handbag on the chair.", "there_is_location"),
            ("There are many handbags on display in the shop window.", "there_are_plural"),
            ("Could you hold my handbag while I wash my hands?", "modal_could_request"),
            ("Can a handbag hold a tablet and a water bottle?", "modal_can_question"),
        ],
        "intermediate": [
            ("Her handbag is bigger than mine, so she can carry more things inside.", "comparative_so_clause"),
            ("If you choose a handbag with several pockets, it will be much easier to stay organised.", "first_conditional_advice"),
            ("She searched through her handbag and finally found the crumpled bus pass.", "compound_sentence_past"),
            ("A durable handbag should be both stylish and practical, and it must be large enough to hold daily essentials.", "compound_sentence_modal"),
            ("If you store your handbag on the floor, it will get dirty and scratched much faster.", "first_conditional"),
        ],
        "upper_intermediate": [
            ("The handbag that was left at the café was returned to its owner after the staff found her number on a card inside.", "relative_clause_passive_past"),
            ("Handbags made from genuine leather are considered more durable than those produced from synthetic materials.", "passive_voice_present_comparative"),
            ("Her favourite handbag, which she had saved up for over six months, was stolen on the crowded train.", "non_defining_relative_clause_past"),
            ("It is recommended that valuable items should not be placed in an outer pocket of a handbag when travelling in busy public areas.", "passive_impersonal_recommendation"),
            ("Handbags are often designed to complement specific outfits, and the most versatile ones are those that work equally well in casual and formal settings.", "passive_voice_compound_relative"),
        ],
        "advanced": [
            ("The handbag occupies a unique position in material culture, serving simultaneously as a functional container, a fashion accessory, and a social signal whose brand and condition are read by others as proxies for wealth and taste.", "sophisticated_participial_series"),
            ("Critics of fast fashion have pointed out that the rapid obsolescence of handbag trends creates enormous textile waste, much of which ends up in landfill because the composite materials used are difficult to recycle.", "complex_subordination_passive_relative"),
            ("The craftsmanship involved in producing a hand-stitched leather handbag — selecting the hide, cutting patterns, hand-setting hardware — represents a form of artisanal knowledge that mass production has largely rendered economically unviable.", "sophisticated_apposition_passive"),
            ("Consumer psychology research suggests that the decision to purchase a premium handbag is rarely driven by purely functional considerations but is instead shaped by complex motivations including aspiration, self-reward, and the desire for social recognition.", "complex_subordination_list"),
            ("As sustainability concerns reshape consumer behaviour, designers are increasingly exploring plant-based leather alternatives derived from pineapple leaf fibre or mushroom mycelium, materials that mimic the aesthetic properties of animal leather without the associated ethical and environmental costs.", "complex_participial_relative_clause"),
        ],
    },
    "tie": {
        "beginner": [
            ("He wears a blue tie to work.", "simple_present_habit"),
            ("The tie is long and narrow.", "simple_present_adjective"),
            ("My father tied his tie slowly.", "simple_past_adverb"),
            ("The tie matches his white shirt.", "simple_present"),
            ("He bought a new tie for the ceremony.", "simple_past_purpose"),
        ],
        "elementary": [
            ("Can you help me tie this tie correctly?", "modal_can_request"),
            ("There is a silk tie hanging on the door.", "there_is_location"),
            ("There are several ties laid out on the table.", "there_are_plural"),
            ("Could you teach me how to knot a tie?", "modal_could_request"),
            ("Can a clip-on tie look as good as a real one?", "modal_can_comparison_question"),
        ],
        "intermediate": [
            ("A tie with stripes is more formal than one with cartoon characters on it.", "comparative_formal"),
            ("If you learn to tie a Windsor knot, you will always look smart at interviews.", "first_conditional_advice"),
            ("He straightened his tie in the mirror and walked confidently into the interview room.", "compound_sentence_past"),
            ("Some schools require students to wear a tie, but many students find them uncomfortable in hot weather.", "compound_sentence_contrast"),
            ("If you fold the tie carefully and store it in a roll, it will not get creased.", "first_conditional"),
        ],
        "upper_intermediate": [
            ("The striped tie that he wore to the prize-giving ceremony was a gift from his grandfather.", "relative_clause_past"),
            ("Ties are generally considered formal accessories and are expected to be worn at official functions and job interviews.", "passive_voice_present_compound"),
            ("His favourite tie, which was made of pure Kanchipuram silk, had been a birthday gift from his mother.", "non_defining_relative_clause_past_material"),
            ("It is generally accepted that the width of a tie should be proportional to the width of the jacket's lapels.", "passive_impersonal_acceptance"),
            ("In many corporate environments, the dress code specifying that male employees must wear ties has been relaxed over the past decade.", "passive_voice_relative_clause_past"),
        ],
        "advanced": [
            ("The necktie's trajectory from a Croatian mercenary's knotted cravat in the seventeenth century to a global symbol of professional formality illustrates how military fashion can infiltrate and permanently alter civilian dress codes.", "sophisticated_noun_phrase_subordination"),
            ("Although the tie serves no functional purpose whatsoever, its persistence in professional and ceremonial dress codes across cultures speaks to the powerful role that sartorial convention plays in constructing and maintaining social hierarchies.", "complex_although_contrast"),
            ("The ongoing debate about whether ties should be mandatory in schools reflects deeper tensions between traditionalists who view uniform codes as instilling discipline and progressives who argue that comfort and personal expression are more conducive to learning.", "complex_relative_clause_parallel"),
            ("Designers who have attempted to reinvent the tie as a genuinely functional garment have largely failed commercially, suggesting that consumers value its symbolic meaning over any practical utility it might theoretically provide.", "relative_clause_passive_subordination"),
            ("The gradual abandonment of the tie in Silicon Valley workplaces, enthusiastically adopted as a symbol of creative freedom and egalitarianism, has been interpreted by sociologists as a deliberate performance of anti-establishment values rather than a straightforward preference for comfort.", "sophisticated_participial_passive_contrast"),
        ],
    },
    "suitcase": {
        "beginner": [
            ("She packed her suitcase the night before.", "simple_past"),
            ("The suitcase is too heavy to carry.", "simple_present_adjective_infinitive"),
            ("He put his clothes in the big suitcase.", "simple_past"),
            ("My suitcase has wheels at the bottom.", "simple_present_possession"),
            ("We pulled our suitcases through the airport.", "simple_past_plural"),
        ],
        "elementary": [
            ("Can you lift that heavy suitcase onto the shelf?", "modal_can_question"),
            ("There is a black suitcase on the baggage belt.", "there_is_location"),
            ("There are two suitcases left uncollected at the airport.", "there_are_plural"),
            ("Could you check if my suitcase has arrived at the carousel?", "modal_could_request"),
            ("Can this suitcase fit inside the overhead compartment?", "modal_can_question"),
        ],
        "intermediate": [
            ("My suitcase is heavier than the allowed limit, so I had to remove some items.", "comparative_so_clause_past"),
            ("If you label your suitcase clearly, you will find it quickly on the baggage carousel.", "first_conditional_advice"),
            ("She locked the suitcase and attached a bright yellow tag so it would be easy to spot.", "compound_sentence_past_purpose"),
            ("A hard-shell suitcase is more durable than a soft one, but it is also heavier when empty.", "comparative_compound_contrast"),
            ("If the airline loses your suitcase, you should report it immediately at the customer service desk.", "first_conditional_instruction"),
        ],
        "upper_intermediate": [
            ("The suitcase that was reported missing at Chennai airport was located at a transit hub and delivered the following day.", "relative_clause_passive_past"),
            ("Passengers are advised to keep valuable items in their hand luggage rather than checking them in their suitcase.", "passive_voice_present_advice"),
            ("Her battered old suitcase, which had accompanied her on every family holiday since childhood, finally gave way at the handle.", "non_defining_relative_clause_past"),
            ("It is required by most airlines that suitcases checked into the hold must not exceed a specified weight limit.", "passive_impersonal_requirement"),
            ("Hundreds of unclaimed suitcases are auctioned off annually by airports that have been unable to trace their owners.", "passive_voice_present_relative_clause"),
        ],
        "advanced": [
            ("The modern wheeled suitcase, an invention that most travellers now take entirely for granted, was only introduced commercially in 1987, a remarkably recent innovation given how ancient the concept of portable luggage is.", "sophisticated_apposition_contrast"),
            ("The contents of a traveller's suitcase offer a surprisingly intimate portrait of their priorities, anxieties, and cultural assumptions — what is packed, and what is left behind, reveals as much about a person as any formal self-description.", "sophisticated_dash_clause"),
            ("Airport security requirements mandating that suitcases be screenable and lockable with approved devices represent a fascinating case study in how geopolitical risk reconfigures the design constraints of even the most mundane consumer products.", "complex_participial_relative_clause"),
            ("Sustainable travel advocates argue that the shift towards carry-on-only travel, while initially driven by airline fee structures, has inadvertently encouraged more mindful packing habits and reduced the environmental footprint associated with baggage handling.", "complex_while_subordination"),
            ("The psychological phenomenon whereby travellers systematically overestimate the amount of clothing they will need — a tendency that marketers have long exploited by designing ever-larger suitcase formats — has been well documented in studies of pre-holiday decision-making.", "sophisticated_whereby_relative_passive"),
        ],
    },
    "frisbee": {
        "beginner": [
            ("We threw the frisbee in the park.", "simple_past_location"),
            ("The frisbee flew through the air.", "simple_past"),
            ("He caught the frisbee with one hand.", "simple_past"),
            ("The frisbee is round and flat.", "simple_present_adjective"),
            ("She threw the frisbee to her friend.", "simple_past"),
        ],
        "elementary": [
            ("Can you throw the frisbee all the way to me?", "modal_can_question"),
            ("There is a yellow frisbee on the grass.", "there_is_location"),
            ("There are children playing frisbee in the field.", "there_are_present_continuous"),
            ("Could you teach me how to throw a frisbee properly?", "modal_could_request"),
            ("Can the dog catch the frisbee in the air?", "modal_can_question"),
        ],
        "intermediate": [
            ("Throwing a frisbee is easier than it looks, but catching one in the wind takes more practice.", "comparative_contrast"),
            ("If you flick your wrist as you throw, the frisbee will fly much straighter and farther.", "first_conditional_technique"),
            ("He threw the frisbee high into the air, and his dog leaped up and caught it perfectly.", "compound_sentence_past"),
            ("A frisbee is lighter than a ball, and it can travel long distances with very little effort.", "comparative_compound_can"),
            ("If the wind is strong, you should angle the frisbee slightly into the wind to keep it on course.", "first_conditional_advice"),
        ],
        "upper_intermediate": [
            ("The frisbee that sailed over the fence landed neatly in the neighbour's flower bed.", "relative_clause_past_result"),
            ("Ultimate frisbee is now played competitively in over 80 countries and is being considered for inclusion in future Olympic programmes.", "passive_voice_present_progressive"),
            ("The old frisbee, which had been found on the beach, was still in good enough condition to use.", "non_defining_relative_clause_past"),
            ("It is said that the frisbee was inspired by the metal pie tins that university students in America used to throw at each other for fun.", "passive_impersonal_origin"),
            ("Aerodynamic frisbees designed for competitive distance throwing are engineered to a far higher specification than the simple plastic discs sold as toys.", "passive_voice_comparative"),
        ],
        "advanced": [
            ("The aerodynamics of a well-thrown frisbee, governed by the same principles of gyroscopic stability that keep a spinning top upright, make it one of the most elegantly efficient projectile forms ever devised by recreational designers.", "sophisticated_participial_superlative"),
            ("Ultimate frisbee's self-refereed culture, in which players are expected to resolve disputes through respectful dialogue rather than appealing to an external official, represents an unusual and arguably admirable model of sporting governance.", "non_defining_relative_clause_contrast"),
            ("The transition of frisbee from a campus pastime to a globally organised competitive sport illustrates how informal recreational activities can, given sufficient community investment, develop the institutional infrastructure of mainstream athletics.", "complex_subordination_given"),
            ("Researchers studying outdoor play have noted that the frisbee's unique flight characteristics — its tendency to hover, curve, and respond to atmospheric conditions — generate a qualitatively different form of physical engagement than sports using heavier projectiles.", "sophisticated_dash_comparative"),
            ("The cultural association of the frisbee with relaxed, communal leisure, reinforced through decades of beach and park imagery, has paradoxically made it difficult for competitive ultimate frisbee to attract the mainstream sports media coverage its organisational maturity arguably warrants.", "sophisticated_participial_passive_contrast"),
        ],
    },
    "skis": {
        "beginner": [
            ("Skis are long and smooth.", "simple_present_adjective"),
            ("People use skis to slide on snow.", "simple_present_purpose"),
            ("I have never seen real skis before.", "present_perfect_negative"),
            ("Skis are used in cold, snowy countries.", "simple_present_passive"),
            ("The skis were leaning against the wall.", "simple_past_progressive"),
        ],
        "elementary": [
            ("Can you ski down a mountain without falling?", "modal_can_question"),
            ("There are skis and poles in the picture from Switzerland.", "there_are_location"),
            ("Could you learn to ski in just one week?", "modal_could_question"),
            ("There is a pair of red skis at the ski school.", "there_is_location"),
            ("Can children learn to ski more easily than adults?", "modal_can_comparative_question"),
        ],
        "intermediate": [
            ("Skiing is more challenging than it looks in videos, and beginners often fall many times on their first day.", "comparative_compound_contrast"),
            ("If you visit a cold country in winter, you might get a chance to try skiing on real snow.", "first_conditional_opportunity"),
            ("The instructor strapped on her skis and glided effortlessly down the icy slope.", "compound_sentence_past"),
            ("Cross-country skis are longer and narrower than downhill skis because they are designed for flat terrain.", "comparative_because_clause"),
            ("If you rent skis rather than buying them, you can try different styles until you find the right fit.", "first_conditional_advice"),
        ],
        "upper_intermediate": [
            ("The skis that were used in the Winter Olympics were custom-built for each athlete to match their weight and skiing style.", "relative_clause_passive_past"),
            ("Modern ski equipment is designed with safety bindings that release automatically when the skier falls at high speed.", "passive_voice_present_relative_clause"),
            ("The old wooden skis, which had been on display in the sports museum, were replaced with modern fibreglass models.", "non_defining_relative_clause_passive"),
            ("It is estimated that over 300 million skier-days are recorded at ski resorts worldwide each winter season.", "passive_impersonal_statistic"),
            ("Alpine skiing has been practised as a competitive sport since the early twentieth century and was included in the first Winter Olympics in 1924.", "passive_voice_present_perfect_past"),
        ],
        "advanced": [
            ("The technological evolution of the ski — from primitive wooden planks used by Scandinavian hunters thousands of years ago to today's carbon-fibre racing boards engineered to precise flex profiles — mirrors the broader trajectory of sports science as a discipline.", "sophisticated_dash_comparative"),
            ("For students in tropical countries like India, skis represent not merely a piece of sporting equipment but a portal into an entirely foreign climate and landscape, accessible primarily through documentary footage and the accounts of well-travelled peers.", "complex_not_merely_but"),
            ("Climate change poses an existential threat to ski resorts at lower altitudes, where declining snowfall and rising temperatures are forcing operators to invest heavily in artificial snow-making technology as a costly and energy-intensive stopgap.", "complex_where_relative_participial"),
            ("The biomechanics of efficient downhill skiing, which requires the simultaneous coordination of edge angle, weight distribution, and pole timing across constantly shifting terrain, make it one of the most technically demanding of all winter sports.", "relative_clause_complex_list_superlative"),
            ("Sociologists have observed that ski culture, historically associated with affluent European and North American leisure classes, is gradually diversifying as programme initiatives introduce the sport to communities for whom the cost and logistics of snow travel had previously been prohibitive.", "complex_passive_relative_clause"),
        ],
    },
    "snowboard": {
        "beginner": [
            ("A snowboard is wider than a ski.", "simple_present_comparative"),
            ("People ride snowboards on snowy hills.", "simple_present_habit"),
            ("He saw a snowboard in a sports shop.", "simple_past"),
            ("The snowboard was bright orange.", "simple_past_adjective"),
            ("Snowboards are used in winter sports.", "simple_present_passive"),
        ],
        "elementary": [
            ("Can you stand on a snowboard without falling off?", "modal_can_question"),
            ("There is a decorated snowboard on the wall of the sports shop.", "there_is_location_adjective"),
            ("There are snowboarders doing jumps at the Winter Olympics.", "there_are_present_continuous"),
            ("Could a beginner learn to snowboard safely?", "modal_could_question"),
            ("Can snowboarding be more fun than skiing?", "modal_can_comparative_question"),
        ],
        "intermediate": [
            ("Snowboarding is harder to learn than skiing, but many people find it more exciting once they get the hang of it.", "comparative_compound_contrast"),
            ("If you watch the Winter Olympics, you will see snowboarders performing incredible jumps and spins in the halfpipe.", "first_conditional_observation"),
            ("The snowboarder flew off the ramp and spun twice in the air before landing perfectly.", "compound_sentence_past"),
            ("A snowboard is wider and shorter than a ski, and the rider stands sideways rather than facing forward.", "comparative_compound_contrast"),
            ("If you want to try snowboarding, you should take at least three lessons before attempting a steep slope.", "first_conditional_advice"),
        ],
        "upper_intermediate": [
            ("The snowboard that was used to win the gold medal at the last Winter Olympics is now on display in a sports museum.", "relative_clause_passive_present"),
            ("Snowboarding was not recognised as an Olympic sport until the 1998 Nagano Winter Games, despite having been popular for over a decade.", "passive_voice_past_contrast"),
            ("The brightly decorated snowboard, which had been ridden by a professional athlete, was auctioned for charity.", "non_defining_relative_clause_passive_past"),
            ("It is generally considered that snowboarding appeals more to younger athletes who are drawn to its connections with skateboarding and surf culture.", "passive_impersonal_belief_relative_clause"),
            ("Snowboards are manufactured in a wide range of shapes and stiffnesses, each designed to optimise performance for a specific riding style.", "passive_voice_present_relative_clause_purpose"),
        ],
        "advanced": [
            ("The emergence of snowboarding as a mainstream winter sport in the 1990s was driven largely by its adoption of skateboarding aesthetics — the baggy clothing, the freestyle attitude, the emphasis on individual expression — which directly challenged the established culture of alpine skiing.", "sophisticated_passive_dash_relative"),
            ("For students in India who have never experienced snow, the snowboard exists primarily as an object encountered in action films and sports broadcasts, its physical properties — the flex, the edge grip, the wax — entirely abstract until the moment of first contact.", "sophisticated_dash_subordination"),
            ("The halfpipe event in competitive snowboarding requires athletes to generate enough vertical height above the pipe's lip to perform multiple rotations in the limited time available before gravity reasserts its authority.", "complex_relative_clause_purpose"),
            ("Material scientists developing next-generation snowboard cores are experimenting with bio-composite materials that offer equivalent performance to conventional wood-and-fibreglass constructions while substantially reducing the carbon footprint of manufacturing.", "complex_participial_relative_clause_contrast"),
            ("The globalisation of snowboarding as a youth culture phenomenon, transmitted through social media and action sports broadcasting, has created demand in countries with no winter climate, driving the growth of indoor ski slopes and dry-slope facilities as year-round training environments.", "sophisticated_participial_relative_clause"),
        ],
    },
    "sports ball": {
        "beginner": [
            ("We played with a sports ball in PE class.", "simple_past_location"),
            ("The ball is round and bouncy.", "simple_present_adjective"),
            ("He kicked the ball into the goal.", "simple_past"),
            ("Different sports use different types of balls.", "simple_present_plural"),
            ("She threw the ball to her teammate.", "simple_past"),
        ],
        "elementary": [
            ("Can you kick the ball into the net from here?", "modal_can_question"),
            ("There is a football rolling across the ground.", "there_is_present_continuous"),
            ("There are several balls in the sports cupboard.", "there_are_plural"),
            ("Could you pass the ball to me quickly?", "modal_could_request"),
            ("Can a tennis ball bounce higher than a basketball?", "modal_can_comparative_question"),
        ],
        "intermediate": [
            ("A cricket ball is harder and heavier than a tennis ball, which is why it can cause injury.", "comparative_compound_reason"),
            ("If you inflate the ball properly, it will bounce better and travel more accurately.", "first_conditional"),
            ("The striker headed the ball into the top corner of the net, and the crowd erupted.", "compound_sentence_past"),
            ("Different sports use different types of balls, and each is designed to suit the speed and playing surface of that sport.", "compound_sentence_passive"),
            ("If you practise controlling the ball every day, you will notice a significant improvement within a month.", "first_conditional_advice"),
        ],
        "upper_intermediate": [
            ("The ball that was hit out of the stadium during the final over was later found on a nearby rooftop.", "relative_clause_passive_past"),
            ("Sports balls are manufactured to precise specifications, and each must meet international standards for size, weight, and pressure.", "passive_voice_present_compound_modal"),
            ("The old leather cricket ball, which had been used in the historic Test match, was donated to the national sports museum.", "non_defining_relative_clause_passive_past"),
            ("It is required by international governing bodies that balls used in professional matches be certified before play begins.", "passive_impersonal_requirement_passive"),
            ("Aerodynamically engineered balls are now used across most professional sports to ensure consistent and predictable flight patterns.", "passive_voice_present_purpose"),
        ],
        "advanced": [
            ("The seemingly trivial differences in surface texture, seam configuration, and internal pressure between sports balls are in fact the product of decades of biomechanical research aimed at optimising the interaction between ball and playing environment.", "sophisticated_contrast_passive_participial"),
            ("The choice of ball technology in cricket — whether a red Dukes, a white Kookaburra, or a pink day-night ball — significantly influences the tactics available to bowlers, creating a layer of strategic complexity invisible to casual observers.", "sophisticated_dash_relative_clause"),
            ("Experimental fluid dynamics research has demonstrated that the erratic swing of a worn cricket ball is produced by asymmetric boundary layer separation, a phenomenon that professional bowlers have intuitively exploited for generations without formal understanding of its physics.", "complex_passive_relative_clause"),
            ("The standardisation of ball specifications across international competitions, while necessary for fairness, has occasionally generated controversy when equipment manufacturers claim that marginal design variations confer a competitive advantage to teams familiar with their product.", "complex_while_subordination_relative"),
            ("The ball, in virtually every culture that has developed organised sport, serves as the focal object around which collective physical effort, rule-governed competition, and communal spectatorship are simultaneously organised — a remarkably consistent cross-cultural pattern given the vast diversity of sporting traditions.", "sophisticated_relative_clause_dash_contrast"),
        ],
    },
    "kite": {
        "beginner": [
            ("We flew a kite on the beach.", "simple_past_location"),
            ("The kite is blue with a long tail.", "simple_present_adjective"),
            ("The string broke and the kite flew away.", "simple_past_compound"),
            ("Kites need wind to fly in the sky.", "simple_present_need"),
            ("She ran fast to make the kite go up.", "simple_past_purpose"),
        ],
        "elementary": [
            ("Can you fly a kite on a day with no wind?", "modal_can_question"),
            ("There is a bright kite stuck in the tall tree.", "there_is_adjective_location"),
            ("There are many kites flying during the Pongal festival.", "there_are_present_continuous_context"),
            ("Could you help me untangle the kite string?", "modal_could_request"),
            ("Can a kite fly if the string is too short?", "modal_can_conditional_question"),
        ],
        "intermediate": [
            ("Flying a kite is more enjoyable on a breezy day than on a completely calm one.", "comparative_than"),
            ("If the wind is too strong, the kite will pull hard on the string and may snap it.", "first_conditional"),
            ("He let out more string gradually, and the kite climbed higher into the clear blue sky.", "compound_sentence_past"),
            ("A diamond kite is easier to fly than a box kite, but a box kite can reach greater heights.", "comparative_compound_contrast"),
            ("If you cross the strings with another kite, your kite may fall, just as in the traditional kite-fighting game.", "first_conditional_cultural"),
        ],
        "upper_intermediate": [
            ("The homemade kite that he had built from newspaper and bamboo sticks won first prize at the school competition.", "relative_clause_past"),
            ("Kite festivals are celebrated across India, with the largest being held in Ahmedabad during the festival of Uttarayan.", "passive_voice_present_relative_clause"),
            ("The delicate silk kite, which had been crafted by a master artisan in Jaipur, was too valuable to be flown in strong winds.", "non_defining_relative_clause_passive_too_infinitive"),
            ("It is believed that kites were invented in China over two thousand years ago and were initially used for military communication.", "passive_impersonal_belief_passive"),
            ("Hundreds of kites are sold in Chennai markets during Pongal season, ranging from simple paper diamonds to elaborate decorated designs.", "passive_voice_present_range"),
        ],
        "advanced": [
            ("The kite's apparent simplicity — a taut surface angled to redirect wind force into lift — conceals a rich body of aerodynamic principle that early aviators, including the Wright brothers, studied carefully as they worked towards powered flight.", "sophisticated_dash_relative_clause"),
            ("In Tamil Nadu, kite flying during Pongal is not merely a recreational activity but a culturally significant ritual that marks the end of winter and the harvest season, embedding a simple toy within a complex web of agricultural and cosmological meaning.", "complex_not_merely_but_relative_clause"),
            ("The materials used in traditional kite-making — thin bamboo, rice paper, natural dye — represent a design philosophy of radical lightness that modern engineering, with all its advanced materials science, continues to find instructive.", "sophisticated_dash_contrast_relative"),
            ("Researchers working on high-altitude wind energy systems have revisited kite aerodynamics as a potential basis for tethered airborne turbines that could access the stronger, more consistent winds found above 300 metres altitude.", "complex_relative_clause_passive"),
            ("The competitive kite-fighting traditions of South Asia, in which abrasive-coated strings are used to cut rivals' lines, demonstrate how a single object can simultaneously embody playful leisure, serious competitive skill, and the ingenuity of material improvisation.", "complex_relative_clause_parallel"),
        ],
    },
    "baseball bat": {
        "beginner": [
            ("A baseball bat is long and heavy.", "simple_present_adjective"),
            ("The player hit the ball with a bat.", "simple_past"),
            ("Baseball bats are made of wood or metal.", "simple_present_material"),
            ("I saw a baseball bat in the sports shop.", "simple_past"),
            ("The bat broke when he hit the ball hard.", "simple_past_compound"),
        ],
        "elementary": [
            ("Can you hit a ball with a heavy baseball bat?", "modal_can_question"),
            ("There is a wooden baseball bat on the sports shelf.", "there_is_adjective_location"),
            ("There are different sizes of baseball bat for different players.", "there_are_plural"),
            ("Could a cricket bat and a baseball bat be used for the same sport?", "modal_could_comparison_question"),
            ("Can you learn to swing a baseball bat correctly in one lesson?", "modal_can_question"),
        ],
        "intermediate": [
            ("A baseball bat is heavier than a cricket bat, so it requires more strength to swing quickly.", "comparative_so_clause"),
            ("If you watch American baseball matches online, you will see how the bat is used to hit fast-moving pitches.", "first_conditional_observation"),
            ("The batter gripped the bat tightly, swung with all his strength, and sent the ball flying over the boundary.", "compound_sentence_past_series"),
            ("Baseball bats made from maple wood are more popular than those made from ash because maple is harder and more durable.", "comparative_because_clause"),
            ("If you have never played baseball before, you might find swinging the bat and hitting a moving ball quite difficult at first.", "first_conditional"),
        ],
        "upper_intermediate": [
            ("The baseball bat that was used to hit the record-breaking home run was donated to the Hall of Fame museum.", "relative_clause_passive_past"),
            ("Professional baseball bats are now tested for performance specifications before being approved for use in Major League games.", "passive_voice_present_before_passive"),
            ("The aluminium bat, which had been confiscated by the umpire, was found to have exceeded the permitted barrel diameter.", "non_defining_relative_clause_passive_past"),
            ("It is widely known that the crack of a wooden bat and the ping of a metal bat produce distinctly different sounds that players find psychologically different.", "passive_impersonal_compound_relative_clause"),
            ("Corked baseball bats, which are illegal in professional play, were historically used by some batters who believed they provided more power despite scientific evidence to the contrary.", "non_defining_relative_clause_passive_contrast"),
        ],
        "advanced": [
            ("The physics of the baseball bat swing — the interplay of moment of inertia, sweet spot location, and vibrational node positioning — has been the subject of surprisingly rigorous mechanical engineering studies driven by the competitive incentives of professional sport.", "sophisticated_dash_passive_participial"),
            ("For students in India encountering a baseball bat for the first time, the natural point of reference is the cricket bat, yet the two implements are optimised for fundamentally different striking techniques: the cricket bat's flat face for ground strokes, the baseball bat's cylindrical barrel for full rotational swings.", "complex_yet_contrast_dash_parallel"),
            ("The ongoing debate in American baseball over whether aluminium bats should be permitted at collegiate level reflects a genuine tension between player safety concerns, the economics of equipment replacement, and the traditionalist argument that the wooden bat is constitutive of the sport's identity.", "complex_whether_subordination_list"),
            ("Biomechanical analyses of elite batters have revealed that the kinetic chain from hip rotation through torso and arms to bat contributes more to bat speed than raw upper body strength, a finding that has substantially influenced training methodologies at professional academies.", "complex_passive_relative_clause"),
            ("The gradual globalisation of baseball beyond its North American heartland has created new markets in Asia and Latin America where bat manufacturing traditions are evolving distinct regional characteristics, subtly diversifying a tool that was once standardised with near-religious rigidity.", "sophisticated_where_relative_passive_contrast"),
        ],
    },
    "baseball glove": {
        "beginner": [
            ("A baseball glove protects the player's hand.", "simple_present_purpose"),
            ("The glove is made of thick leather.", "simple_present_material"),
            ("He caught the ball in his glove.", "simple_past"),
            ("Baseball gloves are big and padded.", "simple_present_adjective"),
            ("She practised catching with her new glove.", "simple_past"),
        ],
        "elementary": [
            ("Can you catch a fast ball without a baseball glove?", "modal_can_question"),
            ("There is a brown leather baseball glove in the sports bag.", "there_is_adjective_location"),
            ("There are different gloves for different positions in baseball.", "there_are_plural"),
            ("Could you explain why a baseball glove has a webbed pocket?", "modal_could_explanation_question"),
            ("Can a catcher's glove be used in the outfield?", "modal_can_question"),
        ],
        "intermediate": [
            ("A baseball glove is larger and more padded than a regular sports glove because it must absorb the impact of a fast-moving ball.", "comparative_because_clause"),
            ("If you see a baseball game online, you will notice how smoothly the fielder uses the glove to catch the ball.", "first_conditional_observation"),
            ("The outfielder sprinted back, reached up with his glove, and made a stunning catch at the boundary wall.", "compound_sentence_past_series"),
            ("Baseball gloves are broken in over time, and players often use special oils and techniques to soften the leather and shape the pocket.", "compound_sentence_present"),
            ("If you want to understand how different gloves work, you could watch a video comparing a catcher's mitt, an infielder's glove, and an outfielder's glove.", "first_conditional_comparison"),
        ],
        "upper_intermediate": [
            ("The baseball glove that was found in the storeroom turned out to belong to a former school champion from twenty years ago.", "relative_clause_past"),
            ("In professional baseball, gloves are carefully selected and maintained by equipment managers who understand how each player's fielding style influences their equipment needs.", "passive_voice_relative_clause_present"),
            ("His worn leather glove, which had been used throughout his entire school baseball career, was framed and hung on the wall of the sports hall.", "non_defining_relative_clause_passive_past"),
            ("It is believed that the first baseball glove was used in the 1870s by a catcher who wanted to protect his hand from repeated impact injuries.", "passive_impersonal_belief_relative_clause"),
            ("Modern baseball gloves are engineered with reinforced stitching and shaped pockets designed to help fielders secure the ball as reliably as possible.", "passive_voice_present_passive_participle"),
        ],
        "advanced": [
            ("The evolution of the baseball glove from a thin, finger-less pad in the 1870s to today's precision-engineered leather instrument reflects the progressive professionalisation of a sport in which marginal fielding improvements can directly determine match outcomes.", "sophisticated_noun_phrase_subordination"),
            ("For students in India who are unfamiliar with baseball, the glove's unusual design — disproportionately large, stiff-webbed, worn only on the non-dominant hand — raises immediate questions about the biomechanics of catching a ball thrown at over 140 kilometres per hour.", "sophisticated_dash_relative_clause"),
            ("The process of breaking in a new baseball glove — a ritual involving oil application, deliberate stretching, and hundreds of catch repetitions — is regarded by serious players as a rite of passage through which the equipment becomes an extension of the player's fielding identity.", "sophisticated_dash_passive_relative_clause"),
            ("Glove-making craftsmen who specialise in custom fielding gloves for professional players must balance competing demands of weight, pocket depth, wrist support, and break stiffness, producing instruments that are simultaneously protective gear and highly personalised performance tools.", "complex_relative_clause_parallel_list"),
            ("The biomechanical principle underlying the baseball glove's design — that a large, flexible catching surface reduces the effective mass of the incoming projectile by extending the collision duration — illustrates how engineering solutions often arrive intuitively in sport long before the underlying physics is formally understood.", "sophisticated_dash_passive_subordination"),
        ],
    },
    "skateboard": {
        "beginner": [
            ("He rides his skateboard to school.", "simple_present_habit"),
            ("The skateboard has four small wheels.", "simple_present_possession"),
            ("She fell off the skateboard and hurt her knee.", "simple_past_compound"),
            ("Skateboards are made of wood and plastic.", "simple_present_material"),
            ("He practised tricks on his skateboard every evening.", "simple_past_habit"),
        ],
        "elementary": [
            ("Can you balance on a skateboard without holding anything?", "modal_can_question"),
            ("There is a decorated skateboard leaning against the wall.", "there_is_present_participle_location"),
            ("There are skateboarders practising tricks at the park.", "there_are_present_continuous"),
            ("Could you learn to skateboard if you already know how to balance on a bicycle?", "modal_could_conditional_question"),
            ("Can skateboarding be a safe sport if you wear the right protective gear?", "modal_can_conditional_question"),
        ],
        "intermediate": [
            ("Skateboarding is harder to master than cycling, but many young people find it more creative and expressive.", "comparative_compound_contrast"),
            ("If you always wear a helmet and knee pads when skateboarding, you will significantly reduce your risk of injury.", "first_conditional_advice"),
            ("He pushed off with his foot, gathered speed down the ramp, and launched into a perfect kickflip.", "compound_sentence_past_series"),
            ("Electric skateboards are more expensive than regular ones, but they are a convenient and eco-friendly way to travel short distances.", "comparative_compound_contrast"),
            ("If you watch skateboarding videos online, you will soon understand why it is considered both a sport and an art form.", "first_conditional_observation"),
        ],
        "upper_intermediate": [
            ("The skateboard that was customised with hand-painted graphics by a local artist was auctioned to raise money for the school sports fund.", "relative_clause_passive_past"),
            ("Skateboarding was officially recognised as an Olympic sport and was included in the Tokyo 2020 Games, where young competitors from around the world demonstrated extraordinary skill.", "passive_voice_compound_past"),
            ("His first skateboard, which had been a birthday gift from his uncle, was eventually worn down to bare wood after three years of daily use.", "non_defining_relative_clause_passive_past"),
            ("It is widely acknowledged that street skateboarding culture, which originated in California in the 1970s, has had a profound influence on global youth fashion, music, and art.", "passive_impersonal_relative_clause_past"),
            ("Skateparks built with smooth concrete transitions are now considered essential infrastructure in many cities, reflecting the recognition of skateboarding as a legitimate recreational activity for young people.", "passive_voice_present_participial"),
        ],
        "advanced": [
            ("The skateboard's cultural journey from a makeshift contraption built by Californian surfers seeking to replicate the sensation of wave-riding on dry land to an Olympic discipline demonstrates how subcultural innovations can, over decades, achieve mainstream institutional recognition.", "sophisticated_noun_phrase_subordination"),
            ("The precise physics of a skateboard trick — the interaction of foot placement, board torque, and rotational momentum — is rarely consciously analysed by practitioners who develop their skills through iterative bodily experimentation rather than formal instruction.", "sophisticated_dash_relative_clause_contrast"),
            ("Urban planners increasingly recognise that skateparks serve not only as recreational facilities but as important social infrastructure that provides young people with structured public space in which to develop physical skills, form peer relationships, and negotiate group norms.", "complex_not_only_but_relative_clause"),
            ("The commercialisation of skateboarding, accelerated by its Olympic inclusion, has generated tensions within the community between practitioners who value its counter-cultural roots and those who welcome the increased visibility, funding, and professional opportunity that mainstream status provides.", "complex_between_parallel_relative_clause"),
            ("Studies examining the psychological benefits of skateboarding have highlighted how the sport's intrinsic demand for repeated failure and incremental improvement cultivates resilience and a growth mindset in young practitioners, outcomes that are increasingly valued in educational discourse.", "complex_how_subordination_relative_clause"),
        ],
    },
    "surfboard": {
        "beginner": [
            ("A surfboard is long and flat.", "simple_present_adjective"),
            ("Surfers use a surfboard to ride waves.", "simple_present_purpose"),
            ("He saw a surfboard in a sports shop window.", "simple_past_location"),
            ("The surfboard was painted with bright colours.", "simple_past_passive"),
            ("Surfboards are used at the beach.", "simple_present_passive"),
        ],
        "elementary": [
            ("Can you stand on a surfboard without falling into the water?", "modal_can_question"),
            ("There is a long white surfboard on top of the car.", "there_is_adjective_location"),
            ("There are surfers with their boards waiting for the next wave.", "there_are_present_participle"),
            ("Could you learn to surf if you know how to swim well?", "modal_could_conditional_question"),
            ("Can a beginner use the same surfboard as a professional surfer?", "modal_can_comparison_question"),
        ],
        "intermediate": [
            ("Surfing is more physically demanding than it looks in videos, because you must paddle strongly and balance on a moving surface.", "comparative_because_clause"),
            ("If you ever visit a beach town in Goa or Kerala, you might see people carrying colourful surfboards towards the water.", "first_conditional_context"),
            ("The surfer paddled hard into the wave, jumped to his feet, and rode it all the way to the shore.", "compound_sentence_past_series"),
            ("A longboard surfboard is more stable than a shortboard, which makes it a better choice for beginners.", "comparative_which_relative_clause"),
            ("If the waves are too small, even the best surfer cannot put on an impressive display.", "first_conditional"),
        ],
        "upper_intermediate": [
            ("The surfboard that was shaped by a master craftsman in Hawaii was considered one of the finest performance boards of the year.", "relative_clause_passive_past"),
            ("Surfing was added to the Olympic programme at the Tokyo 2020 Games and was held at Tsurigasaki Beach, where the waves are consistently powerful.", "passive_voice_compound_past_relative_clause"),
            ("Her surfboard, which had been specially shaped for her height and weight, allowed her to perform aerial manoeuvres that few other competitors could match.", "non_defining_relative_clause_passive_past"),
            ("It is reported that surfing culture, which originated among the Polynesian peoples thousands of years ago, spread to the rest of the world largely through Hawaii in the early twentieth century.", "passive_impersonal_relative_clause_past"),
            ("Lightweight foam-core surfboards covered with fibreglass are now manufactured to a high standard and are affordable enough for recreational surfers at most skill levels.", "passive_voice_present_compound_adjective"),
        ],
        "advanced": [
            ("The surfboard's design has undergone extraordinary refinement over the past century, evolving from the massive solid koa wood planks ridden by Hawaiian royalty to the featherlight, precision-contoured polyurethane and fibreglass structures used in contemporary competitive surfing.", "sophisticated_noun_phrase_participial_contrast"),
            ("For students in Tamil Nadu, the surfboard represents an object encountered primarily through international sports media, yet the Bay of Bengal coastline offers genuine surf potential that a small but growing community of local surfers is beginning to explore.", "complex_yet_contrast_relative_clause"),
            ("The hydrodynamics of surfboard design — the relationship between rocker profile, concave bottom geometry, and fin configuration — constitute a specialised engineering domain in which incremental refinements can produce measurable differences in wave-holding and turning responsiveness.", "sophisticated_dash_relative_clause_passive"),
            ("Environmental activists have drawn attention to the surfing industry's complicated ecological relationship with the ocean it celebrates, pointing out that conventional surfboard manufacturing relies on petroleum-derived polyurethane foam and polyester resin, both of which are non-biodegradable.", "complex_participial_relative_clause_passive"),
            ("The cultural philosophy of surfing — a practice governed by an unwritten code of wave etiquette, localism, and a quasi-spiritual reverence for ocean conditions — sits in productive tension with its increasing commercialisation as an Olympic sport and global lifestyle brand.", "sophisticated_dash_relative_clause_contrast"),
        ],
    },
    "tennis racket": {
        "beginner": [
            ("She hit the ball with her tennis racket.", "simple_present_habit"),
            ("A tennis racket has a long handle.", "simple_present_possession"),
            ("The tennis racket is light and strong.", "simple_present_adjective"),
            ("He bought a new tennis racket last week.", "simple_past"),
            ("The strings of the racket broke during the match.", "simple_past"),
        ],
        "elementary": [
            ("Can you serve a ball over the net with a tennis racket?", "modal_can_question"),
            ("There is a tennis racket and two balls in the bag.", "there_is_coordination"),
            ("There are several tennis rackets in different sizes at the club.", "there_are_plural"),
            ("Could you teach me how to hold a tennis racket correctly?", "modal_could_request"),
            ("Can a lighter racket help you swing faster?", "modal_can_question"),
        ],
        "intermediate": [
            ("A heavier tennis racket provides more power, but a lighter one gives you better control of the ball.", "comparative_compound_contrast"),
            ("If you grip the racket too tightly, your arm will tire quickly and your shots will become less accurate.", "first_conditional_advice"),
            ("She tossed the ball high, brought the racket back smoothly, and served an ace down the centre line.", "compound_sentence_past_series"),
            ("Modern tennis rackets are made from graphite and carbon fibre, which makes them much lighter than the wooden rackets used decades ago.", "passive_voice_which_relative_clause"),
            ("If the strings lose tension over time, you should have them professionally restrung to restore the racket's performance.", "first_conditional_advice_passive"),
        ],
        "upper_intermediate": [
            ("The tennis racket that was used by the champion to win three consecutive Grand Slams is now on display in the Wimbledon museum.", "relative_clause_passive_past"),
            ("String tension in a tennis racket is carefully calibrated by professional stringers according to each player's preferred balance of power and control.", "passive_voice_present_according_to"),
            ("Her favourite racket, which had been custom-strung at eighteen kilograms of tension, gave her the precise feel she needed for her baseline game.", "non_defining_relative_clause_passive_past"),
            ("It is widely acknowledged that the development of graphite-composite racket frames in the 1980s fundamentally changed the power dynamics of the modern game.", "passive_impersonal_belief_past"),
            ("Tennis rackets are tested for frame stiffness and string-bed response before being approved for use in professional tournaments sanctioned by the ITF.", "passive_voice_present_before_passive"),
        ],
        "advanced": [
            ("The engineering of a modern tennis racket involves a precise trade-off between frame stiffness, which enhances power transfer, and flexibility, which reduces the shock transmitted to the player's arm and lowers the risk of repetitive strain injury.", "sophisticated_relative_clause_parallel_contrast"),
            ("The shift from wooden to graphite tennis rackets over the 1980s is widely regarded as the single most transformative equipment change in the sport's history, enabling a style of aggressive baseline play that was physically impossible with the heavier, more flexible wooden frames.", "passive_voice_complex_participial"),
            ("Professional players' relationships with their rackets are often described in almost intimate terms — preferences for specific grip shapes, string gauges, and even individual frames within the same model — suggesting that the racket functions as an extension of bodily schema rather than a mere tool.", "sophisticated_dash_relative_clause_subordination"),
            ("Biomechanical studies of elite tennis strokes have demonstrated that the kinetic energy transferred to the ball is generated primarily in the legs and trunk rather than in the arm and racket, a finding with direct implications for how coaches should structure technical training programmes.", "complex_passive_relative_clause_implication"),
            ("The globalisation of tennis and the emergence of champions from countries with no historic relationship to the sport — from Spain's clay-court academies to Serbia's improvised training facilities — have demonstrated that talent development is more a function of systematic coaching methodology than of inherited cultural advantage.", "sophisticated_dash_parallel_passive_complex"),
        ],
    },
    "bottle": {
        "beginner": [
            ("She drinks water from her bottle every hour.", "simple_present_habit"),
            ("The bottle is made of blue plastic.", "simple_present_material"),
            ("He filled his bottle at the water tap.", "simple_past"),
            ("I carry a water bottle in my school bag.", "simple_present_habit"),
            ("The glass bottle fell and broke.", "simple_past_compound"),
        ],
        "elementary": [
            ("Can you finish the whole bottle of water during recess?", "modal_can_question"),
            ("There is an empty bottle rolling on the classroom floor.", "there_is_present_continuous"),
            ("There are several reusable water bottles on the teacher's desk.", "there_are_adjective"),
            ("Could you pass me that bottle of water, please?", "modal_could_request"),
            ("Can a stainless steel bottle keep water cold all day?", "modal_can_question"),
        ],
        "intermediate": [
            ("A stainless steel bottle keeps water colder for longer than a plastic bottle, especially in hot weather.", "comparative_especially_clause"),
            ("If you remember to refill your bottle before class, you will stay hydrated and find it easier to concentrate.", "first_conditional_advice"),
            ("She unscrewed the cap, took a long drink, and immediately felt more energetic in the afternoon heat.", "compound_sentence_past_series"),
            ("Single-use plastic bottles are cheaper than reusable ones, but they create enormous amounts of plastic waste that pollutes rivers and oceans.", "comparative_compound_contrast_relative_clause"),
            ("If everyone in the school brought a reusable bottle, we could eliminate thousands of plastic bottles from landfill every year.", "second_conditional"),
        ],
        "upper_intermediate": [
            ("The bottle of water that was left in the sun all day had become too warm to drink by the time the match ended.", "relative_clause_past_result"),
            ("Single-use plastic bottles are now banned in several Indian states as part of broader campaigns to reduce plastic pollution in public spaces.", "passive_voice_present_purpose"),
            ("Her insulated bottle, which could keep drinks cold for up to twenty-four hours, was an indispensable item during the long summer trek.", "non_defining_relative_clause_modal_past"),
            ("It is estimated that over one million plastic bottles are purchased globally every minute, making plastic bottle waste one of the most significant contributors to ocean pollution.", "passive_impersonal_estimate_participial"),
            ("Reusable bottles made from food-grade stainless steel or borosilicate glass are increasingly preferred over plastic alternatives by environmentally conscious consumers.", "passive_voice_present_comparative_passive"),
        ],
        "advanced": [
            ("The seemingly mundane plastic water bottle has become one of the most potent symbols of the global single-use plastics crisis, its ubiquity and disposability making it a convenient target for environmental campaigns seeking to change consumer behaviour at scale.", "sophisticated_participial_relative_clause"),
            ("The chemistry of plastic leaching — whereby certain compounds from PET bottles migrate into the water they contain, particularly when the bottle is exposed to heat or repeated use — has generated ongoing scientific debate and consumer anxiety that bottled water companies have been slow to address transparently.", "sophisticated_dash_relative_clause_passive_contrast"),
            ("Designers working on alternatives to conventional bottle formats are exploring everything from edible seaweed capsules to dissolvable packaging, innovations that challenge the assumption that hydration on the go necessarily requires a durable, reusable container.", "complex_participial_relative_clause"),
            ("The economics of bottled water in countries with safe tap water supply represent a striking example of how marketing can construct perceived value around a resource that is freely available, generating a multi-billion dollar industry premised substantially on anxiety and convenience rather than genuine necessity.", "sophisticated_relative_clause_passive_contrast"),
            ("India's Jal Jeevan Mission, which aims to provide piped drinking water to every rural household, carries profound implications for the bottled water market, because widespread access to safe tap water would logically reduce dependence on both single-use and refillable bottles among populations currently reliant on purchased water.", "complex_relative_clause_because_conditional"),
        ],
    },
}
