"""initial schema

Revision ID: a470122ec6ff
Revises: 
Create Date: 2026-03-14 21:54:28.706775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a470122ec6ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.Text(), nullable=True),
    sa.Column('target_objects_json', sa.Text(), nullable=True),
    sa.Column('target_level', sa.Text(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_members',
    sa.Column('class_id', sa.Text(), nullable=False),
    sa.Column('learner_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('class_id', 'learner_id')
    )
    op.create_table('classes',
    sa.Column('class_id', sa.Text(), nullable=False),
    sa.Column('teacher_name', sa.Text(), nullable=True),
    sa.Column('class_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('daily_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('sessions_completed', sa.Integer(), nullable=True),
    sa.Column('sentences_practiced', sa.Integer(), nullable=True),
    sa.Column('minutes_practiced', sa.Float(), nullable=True),
    sa.Column('avg_pronunciation', sa.Float(), nullable=True),
    sa.Column('avg_fluency', sa.Float(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('new_words_learned', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'date')
    )
    op.create_table('generated_prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_name', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.Text(), nullable=True),
    sa.Column('prompt_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('l1_transfer_predictions',
    sa.Column('learner_id', sa.Text(), nullable=False),
    sa.Column('phoneme', sa.Text(), nullable=False),
    sa.Column('predicted_difficult', sa.Boolean(), nullable=True),
    sa.Column('actual_accuracy', sa.Float(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('learner_id', 'phoneme')
    )
    op.create_table('learner_profiles',
    sa.Column('learner_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('native_language', sa.Text(), nullable=True),
    sa.Column('current_level', sa.Text(), nullable=True),
    sa.Column('classroom', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('xp_total', sa.Integer(), nullable=True),
    sa.Column('streak_current', sa.Integer(), nullable=True),
    sa.Column('streak_longest', sa.Integer(), nullable=True),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('learner_id')
    )
    op.create_table('learner_vocabulary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.Text(), nullable=True),
    sa.Column('word', sa.Text(), nullable=True),
    sa.Column('phonemes_arpabet', sa.Text(), nullable=True),
    sa.Column('times_practiced', sa.Integer(), nullable=True),
    sa.Column('avg_pronunciation', sa.Float(), nullable=True),
    sa.Column('mastery_level', sa.Text(), nullable=True),
    sa.Column('last_practiced', sa.DateTime(), nullable=True),
    sa.Column('context_sentence', sa.Text(), nullable=True),
    sa.Column('detected_object', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'word')
    )
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('learner_id', sa.Text(), nullable=True),
    sa.Column('object_name', sa.Text(), nullable=True),
    sa.Column('scene_objects_json', sa.Text(), nullable=True),
    sa.Column('sentence_text', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.Text(), nullable=True),
    sa.Column('sentence_type', sa.Text(), nullable=True),
    sa.Column('grammar_focus', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('reading_accuracy', sa.Float(), nullable=True),
    sa.Column('reading_classification', sa.Text(), nullable=True),
    sa.Column('wer', sa.Float(), nullable=True),
    sa.Column('word_alignment_json', sa.Text(), nullable=True),
    sa.Column('missed_words_json', sa.Text(), nullable=True),
    sa.Column('filler_count', sa.Integer(), nullable=True),
    sa.Column('repetition_count', sa.Integer(), nullable=True),
    sa.Column('pronunciation_score', sa.Float(), nullable=True),
    sa.Column('per_ml', sa.Float(), nullable=True),
    sa.Column('ml_gop', sa.Float(), nullable=True),
    sa.Column('ml_confidence', sa.Float(), nullable=True),
    sa.Column('ml_detected_phonemes_json', sa.Text(), nullable=True),
    sa.Column('ml_detected_ipa_json', sa.Text(), nullable=True),
    sa.Column('ml_alignment_json', sa.Text(), nullable=True),
    sa.Column('ml_phoneme_scores_json', sa.Text(), nullable=True),
    sa.Column('problematic_phonemes_json', sa.Text(), nullable=True),
    sa.Column('speech_rate', sa.Float(), nullable=True),
    sa.Column('prosody_score', sa.Float(), nullable=True),
    sa.Column('stress_accuracy', sa.Float(), nullable=True),
    sa.Column('intonation_accuracy', sa.Float(), nullable=True),
    sa.Column('rhythm_npvi_v', sa.Float(), nullable=True),
    sa.Column('pitch_range_st', sa.Float(), nullable=True),
    sa.Column('mfa_textgrid_path', sa.Text(), nullable=True),
    sa.Column('prosody_details_json', sa.Text(), nullable=True),
    sa.Column('words_per_minute', sa.Float(), nullable=True),
    sa.Column('articulation_rate', sa.Float(), nullable=True),
    sa.Column('mean_length_of_run', sa.Float(), nullable=True),
    sa.Column('longest_fluent_phrase', sa.Integer(), nullable=True),
    sa.Column('hesitation_ratio', sa.Float(), nullable=True),
    sa.Column('mid_phrase_pause_rate', sa.Float(), nullable=True),
    sa.Column('filled_pause_rate', sa.Float(), nullable=True),
    sa.Column('repetition_rate', sa.Float(), nullable=True),
    sa.Column('total_pauses', sa.Integer(), nullable=True),
    sa.Column('hesitation_count', sa.Integer(), nullable=True),
    sa.Column('speaking_rate', sa.Float(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('pauses_json', sa.Text(), nullable=True),
    sa.Column('word_scores_json', sa.Text(), nullable=True),
    sa.Column('utterance_accuracy', sa.Float(), nullable=True),
    sa.Column('utterance_completeness', sa.Float(), nullable=True),
    sa.Column('utterance_fluency', sa.Float(), nullable=True),
    sa.Column('utterance_prosody', sa.Float(), nullable=True),
    sa.Column('utterance_total', sa.Float(), nullable=True),
    sa.Column('analysis_mode', sa.Text(), nullable=True),
    sa.Column('tts_audio_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('learner_id', sa.Text(), nullable=True),
    sa.Column('avg_pronunciation', sa.Float(), nullable=True),
    sa.Column('avg_fluency', sa.Float(), nullable=True),
    sa.Column('sentences_completed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spaced_repetition_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.Text(), nullable=True),
    sa.Column('phoneme', sa.Text(), nullable=True),
    sa.Column('interval_days', sa.Float(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('easiness_factor', sa.Float(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('last_score', sa.Float(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'phoneme')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spaced_repetition_queue')
    op.drop_table('session_progress')
    op.drop_table('recordings')
    op.drop_table('learner_vocabulary')
    op.drop_table('learner_profiles')
    op.drop_table('l1_transfer_predictions')
    op.drop_table('generated_prompts')
    op.drop_table('daily_progress')
    op.drop_table('classes')
    op.drop_table('class_members')
    op.drop_table('class_assignments')
    # ### end Alembic commands ###
